// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f85bd377c2637194a3e43213d7beed980aca3a6615206b2575294dda6fca4afa
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    setupFiles: ["./setup.ts"],
  },
});
