# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:59e5d4536e170937d8e1fdfb7ccbfc886987a6d4f7950558146493c6f246e446
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: async
defmodule E2e.AsyncTest do
  use ExUnit.Case, async: false

  describe "async_extract_bytes" do
    @tag :skip
    test "Async extract_bytes call on PDF document" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "async_extract_bytes_empty_mime" do
    @tag :skip
    test "extract_bytes empty MIME async" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "async_extract_bytes_invalid_mime" do
    @tag :skip
    test "extract_bytes unsupported MIME async" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "async_extract_file" do
    @tag :skip
    test "Async extract_file call on PDF document" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "async_extract_file_docx" do
    @tag :skip
    test "Async extract_file call on DOCX document" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "async_extract_file_html" do
    @tag :skip
    test "Async extract_file call on HTML document" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "async_extract_file_image" do
    @tag :skip
    test "Async extract_file call on image document" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "async_extract_file_with_config" do
    @tag :skip
    test "Async extract_file call with output format and chunking config" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end
end
