# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3f520cdf98affe88c470c24f89244a7f157020098825b59ab68a898c8585d591
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: extraction
defmodule E2e.ExtractionTest do
  use ExUnit.Case, async: false

  describe "extract_doc_basic" do
    @tag :skip
    test "Extract text from a DOC file containing unit test lists" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "extract_email_basic" do
    @tag :skip
    test "Extract content from an email file in EML format" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "extract_pdf_basic" do
    @tag :skip
    test "Extract text from a basic PDF document containing memo content" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "extract_pdf_code" do
    @tag :skip
    test "Extract text from PDF containing code snippets and formulas" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "extract_pptx_basic" do
    @tag :skip
    test "Extract text from a PowerPoint presentation file" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end
end
