# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c16bb1ff9364e512d920f6d5c2dd5b04212344898c49d5fef184907f5113368a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: registry_operations
defmodule E2e.RegistryOperationsTest do
  use ExUnit.Case, async: false

  describe "extensions_docx" do
    @tag :skip
    test "Get file extensions for DOCX MIME type" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "extensions_html" do
    @tag :skip
    test "Get file extensions for HTML MIME type" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "extensions_pdf" do
    @tag :skip
    test "Get file extensions for PDF MIME type" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end

  describe "list_formats_all" do
    @tag :skip
    test "List all supported formats and their extensions" do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end
end
