# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cea2aa1166bd0a5536e1b51a7e5a1dd0df37811e1eefe277623cebb1cca95641
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: xml
defmodule E2e.XmlTest do
  use ExUnit.Case, async: false

  describe "xml_plant_catalog" do
    @tag :skip
    test "XML plant catalog to validate streaming XML extraction." do
      # non-HTTP fixture: Elixir binding does not expose a callable for the configured `[e2e.call]` function
      :ok
    end
  end
end
