// Generated by alef. Do not edit by hand.

import Foundation
import RustBridge

/// Configuration for an LLM provider/model via liter-llm.
///
/// Each feature (VLM OCR, VLM embeddings, structured extraction) carries
/// its own `LlmConfig`, allowing different providers per feature.
///
/// # Example
///
/// ```toml
/// [structured_extraction.llm]
/// model = "openai/gpt-4o"
/// api_key = "sk-..."  # or use KREUZBERG_LLM_API_KEY env var
/// ```
public typealias LlmConfig = RustBridge.LlmConfig

/// Structured table grid with cell-level metadata.
///
/// Stores row/column dimensions and a flat list of cells with position info.
public typealias TableGrid = RustBridge.TableGrid

/// Excel/spreadsheet format metadata.
///
/// Identifies the document as a spreadsheet source via the `FormatMetadata::Excel`
/// discriminant. Sheet count and sheet names are stored inside this struct.
public typealias ExcelMetadata = RustBridge.ExcelMetadata

/// Email metadata extracted from .eml and .msg files.
///
/// Includes sender/recipient information, message ID, and attachment list.
public typealias EmailMetadata = RustBridge.EmailMetadata

/// Archive (ZIP/TAR/7Z) metadata.
///
/// Extracted from compressed archive files containing file lists and size information.
public typealias ArchiveMetadata = RustBridge.ArchiveMetadata

/// XML metadata extracted during XML parsing.
///
/// Provides statistics about XML document structure.
public typealias XmlMetadata = RustBridge.XmlMetadata

/// Text/Markdown metadata.
///
/// Extracted from plain text and Markdown files. Includes word counts and,
/// for Markdown, structural elements like headers and links.
public typealias TextMetadata = RustBridge.TextMetadata

/// HTML metadata extracted from HTML documents.
///
/// Includes document-level metadata, Open Graph data, Twitter Card metadata,
/// and extracted structural elements (headers, links, images, structured data).
public typealias HtmlMetadata = RustBridge.HtmlMetadata

/// OCR processing metadata.
///
/// Captures information about OCR processing configuration and results.
public typealias OcrMetadata = RustBridge.OcrMetadata

/// PowerPoint presentation metadata.
///
/// Extracted from PPTX files containing slide counts and presentation details.
public typealias PptxMetadata = RustBridge.PptxMetadata

/// Word document metadata.
///
/// Extracted from DOCX files using shared Office Open XML metadata extraction.
/// Integrates with `office_metadata` module for core/app/custom properties.
public typealias DocxMetadata = RustBridge.DocxMetadata

/// CSV/TSV file metadata.
public typealias CsvMetadata = RustBridge.CsvMetadata

/// BibTeX bibliography metadata.
public typealias BibtexMetadata = RustBridge.BibtexMetadata

/// Citation file metadata (RIS, PubMed, EndNote).
public typealias CitationMetadata = RustBridge.CitationMetadata

/// FictionBook (FB2) metadata.
public typealias FictionBookMetadata = RustBridge.FictionBookMetadata

/// dBASE (DBF) file metadata.
public typealias DbfMetadata = RustBridge.DbfMetadata

/// JATS (Journal Article Tag Suite) metadata.
public typealias JatsMetadata = RustBridge.JatsMetadata

/// EPUB metadata (Dublin Core extensions).
public typealias EpubMetadata = RustBridge.EpubMetadata

/// Outlook PST archive metadata.
public typealias PstMetadata = RustBridge.PstMetadata

/// ONNX Runtime execution provider type.
///
/// Determines which hardware backend is used for model inference.
/// `Auto` (default) selects the best available provider per platform.
public enum ExecutionProviderType {
    /// Auto-select: CoreML on macOS, CUDA on Linux, CPU elsewhere.
    case auto
    /// CPU execution provider (always available).
    case cpu
    /// Apple CoreML (macOS/iOS Neural Engine + GPU).
    case coreMl
    /// NVIDIA CUDA GPU acceleration.
    case cuda
    /// NVIDIA TensorRT (optimized CUDA inference).
    case tensorRt
}

/// Output format for extraction results.
///
/// Controls the format of the `content` field in `ExtractionResult`.
/// When set to `Markdown`, `Djot`, or `Html`, the output will be formatted
/// accordingly. `Plain` returns the raw extracted text.
/// `Structured` returns JSON with full OCR element data including bounding
/// boxes and confidence scores.
public enum OutputFormat {
    /// Plain text content only (default)
    case plain
    /// Markdown format
    case markdown
    /// Djot markup format
    case djot
    /// HTML format
    case html
    /// JSON tree format with heading-driven sections.
    case json
    /// Structured JSON format with full OCR element metadata.
    case structured
    /// Custom renderer registered via the RendererRegistry.
    /// The string is the renderer name (e.g., "docx", "latex").
    case custom(field0: String)
}

/// Built-in HTML theme selection.
public enum HtmlTheme {
    /// Sensible defaults: system font stack, neutral colours, readable line
    /// measure. CSS custom properties (`--kb-*`) are all defined so user CSS
    /// can override individual values.
    case default_
    /// GitHub Markdown-inspired palette and spacing.
    case gitHub
    /// Dark background, light text.
    case dark
    /// Minimal light theme with generous whitespace.
    case light
    /// No built-in stylesheet emitted. CSS custom properties are still defined
    /// on `:root` so user stylesheets can reference `var(--kb-*)` tokens.
    case unstyled
}

/// Which table structure recognition model to use.
///
/// Controls the model used for table cell detection within layout-detected
/// table regions.
public enum TableModel {
    /// TATR (Table Transformer) -- default, 30MB, DETR-based row/column detection.
    case tatr
    /// SLANeXT wired variant -- 365MB, optimized for bordered tables.
    case slanetWired
    /// SLANeXT wireless variant -- 365MB, optimized for borderless tables.
    case slanetWireless
    /// SLANet-plus -- 7.78MB, lightweight general-purpose.
    case slanetPlus
    /// Classifier-routed SLANeXT: auto-select wired/wireless per table.
    /// Uses PP-LCNet classifier (6.78MB) + both SLANeXT variants (730MB total).
    case slanetAuto
    /// Disable table structure model inference entirely; use heuristic path only.
    case disabled
}

/// Type of text chunker to use.
///
/// # Variants
///
/// * `Text` - Generic text splitter, splits on whitespace and punctuation
/// * `Markdown` - Markdown-aware splitter, preserves formatting and structure
/// * `Yaml` - YAML-aware splitter, creates one chunk per top-level key
/// * `Semantic` - Topic-aware chunker. With an `EmbeddingConfig`, splits at
///   embedding-based topic shifts tuned by `topic_threshold` (default 0.75,
///   lower = more splits). Without an embedding, falls back to a
///   structural-boundary heuristic (ALL-CAPS headers, numbered sections,
///   blank-line paragraphs) and merges groups into chunks capped at
///   `max_characters` (default 1000). `topic_threshold` has no effect in the
///   fallback path. For best results, pair with an embedding model.
public enum ChunkerType {
    case text
    case markdown
    case yaml
    case semantic
}

/// How chunk size is measured.
///
/// Defaults to `Characters` (Unicode character count). When using token-based sizing,
/// chunks are sized by token count according to the specified tokenizer.
///
/// Token-based sizing uses HuggingFace tokenizers loaded at runtime. Any tokenizer
/// available on HuggingFace Hub can be used, including OpenAI-compatible tokenizers
/// (e.g., `Xenova/gpt-4o`, `Xenova/cl100k_base`).
public enum ChunkSizing {
    /// Size measured in Unicode characters (default).
    case characters
    /// Size measured in tokens from a HuggingFace tokenizer.
    case tokenizer(model: String, cacheDir: URL)
}

/// Embedding model types supported by Kreuzberg.
public enum EmbeddingModelType {
    /// Use a preset model configuration (recommended)
    case preset(name: String)
    /// Use a custom ONNX model from HuggingFace
    case custom(modelId: String, dimensions: UInt)
    /// Provider-hosted embedding model via liter-llm.
    ///
    /// Uses the model specified in the nested `LlmConfig` (e.g.,
    /// `"openai/text-embedding-3-small"`).
    case llm(llm: LlmConfig)
    /// In-process embedding backend registered via the plugin system.
    ///
    /// The caller registers an [`EmbeddingBackend`](crate::plugins::EmbeddingBackend) once
    /// (e.g. a wrapper around an already-loaded `llama-cpp-python`, `sentence-transformers`,
    /// or tuned ONNX model), then references it by name in config. Kreuzberg calls back
    /// into the registered backend during chunking and standalone embed requests —
    /// no HuggingFace download, no ONNX Runtime requirement, no HTTP sidecar.
    ///
    /// When this variant is selected, only the following [`EmbeddingConfig`] fields
    /// apply: `normalize` (post-call L2 normalization) and `max_embed_duration_secs`
    /// (dispatcher timeout). Model-loading fields (`batch_size`, `cache_dir`,
    /// `show_download_progress`, `acceleration`) are ignored — the host owns the
    /// model lifecycle.
    ///
    /// Semantic chunking falls back to [`ChunkingConfig::max_characters`] when this variant
    /// is used, since there is no preset to look a chunk-size ceiling up against — size your
    /// context window via `max_characters` directly.
    ///
    /// See `register_embedding_backend`.
    case plugin(name: String)
}

/// Content rendering mode for code extraction.
///
/// Controls how extracted code content is represented in the `content` field
/// of `ExtractionResult`.
public enum CodeContentMode {
    /// Use TSLP semantic chunks as content (default).
    case chunks
    /// Use raw source code as content.
    case raw
    /// Emit function/class headings + docstrings (no code bodies).
    case structure
}

public enum FracType {
    case bar
    case noBar
    case linear
    case skewed
}

/// OCR backend types.
public enum OcrBackendType {
    /// Tesseract OCR (native Rust binding)
    case tesseract
    /// EasyOCR (Python-based, via FFI)
    case easyOcr
    /// PaddleOCR (Python-based, via FFI)
    case paddleOcr
    /// Custom/third-party OCR backend
    case custom
}

/// Processing stages for post-processors.
///
/// Post-processors are executed in stage order (Early → Middle → Late).
/// Use stages to control the order of post-processing operations.
public enum ProcessingStage {
    /// Early stage - foundational processing.
    ///
    /// Use for:
    /// - Language detection
    /// - Character encoding normalization
    /// - Entity extraction (NER)
    /// - Text quality scoring
    case early
    /// Middle stage - content transformation.
    ///
    /// Use for:
    /// - Keyword extraction
    /// - Token reduction
    /// - Text summarization
    /// - Semantic analysis
    case middle
    /// Late stage - final enrichment.
    ///
    /// Use for:
    /// - Custom user hooks
    /// - Analytics/logging
    /// - Final validation
    /// - Output formatting
    case late
}

public enum ReductionLevel {
    case off
    case light
    case moderate
    case aggressive
    case maximum
}

/// Type of PDF annotation.
public enum PdfAnnotationType {
    /// Sticky note / text annotation
    case text
    /// Highlighted text region
    case highlight
    /// Hyperlink annotation
    case link
    /// Rubber stamp annotation
    case stamp
    /// Underline text markup
    case underline
    /// Strikeout text markup
    case strikeOut
    /// Any other annotation type
    case other
}

/// Types of block-level elements in Djot.
public enum BlockType {
    case paragraph
    case heading
    case blockquote
    case codeBlock
    case listItem
    case orderedList
    case bulletList
    case taskList
    case definitionList
    case definitionTerm
    case definitionDescription
    case div
    case section
    case thematicBreak
    case rawBlock
    case mathDisplay
}

/// Types of inline elements in Djot.
public enum InlineType {
    case text
    case strong
    case emphasis
    case highlight
    case subscript_
    case superscript
    case insert
    case delete
    case code
    case link
    case image
    case span
    case math
    case rawInline
    case footnoteRef
    case symbol
}

/// Semantic kind of a relationship between document elements.
public enum RelationshipKind {
    /// Footnote marker -> footnote definition.
    case footnoteReference
    /// Citation marker -> bibliography entry.
    case citationReference
    /// Internal anchor link (`#id`) -> target heading/element.
    case internalLink
    /// Caption paragraph -> figure/table it describes.
    case caption
    /// Label -> labeled element (HTML `<label for>`, LaTeX `\label{}`).
    case label
    /// TOC entry -> target section.
    case tocEntry
    /// Cross-reference (LaTeX `\ref{}`, DOCX cross-reference field).
    case crossReference
}

/// Content layer classification for document nodes.
///
/// Replaces separate body/furniture arrays with per-node granularity.
public enum ContentLayer {
    /// Main document body content.
    case body
    /// Page/section header (running header).
    case header
    /// Page/section footer (running footer).
    case footer
    /// Footnote content.
    case footnote
}

/// Tagged enum for node content. Each variant carries only type-specific data.
///
/// Uses `#[serde(tag = "node_type")]` to avoid "type" keyword collision in
/// Go/Java/TypeScript bindings.
public enum NodeContent {
    /// Document title.
    case title(text: String)
    /// Section heading with level (1-6).
    case heading(level: UInt8, text: String)
    /// Body text paragraph.
    case paragraph(text: String)
    /// List container — children are `ListItem` nodes.
    case list(ordered: Bool)
    /// Individual list item.
    case listItem(text: String)
    /// Table with structured cell grid.
    case table(grid: TableGrid)
    /// Image reference.
    case image(description: String, imageIndex: UInt32, src: String)
    /// Code block.
    case code(text: String, language: String)
    /// Block quote — container, children carry the quoted content.
    case quote
    /// Mathematical formula / equation.
    case formula(text: String)
    /// Footnote reference content.
    case footnote(text: String)
    /// Logical grouping container (section, key-value area).
    ///
    /// `heading_level` + `heading_text` capture the section heading directly
    /// rather than relying on a first-child positional convention.
    case group(label: String, headingLevel: UInt8, headingText: String)
    /// Page break marker.
    case pageBreak
    /// Presentation slide container — children are the slide's content nodes.
    case slide(number: UInt32, title: String)
    /// Definition list container — children are `DefinitionItem` nodes.
    case definitionList
    /// Individual definition list entry with term and definition.
    case definitionItem(term: String, definition: String)
    /// Citation or bibliographic reference.
    case citation(key: String, text: String)
    /// Admonition / callout container (note, warning, tip, etc.).
    ///
    /// Children carry the admonition body content.
    case admonition(kind: String, title: String)
    /// Raw block preserved verbatim from the source format.
    ///
    /// Used for content that cannot be mapped to a semantic node type
    /// (e.g. JSX in MDX, raw LaTeX in markdown, embedded HTML).
    case rawBlock(format: String, content: String)
    /// Structured metadata block (email headers, YAML frontmatter, etc.).
    case metadataBlock(entries: [String])
}

/// Types of inline text annotations.
public enum AnnotationKind {
    case bold
    case italic
    case underline
    case strikethrough
    case code
    case subscript_
    case superscript
    case link(url: String, title: String)
    /// Highlighted text (PDF highlights, HTML `<mark>`).
    case highlight
    /// Text color (CSS-compatible value, e.g. "#ff0000", "red").
    case color(value: String)
    /// Font size with units (e.g. "12pt", "1.2em", "16px").
    case fontSize(value: String)
    /// Extensible annotation for format-specific styling.
    case custom(name: String, value: String)
}

/// How the extracted text was produced.
public enum ExtractionMethod {
    case native
    case ocr
    case mixed
}

/// Semantic structural classification of a text chunk.
///
/// Assigned by the heuristic classifier in `chunking::classifier`.
/// Defaults to `Unknown` when no rule matches.
/// Designed to be extended in future versions without breaking changes.
public enum ChunkType {
    /// Section heading or document title.
    case heading
    /// Party list: names, addresses, and signatories.
    case partyList
    /// Definition clause ("X means…", "X shall mean…").
    case definitions
    /// Operative clause containing legal/contractual action verbs.
    case operativeClause
    /// Signature block with signatures, names, and dates.
    case signatureBlock
    /// Schedule, annex, appendix, or exhibit section.
    case schedule
    /// Table-like content with aligned columns or repeated patterns.
    case tableLike
    /// Mathematical formula or equation.
    case formula
    /// Code block or preformatted content.
    case codeBlock
    /// Embedded or referenced image content.
    case image
    /// Organizational chart or hierarchy diagram.
    case orgChart
    /// Diagram, figure, or visual illustration.
    case diagram
    /// Unclassified or mixed content.
    case unknown
}

/// Heuristic classification of what an image likely depicts.
public enum ImageKind {
    /// Photographic image (natural scene, photograph)
    case photograph
    /// Technical or schematic diagram
    case diagram
    /// Chart, graph, or plot
    case chart
    /// Freehand or technical drawing
    case drawing
    /// Text-heavy image (scanned text, document)
    case textBlock
    /// Decorative element or border
    case decoration
    /// Logo or brand mark
    case logo
    /// Small icon
    case icon
    /// Fragment of a larger tiled image (tile of a technical drawing)
    case tileFragment
    /// Mask or transparency map
    case mask
    /// Could not classify with reasonable confidence
    case unknown
}

/// Result-shape selection for extraction results.
///
/// Distinct from `OutputFormat` (which controls rendering — Plain, Markdown,
/// HTML, etc.). `ResultFormat` controls the *shape* of the result: a unified content
/// blob vs. an element-based decomposition.
public enum ResultFormat {
    /// Unified format with all content in `content` field
    case unified
    /// Element-based format with semantic element extraction
    case elementBased
}

/// Semantic element type classification.
///
/// Categorizes text content into semantic units for downstream processing.
/// Supports the element types commonly found in Unstructured documents.
public enum ElementType {
    /// Document title
    case title
    /// Main narrative text body
    case narrativeText
    /// Section heading
    case heading
    /// List item (bullet, numbered, etc.)
    case listItem
    /// Table element
    case table
    /// Image element
    case image
    /// Page break marker
    case pageBreak
    /// Code block
    case codeBlock
    /// Block quote
    case blockQuote
    /// Footer text
    case footer
    /// Header text
    case header
}

/// Format-specific metadata (discriminated union).
///
/// Only one format type can exist per extraction result. This provides
/// type-safe, clean metadata without nested optionals.
public enum FormatMetadata {
    case pdf(field0: String)
    case docx(field0: DocxMetadata)
    case excel(field0: ExcelMetadata)
    case email(field0: EmailMetadata)
    case pptx(field0: PptxMetadata)
    case archive(field0: ArchiveMetadata)
    case image(field0: String)
    case xml(field0: XmlMetadata)
    case text(field0: TextMetadata)
    case html(field0: HtmlMetadata)
    case ocr(field0: OcrMetadata)
    case csv(field0: CsvMetadata)
    case bibtex(field0: BibtexMetadata)
    case citation(field0: CitationMetadata)
    case fictionBook(field0: FictionBookMetadata)
    case dbf(field0: DbfMetadata)
    case jats(field0: JatsMetadata)
    case epub(field0: EpubMetadata)
    case pst(field0: PstMetadata)
    case code(field0: String)
}

/// Text direction enumeration for HTML documents.
public enum TextDirection {
    /// Left-to-right text direction
    case leftToRight
    /// Right-to-left text direction
    case rightToLeft
    /// Automatic text direction detection
    case auto
}

/// Link type classification.
public enum LinkType {
    /// Anchor link (#section)
    case anchor
    /// Internal link (same domain)
    case internal_
    /// External link (different domain)
    case external
    /// Email link (mailto:)
    case email
    /// Phone link (tel:)
    case phone
    /// Other link type
    case other
}

/// Image type classification.
public enum ImageType {
    /// Data URI image
    case dataUri
    /// Inline SVG
    case inlineSvg
    /// External image URL
    case external
    /// Relative path image
    case relative
}

/// Structured data type classification.
public enum StructuredDataType {
    /// JSON-LD structured data
    case jsonLd
    /// Microdata
    case microdata
    /// RDFa
    case rdFa
}

/// Bounding geometry for an OCR element.
///
/// Supports both axis-aligned rectangles (from Tesseract) and 4-point quadrilaterals
/// (from PaddleOCR and rotated text detection).
public enum OcrBoundingGeometry {
    /// Axis-aligned bounding box (typical for Tesseract output).
    case rectangle(left: UInt32, top: UInt32, width: UInt32, height: UInt32)
    /// 4-point quadrilateral for rotated/skewed text (PaddleOCR).
    ///
    /// Points are in clockwise order starting from top-left:
    /// `[top_left, top_right, bottom_right, bottom_left]`
    case quadrilateral(points: String)
}

/// Hierarchical level of an OCR element.
///
/// Maps to Tesseract's page segmentation hierarchy and provides
/// equivalent semantics for PaddleOCR.
public enum OcrElementLevel {
    /// Individual word
    case word
    /// Line of text (default for PaddleOCR)
    case line
    /// Paragraph or text block
    case block
    /// Page-level element
    case page
}

/// Type of paginated unit in a document.
///
/// Distinguishes between different types of "pages" (PDF pages, presentation slides, spreadsheet sheets).
public enum PageUnitType {
    /// Standard document pages (PDF, DOCX, images)
    case page
    /// Presentation slides (PPTX, ODP)
    case slide
    /// Spreadsheet sheets (XLSX, ODS)
    case sheet
}

/// Semantic classification of an extracted URI.
public enum UriKind {
    /// A clickable hyperlink (web URL, file link).
    case hyperlink
    /// An image or media resource reference.
    case image
    /// An internal anchor or cross-reference target.
    case anchor
    /// A citation or bibliographic reference (DOI, academic ref).
    case citation
    /// A general reference (e.g. `\ref{}` in LaTeX, `:ref:` in RST).
    case reference
    /// An email address (`mailto:` link or bare email).
    case email
}

/// Error type for pool operations.
public enum PoolError {
    /// The pool's internal mutex was poisoned.
    ///
    /// This indicates a panic occurred while holding the lock.
    /// The pool is in a locked state and cannot be recovered.
    case lockPoisoned
}

/// Keyword algorithm selection.
public enum KeywordAlgorithm {
    /// YAKE (Yet Another Keyword Extractor) - statistical approach
    case yake
    /// RAKE (Rapid Automatic Keyword Extraction) - co-occurrence based
    case rake
}

/// Page Segmentation Mode for Tesseract OCR
public enum PSMMode {
    case osdOnly
    case autoOsd
    case autoOnly
    case auto
    case singleColumn
    case singleBlockVertical
    case singleBlock
    case singleLine
    case singleWord
    case circleWord
    case singleChar
}

/// Supported languages in PaddleOCR.
///
/// Maps user-friendly language codes to paddle-ocr-rs language identifiers.
public enum PaddleLanguage {
    /// English
    case english
    /// Simplified Chinese
    case chinese
    /// Japanese
    case japanese
    /// Korean
    case korean
    /// German
    case german
    /// French
    case french
    /// Latin script (covers most European languages)
    case latin
    /// Cyrillic (Russian and related)
    case cyrillic
    /// Traditional Chinese
    case traditionalChinese
    /// Thai
    case thai
    /// Greek
    case greek
    /// East Slavic (Russian, Ukrainian, Belarusian)
    case eastSlavic
    /// Arabic (Arabic, Persian, Urdu)
    case arabic
    /// Devanagari (Hindi, Marathi, Sanskrit, Nepali)
    case devanagari
    /// Tamil
    case tamil
    /// Telugu
    case telugu
}

/// The 17 canonical document layout classes.
///
/// All model backends (RT-DETR, YOLO, etc.) map their native class IDs
/// to this shared set. Models with fewer classes (DocLayNet: 11, PubLayNet: 5)
/// map to the closest equivalent.
public enum LayoutClass {
    case caption
    case footnote
    case formula
    case listItem
    case pageFooter
    case pageHeader
    case picture
    case sectionHeader
    case table
    case text
    case title
    case documentIndex
    case code
    case checkboxSelected
    case checkboxUnselected
    case form
    case keyValueRegion
}

/// Main error type for all Kreuzberg operations.
///
/// All errors in Kreuzberg use this enum, which preserves error chains
/// and provides context for debugging.
///
/// # Variants
///
/// - `Io` - File system and I/O errors (always bubble up)
/// - `Parsing` - Document parsing errors (corrupt files, unsupported features)
/// - `Ocr` - OCR processing errors
/// - `Validation` - Input validation errors (invalid paths, config, parameters)
/// - `Cache` - Cache operation errors (non-fatal, can be ignored)
/// - `ImageProcessing` - Image manipulation errors
/// - `Serialization` - JSON/MessagePack serialization errors
/// - `MissingDependency` - Missing optional dependencies (tesseract, etc.)
/// - `Plugin` - Plugin-specific errors
/// - `LockPoisoned` - Mutex/RwLock poisoning (should not happen in normal operation)
/// - `UnsupportedFormat` - Unsupported MIME type or file format
/// - `Other` - Catch-all for uncommon errors
public enum KreuzbergError: Error {
    case io(message: String, field0: String)
    case parsing(message: String, source: String)
    case ocr(message: String, source: String)
    case validation(message: String, source: String)
    case cache(message: String, source: String)
    case imageProcessing(message: String, source: String)
    case serialization(message: String, source: String)
    case missingDependency(message: String, field0: String)
    case plugin(message: String, pluginName: String)
    case lockPoisoned(message: String, field0: String)
    case unsupportedFormat(message: String, field0: String)
    case embedding(message: String, source: String)
    case timeout(message: String, elapsedMs: UInt64, limitMs: UInt64)
    case cancelled(message: String)
    case security(message: String, source: String)
    case other(message: String, field0: String)
}
