// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6720aede1769ac57af8516ada5db3f89dc2e2e3c5fb2d2d7a09a892fda40a2c2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: extraction

use kreuzberg::extract_file;

#[tokio::test]
async fn test_extract_doc_basic() {
    // Extract text from a DOC file containing unit test lists
    let path = Default::default();
    let mime_type: Option<String> = None;
    let config = Default::default();
    let result = extract_file(path, mime_type.as_deref(), &config)
        .await
        .expect("should succeed");
    assert!(
        result.content.len() >= 10,
        "expected length >= 10, got {}",
        result.content.len()
    );
}

#[tokio::test]
async fn test_extract_email_basic() {
    // Extract content from an email file in EML format
    let path = Default::default();
    let mime_type: Option<String> = None;
    let config = Default::default();
    let _ = extract_file(path, mime_type.as_deref(), &config).await;
}

#[tokio::test]
async fn test_extract_pdf_basic() {
    // Extract text from a basic PDF document containing memo content
    let path = Default::default();
    let mime_type: Option<String> = None;
    let config = Default::default();
    let result = extract_file(path, mime_type.as_deref(), &config)
        .await
        .expect("should succeed");
    assert!(
        result.content.len() >= 50,
        "expected length >= 50, got {}",
        result.content.len()
    );
}

#[tokio::test]
async fn test_extract_pdf_code() {
    // Extract text from PDF containing code snippets and formulas
    let path = Default::default();
    let mime_type: Option<String> = None;
    let config = Default::default();
    let result = extract_file(path, mime_type.as_deref(), &config)
        .await
        .expect("should succeed");
    assert!(
        result.content.len() >= 20,
        "expected length >= 20, got {}",
        result.content.len()
    );
}

#[tokio::test]
async fn test_extract_pptx_basic() {
    // Extract text from a PowerPoint presentation file
    let path = Default::default();
    let mime_type: Option<String> = None;
    let config = Default::default();
    let _ = extract_file(path, mime_type.as_deref(), &config).await;
}
