// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9ee8c920a8314fc0024b76c491d24d07bc0d6fe7dd31a14bb2c14afee54b3de4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
//! E2e tests for category: uri

use kreuzberg::extract_file;

#[tokio::test]
async fn test_classify_uri_anchor() {
    // Classify fragment URI
    let path = Default::default();
    let mime_type: Option<String> = None;
    let config = Default::default();
    let _ = extract_file(path, mime_type.as_deref(), &config).await;
}

#[tokio::test]
async fn test_classify_uri_email() {
    // Classify mailto URI
    let path = Default::default();
    let mime_type: Option<String> = None;
    let config = Default::default();
    let _ = extract_file(path, mime_type.as_deref(), &config).await;
}

#[tokio::test]
async fn test_classify_uri_https() {
    // Classify HTTPS URL
    let path = Default::default();
    let mime_type: Option<String> = None;
    let config = Default::default();
    let _ = extract_file(path, mime_type.as_deref(), &config).await;
}
