<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2712b8b446c972a698fe582974d6b7c0db607be6c5adf72cda76dc1de81ff189
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: async. */
final class AsyncTest extends TestCase
{

    /** extract_bytes empty MIME async */
    public function test_async_extract_bytes_empty_mime(): void
    {        $this->expectException(\Exception::class);        $contentBytes = file_get_contents("text/plain.txt");
        if ($contentBytes === false) { $this->fail("failed to read fixture: text/plain.txt"); }
        $config = ExtractionConfig::from_json('{}');
        Kreuzberg::extractBytesAsync($contentBytes, "", $config);    }


    /** extract_bytes unsupported MIME async */
    public function test_async_extract_bytes_invalid_mime(): void
    {        $this->expectException(\Exception::class);        $contentBytes = file_get_contents("text/plain.txt");
        if ($contentBytes === false) { $this->fail("failed to read fixture: text/plain.txt"); }
        $config = ExtractionConfig::from_json('{}');
        Kreuzberg::extractBytesAsync($contentBytes, "application/x-nonexistent", $config);    }

}
