<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:165086eb83bab831025d006fe91de9f5f4c84b109a475e1722aee82fd7d66fda
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\ExtractionConfig;

/** E2e tests for category: detection. */
final class DetectionTest extends TestCase
{
    /** Detect HTML MIME from bytes */
    public function test_detect_mime_bytes_html(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::detectMimeTypeFromBytes(file_get_contents("html/html.html"));
    }

    /** Detect PDF MIME type from bytes */
    public function test_detect_mime_bytes_pdf(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::detectMimeTypeFromBytes(file_get_contents("pdf/fake_memo.pdf"));
    }

    /** Detect PNG MIME type from bytes */
    public function test_detect_mime_bytes_png(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::detectMimeTypeFromBytes(file_get_contents("images/test_hello_world.png"));
    }

    /** get_extensions unknown MIME */
    public function test_get_extensions_unknown_mime(): void
    {
        $this->expectException(\Exception::class);
        Kreuzberg::getExtensionsForMime("application/x-totally-unknown");
    }
}
