<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2c84244dc6262308e03dffcb031b842c2277c8cd346c8755e0f675935f4ee259
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;use Kreuzberg\ExtractionConfig;
/** E2e tests for category: registry_operations. */
final class RegistryOperationsTest extends TestCase
{

    /** Get file extensions for DOCX MIME type */
    public function test_extensions_docx(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::getExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document");

    }


    /** Get file extensions for HTML MIME type */
    public function test_extensions_html(): void
    {        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::getExtensionsForMime("text/html");

    }


    /** Get file extensions for PDF MIME type */
    public function test_extensions_pdf(): void
    {        $result = Kreuzberg::getExtensionsForMime("application/pdf");
            $found = false;
    foreach ($result as $item) {
        if (str_contains((string)$item, "pdf")) { $found = true; }
    }
    $this->assertTrue($found, 'expected array to contain string');

    }

}
