<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:45b53a57757197ed1d58a0da1e49574263bd94d0b012e7bfeaafce082907bd5c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: text_utils. */
final class TextUtilsTest extends TestCase
{
    /** Remove null characters from text */
    public function test_clean_text_basic(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile_async(null);
        $this->assertStringContainsString("Hello", $result->result);
    }

    /** Normalize whitespace in extracted text */
    public function test_clean_text_whitespace(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile_async(null);
        $this->assertGreaterThanOrEqual(1, strlen($result->result));
    }

    /** Deduplicate repeated lines */
    public function test_dedup_basic(): void
    {
        $result = Kreuzberg\Kreuzberg::(["texts" => ["line1", "line1", "line2", "line2", "line3"]]);
        $this->assertStringContainsString("line1", $result->result);
    }

    /** Deduplicate text with all unique lines */
    public function test_dedup_unique(): void
    {
        $result = Kreuzberg\Kreuzberg::(["texts" => ["a", "b", "c"]]);
        $this->assertStringContainsString("a", $result->result);
    }

    /** Escape ampersands in HTML text */
    public function test_escape_html_ampersand(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile_async(null);
        $this->assertStringContainsString("&amp;", $result->result);
    }

    /** Escape HTML special characters including angle brackets */
    public function test_escape_html_basic(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile_async(null);
        $this->assertStringContainsString("&lt;", $result->result);
    }

    /** Fix mojibake encoding issues */
    public function test_fix_mojibake_basic(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile_async(null);
        $this->assertGreaterThanOrEqual(1, strlen($result->result));
    }

    /** Clean text passes through */
    public function test_fix_mojibake_clean(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile_async(null);
        $this->assertStringContainsString("Normal ASCII text", $result->result);
    }

    /** Fix mojibake encoding */
    public function test_fix_mojibake_utf8(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::extractFile_async(null);
    }

    /** Validate ASCII text as valid UTF-8 */
    public function test_is_utf8_ascii(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile_async(null);
        $this->assertTrue($result->result);
    }

    /** Validate UTF-8 encoding */
    public function test_is_utf8_valid(): void
    {
        $result = Kreuzberg\Kreuzberg::extractFile_async(null);
        $this->assertEquals(true, $result->result);
    }

    /** Normalize multiple spaces and newlines */
    public function test_normalize_whitespace_basic(): void
    {
        $result = Kreuzberg\Kreuzberg::(["text" => "hello   world\n\n\nfoo"]);
        $this->assertStringContainsString("hello", $result->result);
    }

    /** Normalize tabs to spaces */
    public function test_normalize_whitespace_tabs(): void
    {
        $result = Kreuzberg\Kreuzberg::(["text" => "col1\t\tcol2\t\tcol3"]);
        $this->assertStringContainsString("col1", $result->result);
    }
}
