<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:029fe116a5594c100ff3a0502ecbf87cd2f15999a5e3df9713ffdd25e8ea4f25
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg\Kreuzberg;

/** E2e tests for category: uri. */
final class UriTest extends TestCase
{
    /** Classify fragment URI */
    public function test_classify_uri_anchor(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::extractFile_async(null);
    }

    /** Classify mailto URI */
    public function test_classify_uri_email(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::extractFile_async(null);
    }

    /** Classify HTTPS URL */
    public function test_classify_uri_https(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg\Kreuzberg::extractFile_async(null);
    }
}
