// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d52805902c3b0f50a074dfe3152cfba9c16bae3837bc98ee00caedadc4a0deb7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Properties for anchored drawings.
/// </summary>
public sealed class AnchorProperties
{
    [JsonPropertyName("behind_doc")]
    public bool BehindDoc { get; set; } = false;

    [JsonPropertyName("layout_in_cell")]
    public bool LayoutInCell { get; set; } = false;

    [JsonPropertyName("relative_height")]
    public long? RelativeHeight { get; set; } = null;

    [JsonPropertyName("position_h")]
    public string? PositionH { get; set; } = null;

    [JsonPropertyName("position_v")]
    public string? PositionV { get; set; } = null;

    [JsonPropertyName("wrap_type")]
    public string WrapType { get; set; } = "";

}
