// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c42e0a8bd1e3905a6b45cb4034864cd716b2b2422ac350091714c8b304f6e1a1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Properties for anchored drawings.
/// </summary>
public sealed class AnchorProperties
{
    [JsonPropertyName("behind_doc")]
    public bool BehindDoc { get; set; } = false;

    [JsonPropertyName("layout_in_cell")]
    public bool LayoutInCell { get; set; } = false;

    [JsonPropertyName("relative_height")]
    public long? RelativeHeight { get; set; } = null;

    [JsonPropertyName("position_h")]
    public string? PositionH { get; set; } = null;

    [JsonPropertyName("position_v")]
    public string? PositionV { get; set; } = null;

    [JsonPropertyName("wrap_type")]
    public string WrapType { get; set; } = "";


    /// <summary>
    /// Parse a <see cref="AnchorProperties"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static AnchorProperties FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<AnchorProperties>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse AnchorProperties from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse AnchorProperties from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
