// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9d87f82e2394de5e84414fa4c9694c97d06b2f90c264914ebebd94ab0d672cee
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;
namespace Kreuzberg;

internal sealed class ApiDocSafeHandle : SafeHandle
{
    internal ApiDocSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.ApiDocFree(handle);
        return true;
    }
}
/// <summary>/// OpenAPI documentation structure./// /// Defines all endpoints, request/response schemas, and examples/// for the Kreuzberg document extraction API./// </summary>
public sealed class ApiDoc : IDisposable
{
    private readonly ApiDocSafeHandle _safeHandle;

    internal ApiDoc(IntPtr handle)
    {
        _safeHandle = new ApiDocSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();

}
