// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a017169d7035952c339a379d8e55f7c2fbc64c8bc280bd09c0f6ddeeb1aa87fe
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// BibTeX bibliography metadata.
/// </summary>
public sealed class BibtexMetadata
{
    /// <summary>
    /// Number of entries in the bibliography.
    /// </summary>
    [JsonPropertyName("entry_count")]
    public ulong EntryCount { get; set; } = 0;

    [JsonPropertyName("citation_keys")]
    public List<string> CitationKeys { get; set; } = [];

    [JsonPropertyName("authors")]
    public List<string> Authors { get; set; } = [];

    [JsonPropertyName("year_range")]
    public YearRange? YearRange { get; set; } = null;

    [JsonPropertyName("entry_types")]
    public Dictionary<string, ulong>? EntryTypes { get; set; } = null;

}
