// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c59a4b7fdb6b3d5a2c404e9a8fd9a9bf8bb02e24df5672b3ac47071fd2dd216a
#nullable enable

using System;

namespace Kreuzberg;

public class CacheException : KreuzbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
