// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e6b59bb84e01befe39187c5ae0a67ccd84c0ca37994f090157cb6ee86d152d2d
#nullable enable

using System;

namespace Kreuzberg;

public class CacheException : KreuzbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
