// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ede8defa17416eb2a8ee3294b343437a860087f8f61876baec2456692ccbdbd2
#nullable enable

using System;

namespace Kreuzberg;

public class CancelledException : KreuzbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
