// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1b2ed174000aa95b264ff5617e013c32497c6d6d5771e7be40f42b60cffb5ad7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class CharShape
{
    [JsonPropertyName("bold")]
    public bool Bold { get; set; } = false;

    [JsonPropertyName("italic")]
    public bool Italic { get; set; } = false;

    [JsonPropertyName("underline")]
    public bool Underline { get; set; } = false;


    /// <summary>
    /// Parse a <see cref="CharShape"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static CharShape FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<CharShape>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse CharShape from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse CharShape from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
