// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:69e33ec9a9cb2b3cf5e4ab5cb212c4ee7fc089c9e44e47663f65c1a8c5082111
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class CharShape
{
    [JsonPropertyName("bold")]
    public bool Bold { get; set; } = false;

    [JsonPropertyName("italic")]
    public bool Italic { get; set; } = false;

    [JsonPropertyName("underline")]
    public bool Underline { get; set; } = false;

}
