// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a4c6d2c722d07ba1e59e5330fcd47ab5238f8a3cd33ec95db0aaeb4fa225cdcf
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Content layer classification for document nodes./// /// Replaces separate body/furniture arrays with per-node granularity./// </summary>
public enum ContentLayer
{/// <summary>    /// Main document body content.    /// </summary>
    [JsonPropertyName("body")]
    Body,/// <summary>    /// Page/section header (running header).    /// </summary>
    [JsonPropertyName("header")]
    Header,/// <summary>    /// Page/section footer (running footer).    /// </summary>
    [JsonPropertyName("footer")]
    Footer,/// <summary>    /// Footnote content.    /// </summary>
    [JsonPropertyName("footnote")]
    Footnote,
}
