// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1e05b2ce1c1c79bf6f1c7ee8fa2ad4cee80c3686e682e37281a553ac9d2ac811
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// JATS contributor with role.
/// </summary>
public sealed class ContributorRole
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("role")]
    public string? Role { get; set; } = null;

}
