// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f5bac7b91298de5440afa495950d06b63520ff85b8371a8e227d7ce41c9819b9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// CSV/TSV file metadata.
/// </summary>
public sealed class CsvMetadata
{
    [JsonPropertyName("row_count")]
    public ulong RowCount { get; set; } = 0;

    [JsonPropertyName("column_count")]
    public ulong ColumnCount { get; set; } = 0;

    [JsonPropertyName("delimiter")]
    public string? Delimiter { get; set; } = null;

    [JsonPropertyName("has_header")]
    public bool HasHeader { get; set; } = false;

    [JsonPropertyName("column_types")]
    public List<string>? ColumnTypes { get; set; } = null;


    /// <summary>
    /// Parse a <see cref="CsvMetadata"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static CsvMetadata FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<CsvMetadata>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse CsvMetadata from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse CsvMetadata from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
