// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:df438175b46d78be29219fc23d10b191441ae8e12383806cd8982a1ccf44b778
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// dBASE field information.
/// </summary>
public sealed class DbfFieldInfo
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("field_type")]
    public string FieldType { get; set; } = "";

}
