// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d83ff5d8e2bd120251f6a3df90d7abc8ea19d213f8c123180fb60982f974999a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// MIME type detection response.
/// </summary>
public sealed class DetectResponse
{
    /// <summary>
    /// Detected MIME type
    /// </summary>
    [JsonPropertyName("mime_type")]
    public string MimeType { get; set; } = "";

    /// <summary>
    /// Original filename (if provided)
    /// </summary>
    [JsonPropertyName("filename")]
    public string? Filename { get; set; } = null;

}
