// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:aff059f314389f0e8f657513e373053f28e83046868e2254d74f9ed97d8fcd05
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Page-level detection result containing all detections and page metadata.
/// </summary>
public sealed class DetectionResult
{
    [JsonPropertyName("page_width")]
    public uint PageWidth { get; set; } = 0;

    [JsonPropertyName("page_height")]
    public uint PageHeight { get; set; } = 0;

    [JsonPropertyName("detections")]
    public List<LayoutDetection> Detections { get; set; } = [];


    /// <summary>
    /// Parse a <see cref="DetectionResult"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static DetectionResult FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<DetectionResult>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse DetectionResult from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse DetectionResult from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
