// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ac43a3cdaae9d29fe0b227da67b1d6cadc82f10972831362cdebf42ec146516c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Page-level detection result containing all detections and page metadata.
/// </summary>
public sealed class DetectionResult
{
    [JsonPropertyName("page_width")]
    public uint PageWidth { get; set; } = 0;

    [JsonPropertyName("page_height")]
    public uint PageHeight { get; set; } = 0;

    [JsonPropertyName("detections")]
    public List<LayoutDetection> Detections { get; set; } = [];

}
