// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1b342a15e5bf24ad513da77c860f6b701ec518a8411452d00bcf4584607757ba
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Request parameters for MIME type detection.
/// </summary>
public sealed class DetectMimeTypeParams
{
    /// <summary>
    /// Path to the file
    /// </summary>
    [JsonPropertyName("path")]
    public string Path { get; set; } = "";

    /// <summary>
    /// Use content-based detection (default: true)
    /// </summary>
    [JsonPropertyName("use_content")]
    public bool UseContent { get; set; } = false;


    /// <summary>
    /// Parse a <see cref="DetectMimeTypeParams"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static DetectMimeTypeParams FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<DetectMimeTypeParams>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse DetectMimeTypeParams from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse DetectMimeTypeParams from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
