// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a2b152570c5b502fb5d1e1eee49746107cd7dc3a8c9e963184e77d1428b240e7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A resolved relationship between two nodes in the document tree.
/// </summary>
public sealed class DocumentRelationship
{
    /// <summary>
    /// Source node index (the referencing node).
    /// </summary>
    [JsonPropertyName("source")]
    public uint Source { get; set; } = 0;

    /// <summary>
    /// Target node index (the referenced node).
    /// </summary>
    [JsonPropertyName("target")]
    public uint Target { get; set; } = 0;

    /// <summary>
    /// Semantic kind of the relationship.
    /// </summary>
    [JsonPropertyName("kind")]
    public RelationshipKind Kind { get; set; } = default!;

}
