// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3cb74af1f6223e3d30748783e26b4219b9ca1c5fdf229c3a8919e452a441527c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Word document metadata.
///
/// Extracted from DOCX files using shared Office Open XML metadata extraction.
/// Integrates with `office_metadata` module for core/app/custom properties.
/// </summary>
public sealed class DocxMetadata
{
    /// <summary>
    /// Core properties from docProps/core.xml (Dublin Core metadata)
    ///
    /// Contains title, creator, subject, keywords, dates, etc.
    /// Shared format across DOCX/PPTX/XLSX documents.
    /// </summary>
    [JsonPropertyName("core_properties")]
    public CoreProperties? CoreProperties { get; set; } = null;

    /// <summary>
    /// Application properties from docProps/app.xml (Word-specific statistics)
    ///
    /// Contains word count, page count, paragraph count, editing time, etc.
    /// DOCX-specific variant of Office application properties.
    /// </summary>
    [JsonPropertyName("app_properties")]
    public DocxAppProperties? AppProperties { get; set; } = null;

    /// <summary>
    /// Custom properties from docProps/custom.xml (user-defined properties)
    ///
    /// Contains key-value pairs defined by users or applications.
    /// Values can be strings, numbers, booleans, or dates.
    /// </summary>
    [JsonPropertyName("custom_properties")]
    public Dictionary<string, object>? CustomProperties { get; set; } = null;

}
