// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b749b83c63955db02e34250dabaffc8e870e6d77079dfc7c4144ef3960ba3e58
#nullable enable

using System;

namespace Kreuzberg;

public class EmbeddingException : KreuzbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
