// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:95ae85fcf5bdb13ce5c9b9ce7cf1c0b55b6f43395feca5effa6cb5cdc80fc426
#nullable enable

using System;

namespace Kreuzberg;

public class EmbeddingException : KreuzbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
