// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:be2e5930d2e862ecc820e10fdd9aa5770b5dc481dbde223689d2f328069ea0d5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// EPUB metadata (Dublin Core extensions).
/// </summary>
public sealed class EpubMetadata
{
    [JsonPropertyName("coverage")]
    public string? Coverage { get; set; } = null;

    [JsonPropertyName("dc_format")]
    public string? DcFormat { get; set; } = null;

    [JsonPropertyName("relation")]
    public string? Relation { get; set; } = null;

    [JsonPropertyName("source")]
    public string? Source { get; set; } = null;

    [JsonPropertyName("dc_type")]
    public string? DcType { get; set; } = null;

    [JsonPropertyName("cover_image")]
    public string? CoverImage { get; set; } = null;

}
