// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:938ebf65ad2f8c3982d133f2c3ec360180157becb5cf555c5aa021daedc48e27
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Error metadata (for batch operations).
/// </summary>
public sealed class ErrorMetadata
{
    [JsonPropertyName("error_type")]
    public string ErrorType { get; set; } = "";

    [JsonPropertyName("message")]
    public string Message { get; set; } = "";

}
