// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2e4b5fe8e85684cf25cf988377a6daa5f24624d79784eed01f65c739578d9b98
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Excel/spreadsheet metadata marker.
///
/// Sheet count and sheet names are now exposed directly on [`Metadata`] as
/// `sheet_count: Option<usize>` and `sheet_names: Option<Vec<String>>` so that
/// every binding (Rust, Python, Node, …) sees them at the same path. This
/// struct remains as a `FormatMetadata` variant tag for spreadsheet sources.
/// </summary>
public sealed class ExcelMetadata
{
}
