// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:245c2d2f8e40bf94696284f5de87ac5decec821a3a3d5d8abdaa937d6402b1ab
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// How the extracted text was produced.
/// </summary>
public enum ExtractionMethod
{
    [JsonPropertyName("native")]
    Native,
    [JsonPropertyName("ocr")]
    Ocr,
    [JsonPropertyName("mixed")]
    Mixed,
}
