// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:147e7e3d14664bdb658a12a002f553a43dbd329fa01cd8dae2615ea2a936059b
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// How the extracted text was produced./// </summary>
public enum ExtractionMethod
{[JsonPropertyName("native")]
    Native,[JsonPropertyName("ocr")]
    Ocr,[JsonPropertyName("mixed")]
    Mixed,}
