// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:441bbb151e7002b76ca93e6968d0d059f21add8785b913d46fee7fdce358102a
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// How the extracted text was produced./// </summary>
public enum ExtractionMethod
{
    [JsonPropertyName("native")]
    Native, [JsonPropertyName("ocr")]
    Ocr, [JsonPropertyName("mixed")]
    Mixed,
}
