// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:283f52933a1bd86dddaa0c04d944632b5bbc77c686a760e728084e6199373192
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;
namespace Kreuzberg;

internal sealed class ExtractResponseSafeHandle : SafeHandle
{
    internal ExtractResponseSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.ExtractResponseFree(handle);
        return true;
    }
}
/// <summary>/// Extraction response (list of results)./// </summary>
public sealed class ExtractResponse : IDisposable
{
    private readonly ExtractResponseSafeHandle _safeHandle;

    internal ExtractResponse(IntPtr handle)
    {
        _safeHandle = new ExtractResponseSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();

}
