// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:395a53451b237b403b260db8aa484ff8030578ff2c9253df3cf0d8f3268a858d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public enum FracType
{[JsonPropertyName("bar")]
    Bar,[JsonPropertyName("nobar")]
    NoBar,[JsonPropertyName("linear")]
    Linear,[JsonPropertyName("skewed")]
    Skewed,}
