// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:55f252972571e49b3859c09cf74b3c1d831e4501a16173540ca7a4a94b4f19c2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Heading context for a chunk within a Markdown document.
///
/// Contains the heading hierarchy from document root to this chunk's section.
/// </summary>
public sealed class HeadingContext
{
    /// <summary>
    /// The heading hierarchy from document root to this chunk's section.
    /// Index 0 is the outermost (h1), last element is the most specific.
    /// </summary>
    [JsonPropertyName("headings")]
    public List<HeadingLevel> Headings { get; set; } = [];

}
