// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:655462c7cf8ba926d2183dbcd1f45aa20da5271d59d49f0df660868df624d2a7
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Built-in HTML theme selection./// </summary>
public enum HtmlTheme
{/// <summary>    /// Sensible defaults: system font stack, neutral colours, readable line    /// measure. CSS custom properties (`--kb-*`) are all defined so user CSS    /// can override individual values.    /// </summary>
    [JsonPropertyName("default")]
    Default,/// <summary>    /// GitHub Markdown-inspired palette and spacing.    /// </summary>
    [JsonPropertyName("github")]
    GitHub,/// <summary>    /// Dark background, light text.    /// </summary>
    [JsonPropertyName("dark")]
    Dark,/// <summary>    /// Minimal light theme with generous whitespace.    /// </summary>
    [JsonPropertyName("light")]
    Light,/// <summary>    /// No built-in stylesheet emitted. CSS custom properties are still defined    /// on `:root` so user stylesheets can reference `var(--kb-*)` tokens.    /// </summary>
    [JsonPropertyName("unstyled")]
    Unstyled,
}
