// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ee5e3156ae681b40d217b52d88e97bd9d4641e62daa1d3d98669c0ac6842d5a4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class HwpImage
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("data")]
    public byte[] Data { get; set; } = Array.Empty<byte>();

}
