// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:07bc20fa6c39a3627c0ee2f156870824c17b2369ed64cf117327954f9c4b53a5
#nullable enable

using System;

namespace Kreuzberg;

public class ImageProcessingException : KreuzbergErrorException
{
    public ImageProcessingException(string message) : base(message) { }

    public ImageProcessingException(string message, Exception innerException) : base(message, innerException) { }
}
