// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c98537f471af0025d4a23d7ce8831912f2ad167760495b3dde680a10c94793b2
#nullable enable

using System;

namespace Kreuzberg;

public class ImageProcessingException : KreuzbergErrorException
{
    public ImageProcessingException(string message) : base(message) { }

    public ImageProcessingException(string message, Exception innerException) : base(message, innerException) { }
}
