// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b0d88f65b71665ad9106312bcb519e8742802c02ba16f712c8bb011660a025e8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Result of OCR extraction from an image with optional page tracking.
/// </summary>
public sealed class ImageOcrResult
{
    /// <summary>
    /// Extracted text content
    /// </summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = "";

    /// <summary>
    /// Character byte boundaries per frame (for multi-frame TIFFs)
    /// </summary>
    [JsonPropertyName("boundaries")]
    public List<PageBoundary>? Boundaries { get; set; } = null;

    /// <summary>
    /// Per-frame content information
    /// </summary>
    [JsonPropertyName("page_contents")]
    public List<PageContent>? PageContents { get; set; } = null;


    /// <summary>
    /// Parse a <see cref="ImageOcrResult"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static ImageOcrResult FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ImageOcrResult>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse ImageOcrResult from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse ImageOcrResult from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
