// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d9e6f803bcdac058b01b25359056630b5a1b94a03d15d8aacc4d7ca501d2e8e3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Types of inline elements in Djot.
/// </summary>
public enum InlineType
{
    [JsonPropertyName("text")]
    Text,
    [JsonPropertyName("strong")]
    Strong,
    [JsonPropertyName("emphasis")]
    Emphasis,
    [JsonPropertyName("highlight")]
    Highlight,
    [JsonPropertyName("subscript")]
    Subscript,
    [JsonPropertyName("superscript")]
    Superscript,
    [JsonPropertyName("insert")]
    Insert,
    [JsonPropertyName("delete")]
    Delete,
    [JsonPropertyName("code")]
    Code,
    [JsonPropertyName("link")]
    Link,
    [JsonPropertyName("image")]
    Image,
    [JsonPropertyName("span")]
    Span,
    [JsonPropertyName("math")]
    Math,
    [JsonPropertyName("raw_inline")]
    RawInline,
    [JsonPropertyName("footnote_ref")]
    FootnoteRef,
    [JsonPropertyName("symbol")]
    Symbol,
}
