// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9871a9e5d76ba42fc9bad932fee7fad6daa6dc49ace608c8e8f4ea3a872fee2d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Types of inline elements in Djot./// </summary>
public enum InlineType
{
    [JsonPropertyName("text")]
    Text, [JsonPropertyName("strong")]
    Strong, [JsonPropertyName("emphasis")]
    Emphasis, [JsonPropertyName("highlight")]
    Highlight, [JsonPropertyName("subscript")]
    Subscript, [JsonPropertyName("superscript")]
    Superscript, [JsonPropertyName("insert")]
    Insert, [JsonPropertyName("delete")]
    Delete, [JsonPropertyName("code")]
    Code, [JsonPropertyName("link")]
    Link, [JsonPropertyName("image")]
    Image, [JsonPropertyName("span")]
    Span, [JsonPropertyName("math")]
    Math, [JsonPropertyName("raw_inline")]
    RawInline, [JsonPropertyName("footnote_ref")]
    FootnoteRef, [JsonPropertyName("symbol")]
    Symbol,
}
