// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:05c8f4eb9f437da8d6d4230b1a1c05dd480c75e3e226a1edf7a7891af0a0bea1
#nullable enable

using System;

namespace Kreuzberg;

public class IoException : KreuzbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
