// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:05d55f40e9c4e49dbe574320b9573794036e64a12b3a6ca02098c17c4b3fdd4f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// JATS (Journal Article Tag Suite) metadata.
/// </summary>
public sealed class JatsMetadata
{
    [JsonPropertyName("copyright")]
    public string? Copyright { get; set; } = null;

    [JsonPropertyName("license")]
    public string? License { get; set; } = null;

    [JsonPropertyName("history_dates")]
    public Dictionary<string, string> HistoryDates { get; set; } = new Dictionary<string, string>();

    [JsonPropertyName("contributor_roles")]
    public List<ContributorRole> ContributorRoles { get; set; } = [];


    /// <summary>
    /// Parse a <see cref="JatsMetadata"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static JatsMetadata FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<JatsMetadata>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse JatsMetadata from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse JatsMetadata from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
