// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e838d67de1f01d6c764b1d825c817d778b58f7b45f28d84d18cd296122b334c9
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Keyword algorithm selection./// </summary>
public enum KeywordAlgorithm
{/// <summary>    /// YAKE (Yet Another Keyword Extractor) - statistical approach    /// </summary>
    [JsonPropertyName("yake")]
    Yake,/// <summary>    /// RAKE (Rapid Automatic Keyword Extraction) - co-occurrence based    /// </summary>
    [JsonPropertyName("rake")]
    Rake,
}
