// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b2a541fb7efba2c2a743e35947c8f8d90665e8a440b6ab65f3188598bfa3e21d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

#nullable enable

using System;

namespace Kreuzberg;

public class KreuzbergException : Exception
{
    public int Code { get; }

    public KreuzbergException(int code, string message) : base(message)
    {
        Code = code;
    }

    public KreuzbergException(string message) : base(message)
    {
        Code = 0;
    }

    public KreuzbergException(string message, Exception innerException) : base(message, innerException)
    {
        Code = 0;
    }
}
