// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:70092dcb0cee0487dadd227fbbba408473409f89b266e873d5ba3ee4bc768c11
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;

namespace Kreuzberg;

public class KreuzbergException : Exception
{
    public int Code { get; }

    public KreuzbergException(int code, string message) : base(message)
    {
        Code = code;
    }
}
