// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f7f125eee201ab4c9beabfed45a621ae40198ac175b21e6787578ac714afefaf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A single layout detection result.
/// </summary>
public sealed class LayoutDetection
{
    [JsonPropertyName("class_name")]
    public LayoutClass ClassName { get; set; } = default!;

    [JsonPropertyName("confidence")]
    public float Confidence { get; set; } = 0.0f;

    [JsonPropertyName("bbox")]
    public BBox Bbox { get; set; } = default!;

}
