// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3ed63ee5446905708d3af8a9745ad89b76ea7fade9ef20bcf4ca09cbf1e75431
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// The 17 canonical document layout classes./// /// All model backends (RT-DETR, YOLO, etc.) map their native class IDs/// to this shared set. Models with fewer classes (DocLayNet: 11, PubLayNet: 5)/// map to the closest equivalent./// </summary>
public enum LayoutClass
{[JsonPropertyName("caption")]
    Caption,[JsonPropertyName("footnote")]
    Footnote,[JsonPropertyName("formula")]
    Formula,[JsonPropertyName("listitem")]
    ListItem,[JsonPropertyName("pagefooter")]
    PageFooter,[JsonPropertyName("pageheader")]
    PageHeader,[JsonPropertyName("picture")]
    Picture,[JsonPropertyName("sectionheader")]
    SectionHeader,[JsonPropertyName("table")]
    Table,[JsonPropertyName("text")]
    Text,[JsonPropertyName("title")]
    Title,[JsonPropertyName("documentindex")]
    DocumentIndex,[JsonPropertyName("code")]
    Code,[JsonPropertyName("checkboxselected")]
    CheckboxSelected,[JsonPropertyName("checkboxunselected")]
    CheckboxUnselected,[JsonPropertyName("form")]
    Form,[JsonPropertyName("keyvalueregion")]
    KeyValueRegion,}
