// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6ff16ca1ae5648c397ff1ceca4fb1ea16034b056694cbdb37621c2a744dee16e
#nullable enable

using System;

namespace Kreuzberg;

public class LockPoisonedException : KreuzbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
