// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3feff16480d21e664be62965bc441ea79229cb959ebad0f6b10019d403bda1a6
#nullable enable

using System;

namespace Kreuzberg;

public class LockPoisonedException : KreuzbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
