// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7b01fb0e032a81fc5977ac6c2b3594c0e0ff8598f1033f5f9b71c756c67953eb
#nullable enable

using System;

namespace Kreuzberg;

public class MissingDependencyException : KreuzbergErrorException
{
    public MissingDependencyException(string message) : base(message) { }

    public MissingDependencyException(string message, Exception innerException) : base(message, innerException) { }
}
