// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:72b4fef40106854b78c30538aa6e2eb2dc3955c4bc915ab2ab4253a37ffd9b04
#nullable enable

using System;

namespace Kreuzberg;

public class MissingDependencyException : KreuzbergErrorException
{
    public MissingDependencyException(string message) : base(message) { }

    public MissingDependencyException(string message, Exception innerException) : base(message, innerException) { }
}
