// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:915123939d6cba402c30b4357fb49eced43c3015690dcd98796e2b53eb34d2a1
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// OCR backend types./// </summary>
public enum OcrBackendType
{/// <summary>    /// Tesseract OCR (native Rust binding)    /// </summary>
    [JsonPropertyName("tesseract")]
    Tesseract,/// <summary>    /// EasyOCR (Python-based, via FFI)    /// </summary>
    [JsonPropertyName("easyocr")]
    EasyOcr,/// <summary>    /// PaddleOCR (Python-based, via FFI)    /// </summary>
    [JsonPropertyName("paddleocr")]
    PaddleOcr,/// <summary>    /// Custom/third-party OCR backend    /// </summary>
    [JsonPropertyName("custom")]
    Custom,
}
