// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1a558204a0be233b7981669a1dfbca24c7cd7731a422235ed8fe00055bb023f3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class OcrCacheStats
{
    [JsonPropertyName("total_files")]
    public ulong TotalFiles { get; set; } = 0;

    [JsonPropertyName("total_size_mb")]
    public double TotalSizeMb { get; set; } = 0.0;

}
