// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ddca369fb5058f6d18491af28e05a3c45c4b79d27813d0ffc9626497e39a5442
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Hierarchical level of an OCR element./// /// Maps to Tesseract's page segmentation hierarchy and provides/// equivalent semantics for PaddleOCR./// </summary>
public enum OcrElementLevel
{/// <summary>    /// Individual word    /// </summary>
[JsonPropertyName("word")]
    Word,/// <summary>    /// Line of text (default for PaddleOCR)    /// </summary>
[JsonPropertyName("line")]
    Line,/// <summary>    /// Paragraph or text block    /// </summary>
[JsonPropertyName("block")]
    Block,/// <summary>    /// Page-level element    /// </summary>
[JsonPropertyName("page")]
    Page,}
