// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7f5b58325e92ce81bd249d15a8b363477dc8877f2cb3175dc8e7acb840a0b16b
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Hierarchical level of an OCR element./// /// Maps to Tesseract's page segmentation hierarchy and provides/// equivalent semantics for PaddleOCR./// </summary>
public enum OcrElementLevel
{/// <summary>    /// Individual word    /// </summary>
    [JsonPropertyName("word")]
    Word,/// <summary>    /// Line of text (default for PaddleOCR)    /// </summary>
    [JsonPropertyName("line")]
    Line,/// <summary>    /// Paragraph or text block    /// </summary>
    [JsonPropertyName("block")]
    Block,/// <summary>    /// Page-level element    /// </summary>
    [JsonPropertyName("page")]
    Page,
}
