// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:bd2f8b32f3c2b1553be6aaba6a37a43eea5be4d15475b12c4cf23662c921f594
#nullable enable

using System;

namespace Kreuzberg;

public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
