// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a2c941ba74387de6d97ab3063b3468e8869077e6ff145a7e2cb0acaef68baef5
#nullable enable

using System;

namespace Kreuzberg;

public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
