// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:46583011eb96c4788c3abfe04ed447ee549ca1bdba5d058808e0ba7781bab3e3
#nullable enable

using System;

namespace Kreuzberg;

public class OtherException : KreuzbergErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
