// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:413d488631501300de202f8814d07114ede4145fb3ea9f5cdb948b41fd3435bf
#nullable enable

using System;

namespace Kreuzberg;

public class OtherException : KreuzbergErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
