// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0552890bd83b27296070dfb7058c8b0719e32b4dbbd39ae4072e91362e555ef4
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Type of paginated unit in a document./// /// Distinguishes between different types of "pages" (PDF pages, presentation slides, spreadsheet sheets)./// </summary>
public enum PageUnitType
{/// <summary>    /// Standard document pages (PDF, DOCX, images)    /// </summary>
    [JsonPropertyName("page")]
    Page,/// <summary>    /// Presentation slides (PPTX, ODP)    /// </summary>
    [JsonPropertyName("slide")]
    Slide,/// <summary>    /// Spreadsheet sheets (XLSX, ODS)    /// </summary>
    [JsonPropertyName("sheet")]
    Sheet,
}
