// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:59120fd4c5a509d7e1e4476a7665a55a2514d046e2e5d73e52dae7e5d6bb84af
#nullable enable

using System;

namespace Kreuzberg;

public class ParsingException : KreuzbergErrorException
{
    public ParsingException(string message) : base(message) { }

    public ParsingException(string message, Exception innerException) : base(message, innerException) { }
}
