// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2aa344a54ab295535277e21ab7489588a86d59cd8ff65ad5fdd0fabb763d42b8
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Type of PDF annotation./// </summary>
public enum PdfAnnotationType
{/// <summary>    /// Sticky note / text annotation    /// </summary>
[JsonPropertyName("text")]
    Text,/// <summary>    /// Highlighted text region    /// </summary>
[JsonPropertyName("highlight")]
    Highlight,/// <summary>    /// Hyperlink annotation    /// </summary>
[JsonPropertyName("link")]
    Link,/// <summary>    /// Rubber stamp annotation    /// </summary>
[JsonPropertyName("stamp")]
    Stamp,/// <summary>    /// Underline text markup    /// </summary>
[JsonPropertyName("underline")]
    Underline,/// <summary>    /// Strikeout text markup    /// </summary>
[JsonPropertyName("strike_out")]
    StrikeOut,/// <summary>    /// Any other annotation type    /// </summary>
[JsonPropertyName("other")]
    Other,}
