// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:ed1c2730b83b3474300a599f49a4a94d3109ccd576309628ff3d27918db5f334
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Type of PDF annotation./// </summary>
public enum PdfAnnotationType
{/// <summary>    /// Sticky note / text annotation    /// </summary>
    [JsonPropertyName("text")]
    Text,/// <summary>    /// Highlighted text region    /// </summary>
    [JsonPropertyName("highlight")]
    Highlight,/// <summary>    /// Hyperlink annotation    /// </summary>
    [JsonPropertyName("link")]
    Link,/// <summary>    /// Rubber stamp annotation    /// </summary>
    [JsonPropertyName("stamp")]
    Stamp,/// <summary>    /// Underline text markup    /// </summary>
    [JsonPropertyName("underline")]
    Underline,/// <summary>    /// Strikeout text markup    /// </summary>
    [JsonPropertyName("strike_out")]
    StrikeOut,/// <summary>    /// Any other annotation type    /// </summary>
    [JsonPropertyName("other")]
    Other,
}
