// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1916ef4483da0f2ac12e73f3f121d57d2b5e81e885b1494cbe7bc09696833882
#nullable enable

using System;

namespace Kreuzberg;

public class PluginException : KreuzbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
