// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f47c1ca6b711338f3db1608bf8f3315a8f638a380677479e2ffa185dbd0475cb
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Error type for pool operations./// </summary>
public enum PoolError
{/// <summary>    /// The pool's internal mutex was poisoned.    ///     /// This indicates a panic occurred while holding the lock.    /// The pool is in a locked state and cannot be recovered.    /// </summary>
    [JsonPropertyName("lockpoisoned")]
    LockPoisoned,
}
