// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4793423ccfa9960c6d1b3b9641a9cb060bc66c5408c540f63d16e3aac2f779ed
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// PowerPoint presentation metadata.
///
/// Extracted from PPTX files containing slide counts and presentation details.
/// </summary>
public sealed class PptxMetadata
{
    /// <summary>
    /// Total number of slides in the presentation
    /// </summary>
    [JsonPropertyName("slide_count")]
    public ulong SlideCount { get; set; } = 0;

    /// <summary>
    /// Names of slides (if available)
    /// </summary>
    [JsonPropertyName("slide_names")]
    public List<string> SlideNames { get; set; } = [];

    /// <summary>
    /// Number of embedded images
    /// </summary>
    [JsonPropertyName("image_count")]
    public ulong? ImageCount { get; set; } = null;

    /// <summary>
    /// Number of tables
    /// </summary>
    [JsonPropertyName("table_count")]
    public ulong? TableCount { get; set; } = null;

}
