// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b0e02dd69175f3a493500048b35949e857a088745743e42d49f36d960124df33
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Processing stages for post-processors.
///
/// Post-processors are executed in stage order (Early → Middle → Late).
/// Use stages to control the order of post-processing operations.
/// </summary>
public enum ProcessingStage
{
    /// <summary>
    /// Early stage - foundational processing.
    ///
    /// Use for:
    /// - Language detection
    /// - Character encoding normalization
    /// - Entity extraction (NER)
    /// - Text quality scoring
    /// </summary>
    [JsonPropertyName("early")]
    Early,
    /// <summary>
    /// Middle stage - content transformation.
    ///
    /// Use for:
    /// - Keyword extraction
    /// - Token reduction
    /// - Text summarization
    /// - Semantic analysis
    /// </summary>
    [JsonPropertyName("middle")]
    Middle,
    /// <summary>
    /// Late stage - final enrichment.
    ///
    /// Use for:
    /// - Custom user hooks
    /// - Analytics/logging
    /// - Final validation
    /// - Output formatting
    /// </summary>
    [JsonPropertyName("late")]
    Late,
}
