// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:43019633fe3f39e06b1d7e1b6a822fcab77f86cb12f15ce2f082037df14ba2d6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A non-fatal warning from a processing pipeline stage.
///
/// Captures errors from optional features that don't prevent extraction
/// but may indicate degraded results.
/// </summary>
public sealed class ProcessingWarning
{
    /// <summary>
    /// The pipeline stage or feature that produced this warning
    /// (e.g., "embedding", "chunking", "language_detection", "output_format").
    /// </summary>
    [JsonPropertyName("source")]
    public string Source { get; set; } = "";

    /// <summary>
    /// Human-readable description of what went wrong.
    /// </summary>
    [JsonPropertyName("message")]
    public string Message { get; set; } = "";

}
