// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6dbcb9c8bd11af66c436daadc1da2a519a1d74f687a7fb47e039a43c67b0d0f6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Page Segmentation Mode for Tesseract OCR
/// </summary>
public enum PsmMode
{
    [JsonPropertyName("osdonly")]
    OsdOnly,
    [JsonPropertyName("autoosd")]
    AutoOsd,
    [JsonPropertyName("autoonly")]
    AutoOnly,
    [JsonPropertyName("auto")]
    Auto,
    [JsonPropertyName("singlecolumn")]
    SingleColumn,
    [JsonPropertyName("singleblockvertical")]
    SingleBlockVertical,
    [JsonPropertyName("singleblock")]
    SingleBlock,
    [JsonPropertyName("singleline")]
    SingleLine,
    [JsonPropertyName("singleword")]
    SingleWord,
    [JsonPropertyName("circleword")]
    CircleWord,
    [JsonPropertyName("singlechar")]
    SingleChar,
}
