// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8f752bf293a832106888e12b6d0e369f5c1a251aa6e9a9082c680628aed5909c
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Page Segmentation Mode for Tesseract OCR/// </summary>
public enum PsmMode
{
    [JsonPropertyName("osdonly")]
    OsdOnly, [JsonPropertyName("autoosd")]
    AutoOsd, [JsonPropertyName("autoonly")]
    AutoOnly, [JsonPropertyName("auto")]
    Auto, [JsonPropertyName("singlecolumn")]
    SingleColumn, [JsonPropertyName("singleblockvertical")]
    SingleBlockVertical, [JsonPropertyName("singleblock")]
    SingleBlock, [JsonPropertyName("singleline")]
    SingleLine, [JsonPropertyName("singleword")]
    SingleWord, [JsonPropertyName("circleword")]
    CircleWord, [JsonPropertyName("singlechar")]
    SingleChar,
}
