// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fe4083af02167df1846c865ae0cbefc90d41459c1650ed6e453b9faffb456168
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Outlook PST archive metadata.
/// </summary>
public sealed class PstMetadata
{
    [JsonPropertyName("message_count")]
    public ulong MessageCount { get; set; } = 0;

}
