// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ac78e2224dabafc442f98ea6639d34aa767a6caccceeb89e8da404b1d0d7730f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// RAKE-specific parameters.
/// </summary>
public sealed class RakeParams
{
    /// <summary>
    /// Minimum word length to consider (default: 1).
    /// </summary>
    [JsonPropertyName("min_word_length")]
    public ulong MinWordLength { get; set; } = 1;

    /// <summary>
    /// Maximum words in a keyword phrase (default: 3).
    /// </summary>
    [JsonPropertyName("max_words_per_phrase")]
    public ulong MaxWordsPerPhrase { get; set; } = 3;

}
