// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:86dd4064d3110196810f3611d0e918fe369cc50f35eab311b7429a5fb288f058
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public enum ReductionLevel
{
    [JsonPropertyName("off")]
    Off, [JsonPropertyName("light")]
    Light, [JsonPropertyName("moderate")]
    Moderate, [JsonPropertyName("aggressive")]
    Aggressive, [JsonPropertyName("maximum")]
    Maximum,
}
