// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2497a38e6d88179e306555e753983c6f51782d5a3145ff9addda660e8ca852ac
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

public enum ReductionLevel
{
    [JsonPropertyName("off")]
    Off,
    [JsonPropertyName("light")]
    Light,
    [JsonPropertyName("moderate")]
    Moderate,
    [JsonPropertyName("aggressive")]
    Aggressive,
    [JsonPropertyName("maximum")]
    Maximum,
}
