// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7e6afd0df8e6b831c55ab0feff1a04bdcdecacb09e897c8245957fe562fbf6c9
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Result-shape selection for extraction results./// /// Distinct from `OutputFormat` (which controls rendering — Plain, Markdown,/// HTML, etc.). `ResultFormat` controls the *shape* of the result: a unified content/// blob vs. an element-based decomposition./// </summary>
public enum ResultFormat
{/// <summary>    /// Unified format with all content in `content` field    /// </summary>
[JsonPropertyName("unified")]
    Unified,/// <summary>    /// Element-based format with semantic element extraction    /// </summary>
[JsonPropertyName("element_based")]
    ElementBased,}
