// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4e9f657e30dff0f7a1a80bfa8b3009a36eda5f82555ce7f42a1a4dd531f4f9b5
#nullable enable

using System;

namespace Kreuzberg;

public class SecurityException : KreuzbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
