// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:299b815155c95c906359f437b96b37619b75147ab96fa10800e3542af7a421bc
#nullable enable

using System;

namespace Kreuzberg;

public class SecurityException : KreuzbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
