// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3ecfa9b0b59b1a60b1f1c9c8ca8e5608e2cd7a7fbf17d67da87a3639d8967db5
#nullable enable

using System;

namespace Kreuzberg;

public class SecurityException : KreuzbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
