// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7e75979c5f6bf407832c353c6a9c8ca0a74546d8e014136be667ecdc9d0d3a0e
#nullable enable

using System;

namespace Kreuzberg;

public class SerializationException : KreuzbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
