// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:02f9b627683d87fce577298cf06df878a9af866ce79278d92156a7710743c8be
#nullable enable

using System;

namespace Kreuzberg;

public class SerializationException : KreuzbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
