// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:615db63c533cc4c447de9231cfacfeb788de6dd641627186a9e4d58113889bbb
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;
namespace Kreuzberg;

internal sealed class StreamReaderSafeHandle : SafeHandle
{
    internal StreamReaderSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.StreamReaderFree(handle);
        return true;
    }
}

public sealed class StreamReader : IDisposable
{
    private readonly StreamReaderSafeHandle _safeHandle;

    internal StreamReader(IntPtr handle)
    {
        _safeHandle = new StreamReaderSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();

}
