// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:36a9e35116f2c90e05458f34f137c94780b99f3e9c0aab6f2bf13ce43c2e3c3e
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;using System.Text.Json;
using System.Text.Json.Serialization;using System.Threading.Tasks;
namespace Kreuzberg;

internal sealed class TesseractWasmBackendSafeHandle : SafeHandle
{
    internal TesseractWasmBackendSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.TesseractWasmBackendFree(handle);
        return true;
    }
}
/// <summary>/// WASM-compatible Tesseract OCR backend./// /// This backend uses direct FFI calls to Tesseract for WASM compatibility./// It does not depend on the OcrProcessor which requires full Tokio runtime./// </summary>
public sealed class TesseractWasmBackend : IDisposable
{    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };
    private readonly TesseractWasmBackendSafeHandle _safeHandle;

    internal TesseractWasmBackend(IntPtr handle)
    {
        _safeHandle = new TesseractWasmBackendSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();


    public string Name()
    {
        var nativeResult = NativeMethods.TesseractWasmBackendName(
            Handle
        );
        if (nativeResult == IntPtr.Zero)
        {
            throw new KreuzbergException(0, "TesseractWasmBackendName failed");
        }
        var returnValue = Marshal.PtrToStringUTF8(nativeResult) ?? string.Empty;
        NativeMethods.FreeString(nativeResult);
        return returnValue;
    }

    public string Version()
    {
        var nativeResult = NativeMethods.TesseractWasmBackendVersion(
            Handle
        );
        if (nativeResult == IntPtr.Zero)
        {
            throw new KreuzbergException(0, "TesseractWasmBackendVersion failed");
        }
        var returnValue = Marshal.PtrToStringUTF8(nativeResult) ?? string.Empty;
        NativeMethods.FreeString(nativeResult);
        return returnValue;
    }

    public void Initialize()
    {
        NativeMethods.TesseractWasmBackendInitialize(
            Handle
        );
    }

    public void Shutdown()
    {
        NativeMethods.TesseractWasmBackendShutdown(
            Handle
        );
    }

    public async Task<ExtractionResult> ProcessImage(byte[] imageBytes, OcrConfig config)
    {
        var imageBytesHandle = GCHandle.Alloc(imageBytes, GCHandleType.Pinned);
        var configJson = JsonSerializer.Serialize(config, JsonOptions);
        var configHandle = NativeMethods.OcrConfigFromJson(configJson);
        return await Task.Run(() =>
        {
            var nativeResult = NativeMethods.TesseractWasmBackendProcessImage(
                Handle,
                imageBytesHandle.AddrOfPinnedObject(),
                configHandle
            );
            if (nativeResult == IntPtr.Zero)
            {
                throw new KreuzbergException(0, "TesseractWasmBackendProcessImage failed");
            }
            var jsonPtr = NativeMethods.ExtractionResultToJson(nativeResult);
            var json = Marshal.PtrToStringUTF8(jsonPtr);
            NativeMethods.FreeString(jsonPtr);
            NativeMethods.ExtractionResultFree(nativeResult);
            var returnValue = JsonSerializer.Deserialize<ExtractionResult>(json ?? "null", JsonOptions)!;
            imageBytesHandle.Free();
            NativeMethods.OcrConfigFree(configHandle);
            return returnValue;
        });
    }

    public async Task<ExtractionResult> ProcessImageFile(string path, OcrConfig config)
    {
        var configJson = JsonSerializer.Serialize(config, JsonOptions);
        var configHandle = NativeMethods.OcrConfigFromJson(configJson);
        return await Task.Run(() =>
        {
            var nativeResult = NativeMethods.TesseractWasmBackendProcessImageFile(
                Handle,
                path,
                configHandle
            );
            if (nativeResult == IntPtr.Zero)
            {
                throw new KreuzbergException(0, "TesseractWasmBackendProcessImageFile failed");
            }
            var jsonPtr = NativeMethods.ExtractionResultToJson(nativeResult);
            var json = Marshal.PtrToStringUTF8(jsonPtr);
            NativeMethods.FreeString(jsonPtr);
            NativeMethods.ExtractionResultFree(nativeResult);
            var returnValue = JsonSerializer.Deserialize<ExtractionResult>(json ?? "null", JsonOptions)!;
            NativeMethods.OcrConfigFree(configHandle);
            return returnValue;
        });
    }

    public bool SupportsLanguage(string lang)
    {
        var nativeResult = NativeMethods.TesseractWasmBackendSupportsLanguage(
            Handle,
            lang
        );
        var returnValue = nativeResult != 0;
        return returnValue;
    }

    public OcrBackendType BackendType()
    {
        var nativeResult = NativeMethods.TesseractWasmBackendBackendType(
            Handle
        );
        if (nativeResult == IntPtr.Zero)
        {
            throw new KreuzbergException(0, "TesseractWasmBackendBackendType failed");
        }
        var json = Marshal.PtrToStringUTF8(nativeResult);
        NativeMethods.FreeString(nativeResult);
        var returnValue = JsonSerializer.Deserialize<OcrBackendType>(json ?? "null", JsonOptions)!;
        return returnValue;
    }
}
