// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0e0eae4a8c49c0fd6a15d7f003c97a48af0da4e55100d3649bf0fe3b79d818d0
#nullable enable

using System;

namespace Kreuzberg;

public class TimeoutException : KreuzbergErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
