// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d3885e717e58bd25049f9b9123f240d0ac2f48ee195a6040859290d4b8a09f1e
#nullable enable

using System;

namespace Kreuzberg;

public class TimeoutException : KreuzbergErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
