// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:22f8a0292a4e9f36538e840dd93e3d8cfef3125d67cb57ea58a7d30940ee489d
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
