// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7d02634e7c8d547adbd6d9470c809ec9d2f0f4e6c6b9b3965f4fcf2a183aa839
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
