// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c047cf17c2e816392d13cab5370e5c18b98c27a3e2f44108d4b8ef26968fbb5d
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
