// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:527a1ad3f28c2691fb1d4b0d7fc069d8359ccac268200c08c255d468fc3432e0
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Semantic classification of an extracted URI./// </summary>
public enum UriKind
{/// <summary>    /// A clickable hyperlink (web URL, file link).    /// </summary>
    [JsonPropertyName("hyperlink")]
    Hyperlink,/// <summary>    /// An image or media resource reference.    /// </summary>
    [JsonPropertyName("image")]
    Image,/// <summary>    /// An internal anchor or cross-reference target.    /// </summary>
    [JsonPropertyName("anchor")]
    Anchor,/// <summary>    /// A citation or bibliographic reference (DOI, academic ref).    /// </summary>
    [JsonPropertyName("citation")]
    Citation,/// <summary>    /// A general reference (e.g. `\ref{}` in LaTeX, `:ref:` in RST).    /// </summary>
    [JsonPropertyName("reference")]
    Reference,/// <summary>    /// An email address (`mailto:` link or bare email).    /// </summary>
    [JsonPropertyName("email")]
    Email,
}
