// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:88a91bad84b45c9902211b869c21aed440535dba101c6b97323e7a816b326ca7
#nullable enable

using System;

namespace Kreuzberg;

public class ValidationException : KreuzbergErrorException
{
    public ValidationException(string message) : base(message) { }

    public ValidationException(string message, Exception innerException) : base(message, innerException) { }
}
