// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:db59ed6e296d0ba4bc2c28325eff573512c076cc9cddbaf714d993caad7f833c
#nullable enable

using System;

namespace Kreuzberg;

public class ValidationException : KreuzbergErrorException
{
    public ValidationException(string message) : base(message) { }

    public ValidationException(string message, Exception innerException) : base(message, innerException) { }
}
