// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:31308feb572ea9295aa4b35e008886bd09dd9dfd8093caff7781a5db76b8a98e
#nullable enable

using System;

namespace Kreuzberg;

public class ValidationException : KreuzbergErrorException
{
    public ValidationException(string message) : base(message) { }

    public ValidationException(string message, Exception innerException) : base(message, innerException) { }
}
