// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6bd407102e72d8a101cfdc4df2dc1618a89bc69ba68c1a40b97f99abd5c530ed
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Year range for bibliographic metadata.
/// </summary>
public sealed class YearRange
{
    [JsonPropertyName("min")]
    public uint? Min { get; set; } = null;

    [JsonPropertyName("max")]
    public uint? Max { get; set; } = null;

    [JsonPropertyName("years")]
    public List<uint> Years { get; set; } = [];


    /// <summary>
    /// Parse a <see cref="YearRange"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static YearRange FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<YearRange>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse YearRange from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse YearRange from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
