// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1d3e849857b4538501c731f605625cdb20a28abc13770b5d973fff40faa3987f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Year range for bibliographic metadata.
/// </summary>
public sealed class YearRange
{
    [JsonPropertyName("min")]
    public uint? Min { get; set; } = null;

    [JsonPropertyName("max")]
    public uint? Max { get; set; } = null;

    [JsonPropertyName("years")]
    public List<uint> Years { get; set; } = [];

}
