// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:82730790610d87a1859964612f3a16a2e64a14dad1d4a70849d12930f743b234
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;
namespace Kreuzberg;

internal sealed class ZipBombValidatorSafeHandle : SafeHandle
{
    internal ZipBombValidatorSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.ZipBombValidatorFree(handle);
        return true;
    }
}
/// <summary>/// Helper struct for validating ZIP archives for security issues./// </summary>
public sealed class ZipBombValidator : IDisposable
{
    private readonly ZipBombValidatorSafeHandle _safeHandle;

    internal ZipBombValidator(IntPtr handle)
    {
        _safeHandle = new ZipBombValidatorSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();

}
