// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b06681f585c0609875be1410c9578d883b1bde6a2d8594e49a7c3b892f3816f4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";
import wasm from "vite-plugin-wasm";

export default defineConfig({
  plugins: [wasm()],
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    setupFiles: ["./setup.ts"],
  },
});
