// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c1d88703ebc099f0e9cd0622c4dcee7298e1c504a97b2c0fa914429e4c6cd54c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Kreuzberg
import RustBridge

/// E2e tests for category: contract.
final class ContractTests: XCTestCase {
    func testConfigDocumentStructureWithHeadings() throws {
        // Tests document structure with DOCX heading-driven nesting
        let result = try extractFileSync("docx/fake.docx", "{\"include_document_structure\":true}")
        XCTAssertEqual(result.mime_type().toString().trimmingCharacters(in: .whitespaces), "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
        XCTAssertNotNil(result.document(), "expected non-nil value")
        XCTAssertGreaterThanOrEqual(result.document()?.nodes().count ?? 0, 1)
    }

    func testConfigExtractionTimeout() throws {
        // Tests that extraction_timeout_secs config field is accepted and does not affect fast extractions
        let result = try extractFileSync("pdf/fake_memo.pdf", "{\"extraction_timeout_secs\":300}")
        XCTAssertEqual(result.mime_type().toString().trimmingCharacters(in: .whitespaces), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content().toString().count, 10)
    }

    func testConfigSecurityLimits() throws {
        // Tests archive extraction with custom security limits
        let result = try extractFileSync("archives/documents.zip", "{\"security_limits\":{\"max_archive_size\":104857600,\"max_compression_ratio\":50,\"max_files_in_archive\":100}}")
        XCTAssertTrue(result.mime_type().toString().contains("application/zip") || result.mime_type().toString().contains("application/x-zip-compressed"), "expected to contain at least one of the specified values")
        XCTAssertGreaterThanOrEqual(result.content().toString().count, 10)
    }

    func testOutputFormatBytesMarkdown() throws {
        // Tests markdown output format via bytes extraction API
        let result = try extractBytesSync("pdf/fake_memo.pdf", "application/pdf", "{\"output_format\":\"markdown\"}")
        XCTAssertEqual(result.mime_type().toString().trimmingCharacters(in: .whitespaces), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content().toString().count, 10)
        XCTAssertEqual(((result.metadata().output_format())?.toString() ?? "").trimmingCharacters(in: .whitespaces), "markdown")
    }

    func testOutputFormatMarkdown() throws {
        // Tests Markdown output format
        let result = try extractFileSync("pdf/fake_memo.pdf", "{\"output_format\":\"markdown\"}")
        XCTAssertEqual(result.mime_type().toString().trimmingCharacters(in: .whitespaces), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content().toString().count, 10)
        XCTAssertEqual(((result.metadata().output_format())?.toString() ?? "").trimmingCharacters(in: .whitespaces), "markdown")
    }

}
