// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5c629631609756b23f36ba574c0d722a45de00421b7544aac798a1c712db310a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Kreuzberg
import RustBridge

/// E2e tests for category: detection.
final class DetectionTests: XCTestCase {
    func testDetectMimeBytesHtml() throws {
        // Detect HTML MIME from bytes
        let result = try detectMimeTypeFromBytes("html/html.html")
    }

    func testDetectMimeBytesPdf() throws {
        // Detect PDF MIME type from bytes
        let result = try detectMimeTypeFromBytes("pdf/fake_memo.pdf")
    }

    func testDetectMimeBytesPng() throws {
        // Detect PNG MIME type from bytes
        let result = try detectMimeTypeFromBytes("images/test_hello_world.png")
    }

    func testGetExtensionsUnknownMime() throws {
        // get_extensions unknown MIME
        XCTAssertThrowsError(try getExtensionsForMime("application/x-totally-unknown"))
    }

}
