// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:817b4a439a44307e03c0ae8ad000d9813627ed36050b61e5ca8c660be210d2c3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: registry_operations.
final class RegistryOperationsTests: XCTestCase {
    func testExtensionsDocx() throws {
        // Get file extensions for DOCX MIME type
        let result = try getExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    }

    func testExtensionsHtml() throws {
        // Get file extensions for HTML MIME type
        let result = try getExtensionsForMime("text/html")
    }

    func testExtensionsPdf() throws {
        // Get file extensions for PDF MIME type
        let result = try getExtensionsForMime("application/pdf")
        XCTAssertTrue(result.map { $0.as_str().toString() }.contains("pdf"), "expected to contain: \("pdf")")
    }

}
