// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5cb45d6b6191ea998694a03742788d15c5ea4c57a31fd4680a61bd060e404242
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import XCTest
import Foundation
import Kreuzberg
import RustBridge

/// E2e tests for category: smoke.
final class SmokeTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _testDocs = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // <Module>Tests/
            .deletingLastPathComponent() // Tests/
            .deletingLastPathComponent() // swift/
            .deletingLastPathComponent() // packages/
            .deletingLastPathComponent() // <repo root>
            .appendingPathComponent("test_documents")
        if FileManager.default.fileExists(atPath: _testDocs.path) {
            FileManager.default.changeCurrentDirectoryPath(_testDocs.path)
        }
    }

    func testSmokeDocxBasic() async throws {
        // Smoke test: DOCX with formatted text
        let configObj = try extractionConfigFromJson("{}")
        let result = try await extractFile("docx/fake.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", configObj)
        XCTAssertEqual(result.mime_type().toString().trimmingCharacters(in: CharacterSet.whitespaces), "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
        XCTAssertGreaterThanOrEqual(result.content().toString().count, 20)
        XCTAssertTrue(result.content().toString().contains("Lorem") || result.content().toString().contains("ipsum") || result.content().toString().contains("document") || result.content().toString().contains("text"), "expected to contain at least one of the specified values")
    }

    func testSmokeHtmlBasic() async throws {
        // Smoke test: HTML table extraction
        let configObj = try extractionConfigFromJson("{}")
        let result = try await extractFile("html/simple_table.html", "text/html", configObj)
        XCTAssertEqual(result.mime_type().toString().trimmingCharacters(in: CharacterSet.whitespaces), "text/html")
        XCTAssertGreaterThanOrEqual(result.content().toString().count, 10)
        XCTAssertTrue(result.content().toString().contains("Sample Data Table") || result.content().toString().contains("Laptop") || result.content().toString().contains("Electronics") || result.content().toString().contains("Product"), "expected to contain at least one of the specified values")
    }

    func testSmokeJsonBasic() async throws {
        // Smoke test: JSON file extraction
        let configObj = try extractionConfigFromJson("{}")
        let result = try await extractFile("json/simple.json", "application/json", configObj)
        XCTAssertEqual(result.mime_type().toString().trimmingCharacters(in: CharacterSet.whitespaces), "application/json")
        XCTAssertGreaterThanOrEqual(result.content().toString().count, 5)
    }

    func testSmokePdfBasic() async throws {
        // Smoke test: PDF with simple text extraction
        let configObj = try extractionConfigFromJson("{}")
        let result = try await extractFile("pdf/fake_memo.pdf", "application/pdf", configObj)
        XCTAssertEqual(result.mime_type().toString().trimmingCharacters(in: CharacterSet.whitespaces), "application/pdf")
        XCTAssertGreaterThanOrEqual(result.content().toString().count, 50)
        XCTAssertTrue(result.content().toString().contains("May 5, 2023") || result.content().toString().contains("To Whom it May Concern"), "expected to contain at least one of the specified values")
    }

    func testSmokeTxtBasic() async throws {
        // Smoke test: Plain text file
        let configObj = try extractionConfigFromJson("{}")
        let result = try await extractFile("text/report.txt", "text/plain", configObj)
        XCTAssertEqual(result.mime_type().toString().trimmingCharacters(in: CharacterSet.whitespaces), "text/plain")
        XCTAssertGreaterThanOrEqual(result.content().toString().count, 5)
    }

    func testSmokeXlsxBasic() async throws {
        // Smoke test: XLSX with basic spreadsheet data including tables
        let configObj = try extractionConfigFromJson("{}")
        let result = try await extractFile("xlsx/stanley_cups.xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", configObj)
        XCTAssertEqual(result.mime_type().toString().trimmingCharacters(in: CharacterSet.whitespaces), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
        XCTAssertGreaterThanOrEqual(result.content().toString().count, 100)
        XCTAssertTrue(result.content().toString().contains("Team"), "expected to contain: \("Team")")
        XCTAssertTrue(result.content().toString().contains("Location"), "expected to contain: \("Location")")
        XCTAssertTrue(result.content().toString().contains("Stanley Cups"), "expected to contain: \("Stanley Cups")")
        XCTAssertTrue(result.content().toString().contains("Blues"), "expected to contain: \("Blues")")
        XCTAssertTrue(result.content().toString().contains("Flyers"), "expected to contain: \("Flyers")")
        XCTAssertTrue(result.content().toString().contains("Maple Leafs"), "expected to contain: \("Maple Leafs")")
        XCTAssertTrue(result.content().toString().contains("STL"), "expected to contain: \("STL")")
        XCTAssertTrue(result.content().toString().contains("PHI"), "expected to contain: \("PHI")")
        XCTAssertTrue(result.content().toString().contains("TOR"), "expected to contain: \("TOR")")
        XCTAssertGreaterThanOrEqual(result.tables().count, 1)
        // skipped: field 'metadata.format.excel.sheet_count' crosses a tagged-union variant boundary (not expressible in Swift)
        // skipped: field 'metadata.format.excel.sheet_names' crosses a tagged-union variant boundary (not expressible in Swift)
    }

}
