# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:957d19b73463a710e70090b6e938f2f05d94d3dc65b01b812f423e00415ab4b9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: async

test_that("async_extract_bytes_empty_mime: extract_bytes empty MIME async", {
  expect_error(extract_bytes(content = readBin(.resolve_fixture("text/plain.txt"), what = "raw", n = file.info(.resolve_fixture("text/plain.txt"))$size), mime_type = "", config = ExtractionConfig$default()))
})

test_that("async_extract_bytes_invalid_mime: extract_bytes unsupported MIME async", {
  expect_error(extract_bytes(content = readBin(.resolve_fixture("text/plain.txt"), what = "raw", n = file.info(.resolve_fixture("text/plain.txt"))$size), mime_type = "application/x-nonexistent", config = ExtractionConfig$default()))
})
