# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f5d4c79920a4cef1f7382b4ca7648c0f5fc74983c75fc073e06be14163e12bd0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: registry_operations

test_that("extensions_docx: Get file extensions for DOCX MIME type", {
  result <- get_extensions_for_mime(mime_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
})

test_that("extensions_html: Get file extensions for HTML MIME type", {
  result <- get_extensions_for_mime(mime_type = "text/html")
})

test_that("extensions_pdf: Get file extensions for PDF MIME type", {
  result <- get_extensions_for_mime(mime_type = "application/pdf")
  expect_true(grepl("pdf", result$result, fixed = TRUE))
})

test_that("list_formats_all: List all supported formats and their extensions", {
  result <- extract_file()
})
