# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d2f6e2240798b3a8366a7d82d1ac89dac0dbb7a254f4219c4ec8d8b5218c7602
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: extraction

test_that("extract_doc_basic: Extract text from a DOC file containing unit test lists", {
  result <- extract_file()
  expect_true(nchar(result$content) >= 10)
})

test_that("extract_email_basic: Extract content from an email file in EML format", {
  result <- extract_file()
})

test_that("extract_pdf_basic: Extract text from a basic PDF document containing memo content", {
  result <- extract_file()
  expect_true(nchar(result$content) >= 50)
})

test_that("extract_pdf_code: Extract text from PDF containing code snippets and formulas", {
  result <- extract_file()
  expect_true(nchar(result$content) >= 20)
})

test_that("extract_pptx_basic: Extract text from a PowerPoint presentation file", {
  result <- extract_file()
})
