# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:800882b0a98e49f32c1d5137eadf6f5b858c4c77e367e0548810a64d79d972e3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: embed_extra

test_that("embed_normalize_unit: Normalize unit vector", {
  result <- extract_file()
})

test_that("embed_normalize_zero: Normalize zero vector", {
  result <- extract_file()
})
