# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dca3905fefbbde85fe4c18b92a121595cb562f5025509dd8f83925621b7d9143
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: registry

test_that("list_document_extractors: List document extractors", {
  result <- list_document_extractors(list())
})

test_that("list_ocr_backends: List OCR backends", {
  result <- list_ocr_backends(list())
})

test_that("list_post_processors: List post-processors", {
  result <- list_post_processors(list())
})

test_that("list_validators: List validators", {
  result <- list_validators(list())
})
