# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c7795075ff903f738e00af85f66302a18dc167eb3a75406f62d037d5e76ea118
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: serialization

test_that("serialize_json_basic: Serialize extraction result to JSON", {
  result <- (list("config" = list(), "path" = "test_documents/text/plain.txt"))
  expect_true(nchar(result$content) >= 1)
})

test_that("serialize_json_pdf: Serialize PDF extraction to JSON", {
  result <- (list("config" = list(), "path" = "test_documents/pdf/sample.pdf"))
  expect_true(grepl("content", result$content, fixed = TRUE))
})

test_that("serialize_toon_basic: Serialize extraction result to TOON format", {
  result <- (list("config" = list(), "path" = "test_documents/text/plain.txt"))
  expect_true(nchar(result$content) >= 1)
})

test_that("serialize_toon_pdf: Serialize PDF extraction to TOON", {
  result <- (list("config" = list(), "path" = "test_documents/pdf/sample.pdf"))
  expect_true(nchar(result$content) >= 10)
})
