# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:93e45445de4af915bca85674f298c42e7db9203bb18770b61b5061ecbabb6e9b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: contract

test_that("api_batch_bytes_async: Tests async batch bytes extraction API (batch_extract_bytes)", {
  result <- extract_file(path = "pdf/fake_memo.pdf")
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 10)
  expect_true(any(sapply(c("May 5, 2023", "Mallori"), function(v) grepl(v, result$content, fixed = TRUE))))
})

test_that("api_batch_bytes_with_configs_async: Tests async batch bytes extraction with per-file configs (batch_extract_bytes with file_configs parameter)", {
  result <- extract_file(path = "pdf/fake_memo.pdf", config = list("output_format" = "markdown"))
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 10)
  expect_equal(trimws(result$metadata$output_format), "markdown")
})

test_that("api_batch_file_async: Tests async batch file extraction API (batch_extract_file)", {
  result <- extract_file(path = "pdf/fake_memo.pdf")
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 10)
  expect_true(any(sapply(c("May 5, 2023", "Mallori"), function(v) grepl(v, result$content, fixed = TRUE))))
})

test_that("api_batch_file_with_configs_async: Tests async batch file extraction with per-file configs (batch_extract_files with file_configs parameter)", {
  result <- extract_file(path = "pdf/fake_memo.pdf", config = list("output_format" = "markdown"))
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 10)
  expect_equal(trimws(result$metadata$output_format), "markdown")
})

test_that("api_extract_bytes_async: Tests async bytes extraction API (extract_bytes)", {
  result <- extract_file(path = "pdf/fake_memo.pdf")
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 10)
  expect_true(any(sapply(c("May 5, 2023", "Mallori"), function(v) grepl(v, result$content, fixed = TRUE))))
})

test_that("api_extract_file_async: Tests async file extraction API (extract_file)", {
  result <- extract_file(path = "pdf/fake_memo.pdf")
  expect_equal(trimws(result$mime_type), "application/pdf")
  expect_true(nchar(result$content) >= 10)
  expect_true(any(sapply(c("May 5, 2023", "Mallori"), function(v) grepl(v, result$content, fixed = TRUE))))
})
