# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:12119f695a80fb5cdc3111fbd0123acd23e1851246acd3505b5389a476ce0e0a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: uri

test_that("classify_uri_anchor: Classify fragment URI", {
  result <- extract_file()
})

test_that("classify_uri_email: Classify mailto URI", {
  result <- extract_file()
})

test_that("classify_uri_https: Classify HTTPS URL", {
  result <- extract_file()
})
