# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:046ab143cc1e6cc0317869dada2ae36bd6000445faca55a6cd60d0fb11d7721a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: registry

test_that("list_document_extractors: List document extractors", {
  result <- list_document_extractors()
  expect_true(TRUE)
})

test_that("list_embedding_backends: List embedding backends", {
  result <- jsonlite::fromJSON(extract_file(mime_type = NULL, config = ExtractionConfig$default()), simplifyVector = FALSE)
  expect_true(TRUE)
})

test_that("list_ocr_backends: List OCR backends", {
  result <- list_ocr_backends()
  expect_true(TRUE)
})

test_that("list_post_processors: List post-processors", {
  result <- list_post_processors()
  expect_true(TRUE)
})

test_that("list_renderers: List renderers", {
  result <- jsonlite::fromJSON(extract_file(mime_type = NULL, config = ExtractionConfig$default()), simplifyVector = FALSE)
  expect_true(TRUE)
})

test_that("list_validators: List validators", {
  result <- list_validators()
  expect_true(TRUE)
})
