// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7dd14f124f0db670157b3fdeb0f13888083a4f1d729d06c1490d461941da4f29
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: async

test "async_extract_bytes_empty_mime" {
    // extract_bytes empty MIME async
    const content_bytes = try std.Io.Dir.cwd().readFileAlloc(std.testing.io, "text/plain.txt", std.heap.c_allocator, .unlimited);
    defer std.heap.c_allocator.free(content_bytes);
    const _result_json = kreuzberg.extract_bytes_sync(content_bytes, "", "{}") catch {
        try testing.expect(true); // Error occurred as expected
        return;
    };
    _ = _result_json;
}

test "async_extract_bytes_invalid_mime" {
    // extract_bytes unsupported MIME async
    const content_bytes = try std.Io.Dir.cwd().readFileAlloc(std.testing.io, "text/plain.txt", std.heap.c_allocator, .unlimited);
    defer std.heap.c_allocator.free(content_bytes);
    const _result_json = kreuzberg.extract_bytes_sync(content_bytes, "application/x-nonexistent", "{}") catch {
        try testing.expect(true); // Error occurred as expected
        return;
    };
    _ = _result_json;
}
