// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:214067d326ed4820718a37f97cae7afc51828d687d471946e54e3880d5a7db28
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: registry

test "list_document_extractors" {
    // List document extractors
    _ = try kreuzberg.list_document_extractors();
}

test "list_embedding_backends" {
    // List embedding backends
    const _result_json = try kreuzberg.extract_file_sync(null, null, "{}");
    defer std.heap.c_allocator.free(_result_json);
}

test "list_ocr_backends" {
    // List OCR backends
    _ = try kreuzberg.list_ocr_backends();
}

test "list_post_processors" {
    // List post-processors
    _ = try kreuzberg.list_post_processors();
}

test "list_renderers" {
    // List renderers
    const _result_json = try kreuzberg.extract_file_sync(null, null, "{}");
    defer std.heap.c_allocator.free(_result_json);
}

test "list_validators" {
    // List validators
    _ = try kreuzberg.list_validators();
}
