// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:52d1459476b960def3341c43fb9ad49f03dd857a33dfacf48ca9366871baf3be
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
const std = @import("std");
const testing = std.testing;
const kreuzberg = @import("kreuzberg");

// E2e tests for category: registry_operations

test "extensions_docx" {
    // Get file extensions for DOCX MIME type
    _ = try kreuzberg.get_extensions_for_mime("application/vnd.openxmlformats-officedocument.wordprocessingml.document");
}

test "extensions_html" {
    // Get file extensions for HTML MIME type
    _ = try kreuzberg.get_extensions_for_mime("text/html");
}

test "extensions_pdf" {
    // Get file extensions for PDF MIME type
    const result = try kreuzberg.get_extensions_for_mime("application/pdf");
    try testing.expect(std.mem.indexOf(u8, result, "pdf") != null);
}
