// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2704ea51afc292254db552090271e3ae9a0b76a0592e2d7799ca8349a8ca0068
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from "vitest";
import { extractFile, batchExtractBytesSync } from "kreuzberg";

describe("batch", () => {
  it("batch_bytes_invalid_mime: batch_extract_bytes_sync invalid MIME", () => {
    batchExtractBytesSync([
      { data: "SGVsbG8=", mimeType: "application/x-nonexistent" },
    ] as JsExtractionConfig);
  });

  it("batch_file_async_basic: Extract text from multiple files asynchronously", async () => {
    await extractFile(null);
  });

  it("batch_file_async_not_found: batch_extract_file async nonexistent", async () => {
    await extractFile(null);
  });

  it("batch_file_not_found: batch_extract_file_sync nonexistent", async () => {
    await extractFile(null);
  });

  it("batch_file_partial: batch_extract_file_sync mixed", async () => {
    await extractFile(null);
  });

  it("batch_file_sync_basic: Extract text from multiple files synchronously", async () => {
    await extractFile(null);
  });
});
