// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:bd8f2f571c2375bd2a152afe7b08164296e17a898b58b5afcf4d967ecd5b1026
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from "vitest";
import { extractFile } from "kreuzberg";

describe("embed_extra", () => {
  it("embed_normalize_unit: Normalize unit vector", async () => {
    await extractFile(null);
  });

  it("embed_normalize_zero: Normalize zero vector", async () => {
    await extractFile(null);
  });
});
