// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5f97399f3738ef3c5d84b926aaf4add775dca1b69b49cd81a796ea2b304c8558
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from "vitest";
import { extractFile, type JsExtractionConfig } from "kreuzberg";

describe("image", () => {
  it("image_metadata_only: JPEG image to validate metadata extraction without OCR.", async () => {
    const result = await extractFile("images/example.jpg", undefined, {
      disableOcr: true,
      ocr: null,
    } as JsExtractionConfig);
    expect(result.mimeType.trim()).toBe("image/jpeg");
    expect(result.content.length).toBeLessThanOrEqual(200);
  });

  it("image_svg_basic: SVG image extraction.", async () => {
    const result = await extractFile("xml/simple_svg.svg");
    expect(result.mimeType.trim()).toBe("image/svg+xml");
    expect(result.content.length).toBeGreaterThanOrEqual(5);
  });
});
