// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:24cf015d811f6d9cfcc826348a6aa4ce34e58b27ada4694f5e71975101563c9f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from "vitest";
import { extractFile } from "kreuzberg";

describe("uri", () => {
  it("classify_uri_anchor: Classify fragment URI", async () => {
    await extractFile(null);
  });

  it("classify_uri_email: Classify mailto URI", async () => {
    await extractFile(null);
  });

  it("classify_uri_https: Classify HTTPS URL", async () => {
    await extractFile(null);
  });
});
