# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d42db6cbd2367604bf3ce0519e8dedb9e5291b1aaa89ba608d4669c6f67f39c8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: cache_ops."""
import pytest  # noqa: F401
from kreuzberg import extract_file


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = " ".join(str(value) for value in raw_items) if isinstance(raw_items, list) else ""
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.asyncio
async def test_generate_cache_key_complex() -> None:
    """Complex cache key."""
    path = None
    result = await extract_file(path=path)
    assert len(result.result) >= 5  # noqa: S101

@pytest.mark.asyncio
async def test_validate_cache_key_invalid() -> None:
    """Invalid cache key returns false."""
    path = None
    result = await extract_file(path=path)
    assert not result.result  # noqa: S101
