# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:43e6f24f295152a0a1af4d6ec555e712497b3cfe4cb146201c7d692996771d8c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: table."""
import pytest  # noqa: F401
from kreuzberg import extract_file_sync, ExtractionConfig


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = " ".join(str(value) for value in raw_items) if isinstance(raw_items, list) else ""
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


def test_table_csv_extraction() -> None:
    """CSV file extraction produces content."""
    path = "csv/stanley_cups.csv"
    result = extract_file_sync(path=path)
    assert len(result.content) >= 10  # noqa: S101

def test_table_html_extraction() -> None:
    """HTML table extraction produces markdown format."""
    path = "html/simple_table.html"
    config = ExtractionConfig(output_format="markdown")
    result = extract_file_sync(path=path, config=config)
    assert any(v in result.content for v in ["|"])  # noqa: S101

def test_table_xlsx_markdown() -> None:
    """XLSX extraction produces markdown table format."""
    path = "xlsx/stanley_cups.xlsx"
    config = ExtractionConfig(output_format="markdown")
    result = extract_file_sync(path=path, config=config)
    assert any(v in result.content for v in ["|", "---"])  # noqa: S101
