# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4b5062c7a3d1b24914da056358b54e5afe22959a057c7b82983d39285881cd67
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""E2e tests for category: embed_extra."""
import pytest  # noqa: F401
from kreuzberg import extract_file, embed_texts, ExtractionConfig


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = " ".join(str(value) for value in raw_items) if isinstance(raw_items, list) else ""
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


@pytest.mark.skip(reason="Requires features: embeddings")
@pytest.mark.asyncio
async def test_embed_get_preset() -> None:
    """Get preset by name."""
    path = None
    _ = await extract_file(path=path)

@pytest.mark.skip(reason="Requires features: embeddings")
@pytest.mark.asyncio
async def test_embed_get_preset_invalid() -> None:
    """Get preset invalid name."""
    path = None
    _ = await extract_file(path=path)

@pytest.mark.skip(reason="Requires features: embeddings")
@pytest.mark.asyncio
async def test_embed_list_presets() -> None:
    """Lists available embedding model presets."""
    path = None
    _ = await extract_file(path=path)

@pytest.mark.asyncio
async def test_embed_normalize_unit() -> None:
    """Normalize unit vector."""
    path = None
    _ = await extract_file(path=path)

@pytest.mark.skip(reason="Requires features: embeddings")
@pytest.mark.asyncio
async def test_embed_normalize_vec() -> None:
    """Normalizes a vector of embedding values."""
    path = None
    _ = await extract_file(path=path)

@pytest.mark.asyncio
async def test_embed_normalize_zero() -> None:
    """Normalize zero vector."""
    path = None
    _ = await extract_file(path=path)

@pytest.mark.skip(reason="Requires features: embeddings")
def test_embed_text_basic() -> None:
    """Basic text embedding with default configuration."""
    texts = None
    _ = embed_texts(texts=texts)

@pytest.mark.skip(reason="Requires features: embeddings")
def test_embed_text_long() -> None:
    """Embedding of longer text content."""
    texts = None
    _ = embed_texts(texts=texts)

@pytest.mark.skip(reason="Requires features: embeddings")
def test_embed_texts_batch() -> None:
    """Batch embed texts."""
    texts = ["Hello", "World"]
    config = ExtractionConfig()
    _ = embed_texts(texts=texts, config=config)
