// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:540312d0b5dfdaa97ec92755ab583a305269503a9251be8573555bf3e783c918
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import dev.kreuzberg.ExtractionConfig;

/** E2e tests for category: batch. */
class BatchTest {

    private static final ObjectMapper MAPPER = new ObjectMapper().registerModule(new Jdk8Module());
    @Test
    void testBatchBytesInvalidMime() throws Exception {
        // batch_extract_bytes_sync invalid MIME
        var result = Kreuzberg.batchExtractBytesSync(java.util.List.of("{\"data\":\"SGVsbG8=\",\"mime_type\":\"application/x-nonexistent\"}"), MAPPER.readValue("{}", ExtractionConfig.class));
    }

    @Test
    void testBatchFileAsyncBasic() throws Exception {
        // Extract text from multiple files asynchronously
        var result = Kreuzberg.extractFile("", null, MAPPER.readValue("{}", ExtractionConfig.class));
    }

    @Test
    void testBatchFileAsyncNotFound() throws Exception {
        // batch_extract_file async nonexistent
        var result = Kreuzberg.extractFile("", null, MAPPER.readValue("{}", ExtractionConfig.class));
    }

    @Test
    void testBatchFileNotFound() throws Exception {
        // batch_extract_file_sync nonexistent
        var result = Kreuzberg.extractFile("", null, MAPPER.readValue("{}", ExtractionConfig.class));
    }

    @Test
    void testBatchFilePartial() throws Exception {
        // batch_extract_file_sync mixed
        var result = Kreuzberg.extractFile("", null, MAPPER.readValue("{}", ExtractionConfig.class));
    }

    @Test
    void testBatchFileSyncBasic() throws Exception {
        // Extract text from multiple files synchronously
        var result = Kreuzberg.extractFile("", null, MAPPER.readValue("{}", ExtractionConfig.class));
    }

}
