// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:97b78fa85e1e541c2788dab5b952b8aff33ca7933967fb7bfe32fb625f459232
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import dev.kreuzberg.ExtractionConfig;

/** E2e tests for category: embeddings. */
class EmbeddingsTest {

    private static final ObjectMapper MAPPER = new ObjectMapper().registerModule(new Jdk8Module());
    @Test
    void testEmbeddingDisabled() {
        // Tests chunking without embeddings - chunks should not have embedding vectors
        org.junit.jupiter.api.Assumptions.assumeTrue(false, "TODO: implement Java e2e test for fixture 'embedding_disabled'");
    }

}
