# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:db56f0ce0a000b555819d230453fb860929a7292e30a8f2853bade55a8f9d9d8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
library(testthat)
devtools::load_all("../../packages/r")

test_dir("tests")
