# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f7e3593c7e1f97b9e55d8548b855f76e7faed2f9e30d9f2d80bc8d2fa358de84
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Kreuzberg
  VERSION = '5.0.0.pre.rc.3'
end
