# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0e501047a083299e63fec8ca8206545d30dfb68012bd6afd23a2d3ff92f58a25
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require_relative 'kreuzberg/version'
require_relative 'kreuzberg/native'

module Kreuzberg
  # Re-export all types and functions from native extension
end
