# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1162ab8382526036843e39b1b02e3dd7c5d97256d5c3fac0f0482557aecf1d53
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require_relative 'kreuzberg/version'
require_relative 'kreuzberg/native'

module Kreuzberg
  # Re-export all types and functions from native extension
end
