// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e96f4e327956e7adf956954678f8c76def6ec3b938d96fad244a45137f2cf9cd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Hardware acceleration configuration for ONNX Runtime models.
 *
 * Controls which execution provider (CPU, CoreML, CUDA, TensorRT) is used for inference in layout detection and
 * embedding generation.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class AccelerationConfigBuilder {

    private ExecutionProviderType provider = null;
    @JsonProperty("device_id")
    private int deviceId = 0;

    /** Sets the provider field. */
    public AccelerationConfigBuilder withProvider(final ExecutionProviderType value) {
        this.provider = value;
        return this;
    }

    /** Sets the deviceId field. */
    public AccelerationConfigBuilder withDeviceId(final int value) {
        this.deviceId = value;
        return this;
    }

    /** Builds the AccelerationConfig instance. */
    public AccelerationConfig build() {
        return new AccelerationConfig(provider, deviceId);
    }
}
