// DO NOT EDIT - auto-generated by alef
// alef:hash:afbeee64f84d010945684f515d9045be8198852d566bf830505c9eb260b3fa10
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
