// DO NOT EDIT - auto-generated by alef
// alef:hash:13ceed6851dfd55d6ea54537ba583040ee67c717141eb5bc1cad116ee9eea47a
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
