// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1af5e919ba2595e6628746af8c1dfa140042dfdb786f56c20e379ab4c4862a8b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

@JsonDeserialize(builder = CharShapeBuilder.class)
public record CharShape(boolean bold, boolean italic, boolean underline) {
    public static CharShapeBuilder builder() {
        return new CharShapeBuilder();
    }
}
