// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:47cd22bd6442af1cacb0c7365642998daa7c8f388416da06ef53db538efda47e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * JATS contributor with role.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ContributorRole(String name, @Nullable String role) {
}
