// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:410a72149865c8ef148a081e39ffbeef64e1f4d59893250a01b65d30f74f9b0c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * dBASE field information.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DbfFieldInfo(String name, @JsonProperty("field_type") String fieldType) {
}
