// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0b5e6ce96d7609d7a40282a20ec58701af1c0d24bb7db8a9aa4069429be3b915
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Request parameters for MIME type detection.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DetectMimeTypeParams(String path, @JsonProperty("use_content") boolean useContent) {
}
