// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9bb64edf76f3d09dd72e5be5f0870665c03fcadff2dc086d483f5df9102446e1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * OpenWebUI "Docling" engine response format.
 *
 * Returned by {@code POST /v1/convert/file} for docling-serve compatibility.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DoclingCompatResponse(String document, String status) {
}
