// DO NOT EDIT - auto-generated by alef
// alef:hash:3405c09294a07bd81ca5bdaa077dc348d9082981ec47967792fb7f1b29a7bed0
package dev.kreuzberg;

public class EmbeddingException extends KreuzbergErrorException {
    /** Creates a new EmbeddingException with the given message. */
    public EmbeddingException(final String message) {
        super(message);
    }

    /** Creates a new EmbeddingException with the given message and cause. */
    public EmbeddingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
