// DO NOT EDIT - auto-generated by alef
// alef:hash:3cc296b092f46b420827498b1dce934a5a5ee14dcf60c1802ad1f6820df24a7e
package dev.kreuzberg;

public class EmbeddingException extends KreuzbergErrorException {
    /** Creates a new EmbeddingException with the given message. */
    public EmbeddingException(final String message) {
        super(message);
    }

    /** Creates a new EmbeddingException with the given message and cause. */
    public EmbeddingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
