// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:843064b4ef6586e3f4e18314a7248c37c8ee85edaff2b2dad568f6b2d366044d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Footnote in Djot.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record Footnote(
    String label,
    @JsonInclude(JsonInclude.Include.NON_NULL) List<FormattedBlock> content
) {

    /**
     * Parse a {@code Footnote} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws RuntimeException if the JSON cannot be deserialised.
     */
    public static Footnote fromJson(String json) {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, Footnote.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse Footnote from JSON", e);
        }
    }
}
