// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:52d56e85c16917d02f54992d90392cbc0107522fd6e6b7684a4206a12052b343
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A single heading in the hierarchy.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record HeadingLevel(byte level, String text) {
}
