// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cca23b8c800993f993f05bd4ba3cb59929d322ed5805a308c37b11f3e2429d78
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

@JsonDeserialize(builder = HwpImageBuilder.class)
public record HwpImage(String name, byte[] data) {
    public static HwpImageBuilder builder() {
        return new HwpImageBuilder();
    }
}
