// DO NOT EDIT - auto-generated by alef
// alef:hash:77d39f9357557acd01519585867efb6fc81dabb2cfc68dbe43c0d235a1cc385b
package dev.kreuzberg;

public class ImageProcessingException extends KreuzbergErrorException {
    /** Creates a new ImageProcessingException with the given message. */
    public ImageProcessingException(final String message) {
        super(message);
    }

    /** Creates a new ImageProcessingException with the given message and cause. */
    public ImageProcessingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
