// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:830fb65dc486ba4e14979e374bfab14506603d4f5551e647b7237cd5808cd8c6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.jspecify.annotations.Nullable;

/**
 * Result of OCR extraction from an image with optional page tracking.
 */
public record ImageOcrResult(
    String content,
    @Nullable List<PageBoundary> boundaries,
    @Nullable @JsonProperty("page_contents") List<PageContent> pageContents
) {

    /**
     * Parse a {@code ImageOcrResult} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws RuntimeException if the JSON cannot be deserialised.
     */
    public static ImageOcrResult fromJson(String json) {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, ImageOcrResult.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse ImageOcrResult from JSON", e);
        }
    }
}
