// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a98095a4c5e2b8cfe39c069a2b257a29b728c52921a164058dd8f22d53439400
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Image element metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ImageMetadataType(String src, @Nullable String alt, @Nullable String title,
        @Nullable List<Integer> dimensions, @JsonProperty("image_type") ImageType imageType,
        @JsonInclude(JsonInclude.Include.NON_NULL) List<String> attributes) {

    /**
     * Parse a {@code ImageMetadataType} from a JSON string.
     *
     * @param json
     *            JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException
     *             if the JSON cannot be deserialised.
     */
    public static ImageMetadataType fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                    .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module()).findAndRegisterModules()
                    .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                    .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                    .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                    .readValue(json, ImageMetadataType.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse ImageMetadataType from JSON: " + e.getMessage(), e);
        }
    }
}
