// DO NOT EDIT - auto-generated by alef
// alef:hash:993b863fc7f6e7d9fe535e8ec568ee839fefe20c257f57128e6d970444617907
package dev.kreuzberg;

public class IoException extends KreuzbergErrorException {
    /** Creates a new IoException with the given message. */
    public IoException(final String message) {
        super(message);
    }

    /** Creates a new IoException with the given message and cause. */
    public IoException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
