// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ad4cad04aa330f7165d2f80dc7364c725243abc9f645eb9e9453ac39dcb4425d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Language detection configuration.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class LanguageDetectionConfigBuilder {

    private boolean enabled = true;
    @JsonProperty("min_confidence")
    private double minConfidence = 0.0;
    @JsonProperty("detect_multiple")
    private boolean detectMultiple = false;

    /** Sets the enabled field. */
    public LanguageDetectionConfigBuilder withEnabled(final boolean value) {
        this.enabled = value;
        return this;
    }

    /** Sets the minConfidence field. */
    public LanguageDetectionConfigBuilder withMinConfidence(final double value) {
        this.minConfidence = value;
        return this;
    }

    /** Sets the detectMultiple field. */
    public LanguageDetectionConfigBuilder withDetectMultiple(final boolean value) {
        this.detectMultiple = value;
        return this;
    }

    /** Builds the LanguageDetectionConfig instance. */
    public LanguageDetectionConfig build() {
        return new LanguageDetectionConfig(enabled, minConfidence, detectMultiple);
    }
}
