// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ad8365f5b3fcefeabf01acdc92ecf69f24cbe038c74b3e0abb2bc3bfc9e3ce41
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Link element metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record LinkMetadata(String href, String text, @Nullable String title,
        @JsonProperty("link_type") LinkType linkType, @JsonInclude(JsonInclude.Include.NON_NULL) List<String> rel,
        @JsonInclude(JsonInclude.Include.NON_NULL) List<String> attributes) {

    /**
     * Parse a {@code LinkMetadata} from a JSON string.
     *
     * @param json
     *            JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException
     *             if the JSON cannot be deserialised.
     */
    public static LinkMetadata fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                    .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module()).findAndRegisterModules()
                    .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                    .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                    .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                    .readValue(json, LinkMetadata.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse LinkMetadata from JSON: " + e.getMessage(), e);
        }
    }
}
