// DO NOT EDIT - auto-generated by alef
// alef:hash:bf87045f1639333e76eba42589cbaf2c2d2f2333ba3690d577a3d6d94b0594f1
package dev.kreuzberg;

public class LockPoisonedException extends KreuzbergErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
