// DO NOT EDIT - auto-generated by alef
// alef:hash:01878a4c32bc71f5eeec843ce59a4bf6772634a42cdf84da3875c131c0bc7989
package dev.kreuzberg;

public class LockPoisonedException extends KreuzbergErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
