// DO NOT EDIT - auto-generated by alef
// alef:hash:556b07a8c3e92c4abd9a0e11a16e77ae74012c20e58ba1f6296a39bef7d26909
package dev.kreuzberg;

public class MissingDependencyException extends KreuzbergErrorException {
    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
