// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4a1bfea1a240b425f0b98f0705fd030fdccb37d83cb71647388ca3a2783721b1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonPOJOBuilder(withPrefix = "with")
public class OcrCacheStatsBuilder {

    @JsonProperty("total_files")
    private long totalFiles = 0;
    @JsonProperty("total_size_mb")
    private double totalSizeMb = 0.0;

    /** Sets the totalFiles field. */
    public OcrCacheStatsBuilder withTotalFiles(final long value) {
        this.totalFiles = value;
        return this;
    }

    /** Sets the totalSizeMb field. */
    public OcrCacheStatsBuilder withTotalSizeMb(final double value) {
        this.totalSizeMb = value;
        return this;
    }

    /** Builds the OcrCacheStats instance. */
    public OcrCacheStats build() {
        return new OcrCacheStats(totalFiles, totalSizeMb);
    }
}
