// DO NOT EDIT - auto-generated by alef
// alef:hash:c1746444c2d354a5f319a0397c9e4602e2fd6361e94cdef88987730fec9dd88f
package dev.kreuzberg;

public class OcrException extends KreuzbergErrorException {
    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
