// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9919f224210489173c9bbec65c305a092121cab913db5df4075fb83b457639ef
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Bounding box for an OCR-detected table in pixel coordinates.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record OcrTableBoundingBox(int left, int top, int right, int bottom) {
}
