// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6e261d700a78d6f4a5116a1c3716148df3b888af03cfa187778408fc42908e4f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Document orientation detection result.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record OrientationResult(int degrees, float confidence) {

    /**
     * Parse a {@code OrientationResult} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws RuntimeException if the JSON cannot be deserialised.
     */
    public static OrientationResult fromJson(String json) {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, OrientationResult.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse OrientationResult from JSON", e);
        }
    }
}
