// DO NOT EDIT - auto-generated by alef
// alef:hash:cc590c3be96042712e7982ddc8e38becb1250e2a218e22270a54140271232e36
package dev.kreuzberg;

public class OtherException extends KreuzbergErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
