// DO NOT EDIT - auto-generated by alef
// alef:hash:0c8e41771cd04db3d8fa02a3c403d455691aa5eb36e7fe83f8f877e1cd474c59
package dev.kreuzberg;

public class OtherException extends KreuzbergErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
