// DO NOT EDIT - auto-generated by alef
// alef:hash:16e617abfe5c1cd1d686140877703807cc2ac5d91591134534c48f2d1c9de263
package dev.kreuzberg;

public class ParsingException extends KreuzbergErrorException {
    /** Creates a new ParsingException with the given message. */
    public ParsingException(final String message) {
        super(message);
    }

    /** Creates a new ParsingException with the given message and cause. */
    public ParsingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
