// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ef7f3349edd7efe3aa0849c16559a30a6b59702c8f5ef00e1117ce5f7f3ae4e2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Type of PDF annotation.
 */
public enum PdfAnnotationType {
    /** Sticky note / text annotation */
    Text("text"),
    /** Highlighted text region */
    Highlight("highlight"),
    /** Hyperlink annotation */
    Link("link"),
    /** Rubber stamp annotation */
    Stamp("stamp"),
    /** Underline text markup */
    Underline("underline"),
    /** Strikeout text markup */
    StrikeOut("strike_out"),
    /** Any other annotation type */
    Other("other");

    /** The string value. */
    private final String value;

    PdfAnnotationType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static PdfAnnotationType fromValue(final String value) {
        for (PdfAnnotationType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
