// DO NOT EDIT - auto-generated by alef
// alef:hash:e39183f129021765f27a1c617109e5db6708a450057654d4de77774f2dd39cd8
package dev.kreuzberg;

public class PluginException extends KreuzbergErrorException {
    /** Creates a new PluginException with the given message. */
    public PluginException(final String message) {
        super(message);
    }

    /** Creates a new PluginException with the given message and cause. */
    public PluginException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
