// DO NOT EDIT - auto-generated by alef
// alef:hash:c902206282b3411b82003d36454e103706c9bbf10c1cecb9f97922fc8487a8ed
package dev.kreuzberg;

public class PluginException extends KreuzbergErrorException {
    /** Creates a new PluginException with the given message. */
    public PluginException(final String message) {
        super(message);
    }

    /** Creates a new PluginException with the given message and cause. */
    public PluginException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
