// DO NOT EDIT - auto-generated by alef
// alef:hash:2f49dba352b4229bd319ef706c35dde7179e61e81127e775f8f479d591b1b92d
package dev.kreuzberg;

public class PluginException extends KreuzbergErrorException {
    /** Creates a new PluginException with the given message. */
    public PluginException(final String message) {
        super(message);
    }

    /** Creates a new PluginException with the given message and cause. */
    public PluginException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
