// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:71478465769bd3ee06a4383bc8192343139d40dcbf5411ad5cecca90de5bffb0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Processing stages for post-processors.
 *
 * Post-processors are executed in stage order (Early → Middle → Late). Use stages to control the order of
 * post-processing operations.
 */
public enum ProcessingStage {
    /** Early stage - foundational processing. */
    Early("early"),
    /** Middle stage - content transformation. */
    Middle("middle"),
    /** Late stage - final enrichment. */
    Late("late");

    /** The string value. */
    private final String value;

    ProcessingStage(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ProcessingStage fromValue(final String value) {
        for (ProcessingStage e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
