// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:775b092c9753e0bed0b95b1d3bd430815fbca1ae2f851048af660aa0c7a5f5ec
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Page Segmentation Mode for Tesseract OCR
 */
public enum PSMMode {
    OsdOnly("osdonly"), AutoOsd("autoosd"), AutoOnly("autoonly"), Auto("auto"), SingleColumn(
            "singlecolumn"), SingleBlockVertical("singleblockvertical"), SingleBlock("singleblock"), SingleLine(
                    "singleline"), SingleWord("singleword"), CircleWord("circleword"), SingleChar("singlechar");

    /** The string value. */
    private final String value;

    PSMMode(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static PSMMode fromValue(final String value) {
        for (PSMMode e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }
}
