// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:24ca79cee4f7b3c268a49bd6afc1428b17a46ccf0da31929ca2d9f38db9e0c9b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Outlook PST archive metadata.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class PstMetadataBuilder {

    @JsonProperty("message_count")
    private long messageCount = 0;

    /** Sets the messageCount field. */
    public PstMetadataBuilder withMessageCount(final long value) {
        this.messageCount = value;
        return this;
    }

    /** Builds the PstMetadata instance. */
    public PstMetadata build() {
        return new PstMetadata(messageCount);
    }
}
