// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d32db28d64b936779fc2e8965a7a862c67ab275d2ce305c7150ebe1e40d4d03d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Pre-computed table markdown for a table detection region.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record RecognizedTable(@JsonProperty("detection_bbox") BBox detectionBbox,
        @JsonInclude(JsonInclude.Include.NON_NULL) List<List<String>> cells, String markdown) {

    /**
     * Parse a {@code RecognizedTable} from a JSON string.
     *
     * @param json
     *            JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException
     *             if the JSON cannot be deserialised.
     */
    public static RecognizedTable fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                    .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module()).findAndRegisterModules()
                    .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                    .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                    .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                    .readValue(json, RecognizedTable.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse RecognizedTable from JSON: " + e.getMessage(), e);
        }
    }
}
