// DO NOT EDIT - auto-generated by alef
// alef:hash:052fc95861156bdb0d7932bc2b31c96f32fb46580d628d450f5429aa810f0073
package dev.kreuzberg;

public class SecurityException extends KreuzbergErrorException {
    /** Creates a new SecurityException with the given message. */
    public SecurityException(final String message) {
        super(message);
    }

    /** Creates a new SecurityException with the given message and cause. */
    public SecurityException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
