// DO NOT EDIT - auto-generated by alef
// alef:hash:d10eca1ff3b546db2e485642b90204797c529dc9a7eb5db8bdf23315c604fd51
package dev.kreuzberg;

public class SerializationException extends KreuzbergErrorException {
    /** Creates a new SerializationException with the given message. */
    public SerializationException(final String message) {
        super(message);
    }

    /** Creates a new SerializationException with the given message and cause. */
    public SerializationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
