// DO NOT EDIT - auto-generated by alef
// alef:hash:20a2ba0daf4dca6be0d3e6d86aa849217c266edce353540c848095f863a25c17
package dev.kreuzberg;

public class SerializationException extends KreuzbergErrorException {
    /** Creates a new SerializationException with the given message. */
    public SerializationException(final String message) {
        super(message);
    }

    /** Creates a new SerializationException with the given message and cause. */
    public SerializationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
