// DO NOT EDIT - auto-generated by alef
// alef:hash:803e12e695551bbd88137176150c69013cb8b1172b7bd1ce2f3b21e4422715ca
package dev.kreuzberg;

public class SerializationException extends KreuzbergErrorException {
    /** Creates a new SerializationException with the given message. */
    public SerializationException(final String message) {
        super(message);
    }

    /** Creates a new SerializationException with the given message and cause. */
    public SerializationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
