// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3254cd360298eb792255ae878dd55fbd7d506722806da74df3d55def5da6a498
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

public class StreamReader implements AutoCloseable {
    private final MemorySegment handle;

    StreamReader(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_STREAM_READER_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free StreamReader: " + e.getMessage(), e);
            }
        }
    }
}
