// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e4a54173909b0b9ad84afa24cd82b6b10c91ace6c7196be7b85611e42a35e161
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record StructuredDataResult(
    String content,
    String format,
    Map<String, String> metadata,
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("text_fields") List<String> textFields
) {

    /**
     * Parse a {@code StructuredDataResult} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws RuntimeException if the JSON cannot be deserialised.
     */
    public static StructuredDataResult fromJson(String json) {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, StructuredDataResult.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse StructuredDataResult from JSON", e);
        }
    }
}
