// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0684c082f6e5841c9b0b2e578b02452388577a1b92b1064facbcd5091c8b5b6e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Configuration for LLM-based structured data extraction.
 *
 * Sends extracted document content to a VLM with a JSON schema,
 * returning structured data that conforms to the schema.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record StructuredExtractionConfig(
    Object schema,
    @JsonProperty("schema_name") String schemaName,
    @Nullable @JsonProperty("schema_description") String schemaDescription,
    boolean strict,
    @Nullable String prompt,
    LlmConfig llm
) {

    /**
     * Parse a {@code StructuredExtractionConfig} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws RuntimeException if the JSON cannot be deserialised.
     */
    public static StructuredExtractionConfig fromJson(String json) {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, StructuredExtractionConfig.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse StructuredExtractionConfig from JSON", e);
        }
    }
}
