// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:33df270605d883f85586acbeb1ced71767b3466e4c993f684a35b078087596f1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * WASM-compatible Tesseract OCR backend.
 *
 * This backend uses direct FFI calls to Tesseract for WASM compatibility.
 * It does not depend on the OcrProcessor which requires full Tokio runtime.
 */
public class TesseractWasmBackend implements AutoCloseable {
    private final MemorySegment handle;

    TesseractWasmBackend(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_TESSERACT_WASM_BACKEND_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free TesseractWasmBackend: " + e.getMessage(), e);
            }
        }
    }
}
