// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:82e94accd3dbc11b6ca11520cb258919565db31cfba735d34a270d7a9909d3f4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Inline text annotation — byte-range based formatting and links.
 *
 * Annotations reference byte offsets into the node's text content,
 * enabling precise identification of formatted regions.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record TextAnnotation(int start, int end, AnnotationKind kind) {

    /**
     * Parse a {@code TextAnnotation} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws RuntimeException if the JSON cannot be deserialised.
     */
    public static TextAnnotation fromJson(String json) {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, TextAnnotation.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse TextAnnotation from JSON", e);
        }
    }
}
