// DO NOT EDIT - auto-generated by alef
// alef:hash:bf014d9bc6aafae6847fcb866d9400a67def5f21b059af49f34354f14a78484b
package dev.kreuzberg;

public class TimeoutException extends KreuzbergErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
