// DO NOT EDIT - auto-generated by alef
// alef:hash:01980d80527276b2015828cb2e74003dea056b729210b2d6ed58871e78277aa6
package dev.kreuzberg;

public class TimeoutException extends KreuzbergErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
