// DO NOT EDIT - auto-generated by alef
// alef:hash:0f8417c11aba26d0760973d21436d95caaed58cd98f7641ed2dbc2e3f624f129
package dev.kreuzberg;

public class TimeoutException extends KreuzbergErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
