// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e30e79551d576d468211adb94aaebfed03d129ce74d337c0c5ebd9801fae2be9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Token reduction configuration.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class TokenReductionOptionsBuilder {

    private String mode = "";
    @JsonProperty("preserve_important_words")
    private boolean preserveImportantWords = true;

    /** Sets the mode field. */
    public TokenReductionOptionsBuilder withMode(final String value) {
        this.mode = value;
        return this;
    }

    /** Sets the preserveImportantWords field. */
    public TokenReductionOptionsBuilder withPreserveImportantWords(final boolean value) {
        this.preserveImportantWords = value;
        return this;
    }

    /** Builds the TokenReductionOptions instance. */
    public TokenReductionOptions build() {
        return new TokenReductionOptions(mode, preserveImportantWords);
    }
}
