// DO NOT EDIT - auto-generated by alef
// alef:hash:df6eba2466d5b47f0ffd022cae29481924749b23ea968102f6053d050d8ee602
package dev.kreuzberg;

public class UnsupportedFormatException extends KreuzbergErrorException {
    /** Creates a new UnsupportedFormatException with the given message. */
    public UnsupportedFormatException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedFormatException with the given message and cause. */
    public UnsupportedFormatException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
