// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b1ac8b6489321061ce0c1d1e279151b77d866fbdc1f0542bc5887353e7f42f3a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * A URI extracted from a document.
 *
 * Represents any link, reference, or resource pointer found during extraction.
 * The {@code kind} field classifies the URI semantically, while {@code label} carries
 * optional human-readable display text.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record Uri(String url, @Nullable String label, @Nullable Integer page, UriKind kind) {

    /**
     * Parse a {@code Uri} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws RuntimeException if the JSON cannot be deserialised.
     */
    public static Uri fromJson(String json) {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, Uri.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse Uri from JSON", e);
        }
    }
}
