// DO NOT EDIT - auto-generated by alef
// alef:hash:99d62f952d2e4004a3a7bf6b05631f2f8edd7d45fb0a4b4cf2a6fa29f522c9d9
package dev.kreuzberg;

public class ValidationException extends KreuzbergErrorException {
    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
