// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a3c0b7a991ee453c39eb43b12ccffbed80d4527bb4ba1c9c19f597e3a771c609
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Cache warm response.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record WarmResponse(
    @JsonProperty("cache_dir") String cacheDir,
    @JsonInclude(JsonInclude.Include.NON_NULL) List<String> downloaded,
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("already_cached") List<String> alreadyCached
) {

    /**
     * Parse a {@code WarmResponse} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws RuntimeException if the JSON cannot be deserialised.
     */
    public static WarmResponse fromJson(String json) {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, WarmResponse.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse WarmResponse from JSON", e);
        }
    }
}
