// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a3cbfd7d099e52df2d478fd86b7871bac09c206cf903f054dba6d12b9b537d80
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * XML metadata extracted during XML parsing.
 *
 * Provides statistics about XML document structure.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = XmlMetadataBuilder.class)
public record XmlMetadata(
    @JsonProperty("element_count") long elementCount,
    @JsonInclude(JsonInclude.Include.NON_NULL) @JsonProperty("unique_elements") List<String> uniqueElements
) {
    public static XmlMetadataBuilder builder() {
        return new XmlMetadataBuilder();
    }

    /**
     * Parse a {@code XmlMetadata} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws RuntimeException if the JSON cannot be deserialised.
     */
    public static XmlMetadata fromJson(String json) {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, XmlMetadata.class);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse XmlMetadata from JSON", e);
        }
    }
}
