# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c2c5fb07a8376b2044f0cc75f31952d4b6a2cc86d931a436f0ea87a1f804f538
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.AccelerationConfig do
  @moduledoc "Hardware acceleration configuration for ONNX Runtime models."

  defstruct provider: :auto,
            device_id: 0
end
