# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9729ea3d4f7aa59252cc72c82db2e74cd62419b07bce32611ea9dce7a0960ed1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.AccelerationConfig do
  @moduledoc "Hardware acceleration configuration for ONNX Runtime models."

  defstruct provider: :auto,
            device_id: 0
end
