# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:278e6c65a49ceea336f3fc4b5498e1b2c6b5715d4097366a0b4b030bcce9cf72
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.AccelerationConfig do
  @moduledoc "Hardware acceleration configuration for ONNX Runtime models."

  defstruct provider: :auto,
            device_id: 0
end
