# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f85665d4cfc46b1ff98bf477d2a3d0b65f44bba7b07e5acf9d2d9706740379f7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.AnchorProperties do
  @moduledoc "Properties for anchored drawings."

  defstruct behind_doc: false,
            layout_in_cell: false,
            relative_height: 0,
            position_h: "",
            position_v: "",
            wrap_type: ""
end
