# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8b7dac22bc0ed1bab56523982a71323089eee2d26de9177d7bb8b571a7b30f48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ArchiveMetadata do
  @moduledoc "Archive (ZIP/TAR/7Z) metadata."

  defstruct format: "",
            file_count: 0,
            file_list: [],
            total_size: 0,
            compressed_size: 0
end
