# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f11b1d790a09107a6c03e7ab217603a535022caef5f8aaf686fca7ef0badef86
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ArchiveEntry do
  @moduledoc "A single file extracted from an archive."

  defstruct path: "",
            mime_type: "",
            result: nil
end
