# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2a72212be729c72e0eec8e93c4b8a304bb25a6e7c6e2870393371a8940240294
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ArchiveEntry do
  @moduledoc "A single file extracted from an archive."

  defstruct path: "",
            mime_type: "",
            result: nil
end
