# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fb794f5e812972c8c744d2b9592ada99f9f7f764766420eab55c1b90510510cf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BBox do
  @moduledoc "Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right."

  defstruct x1: 0.0,
            y1: 0.0,
            x2: 0.0,
            y2: 0.0
end
