# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4383b67bd9741db57839626c51e5fcfe4e3e9ec7a0aeeb5de462243f402d1338
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BBox do
  @moduledoc "Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right."

  defstruct x1: 0.0,
            y1: 0.0,
            x2: 0.0,
            y2: 0.0
end
