# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:96847b32d696460e9293390fe169a1c5fac0dae44e2f914037e7bd96e57602cd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BatchBytesItem do
  @moduledoc "Batch item for byte array extraction."

  defstruct content: "",
            mime_type: "",
            config: nil
end
