# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8cb621c3d28ec4a1755363c5a04e5d956a29fe0254be2e861fff5ae4c88a9e0c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BatchFileItem do
  @moduledoc "Batch item for file extraction."

  defstruct path: "",
            config: nil
end
