# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:65d0fc38dfb6d5cdf1086a5aedd054419d7c40343132d27721fb7b43424d02e5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CacheWarmParams do
  @moduledoc "Request parameters for cache warm (model download)."

  defstruct all_embeddings: false,
            embedding_model: nil
end
