# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ad17e1f0a3beb84ce285be650c1786484a2951b58804900fb6bc2d8b94113590
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CharShape do
  @moduledoc false

  defstruct bold: false,
            italic: false,
            underline: false
end
