# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:80604fb436798100f5c91dec6d2014e06aee98d7762e4454e54ae50e311b6b3a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CharShape do
  @moduledoc false

  defstruct bold: false,
            italic: false,
            underline: false
end
