# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cb5266e21a516266b32e7e470dc4a019bf193c23d297d806d4d5931d2c2b5fd0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CharShape do
  @moduledoc false

  defstruct bold: false,
            italic: false,
            underline: false
end
