# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dd22216c352366c8ab92332522b730a78bea270b18e63ca36a870fa2c50d61db
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkSizing do
  @moduledoc "How chunk size is measured."

  @type t :: term()

  @type characters :: :characters
  @type tokenizer :: %{type: :tokenizer, model: term(), cache_dir: term()}
end
