# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a811dcad8da1c939b97db2ad339c7a1f0ac4a1c2e1b6c01965e8e2d645e69242
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkSizing do
  @moduledoc "How chunk size is measured."

  @type t :: term()

  @type characters :: :characters
  @type tokenizer :: %{type: :tokenizer, model: term(), cache_dir: term()}
end
