# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc76a5fe5728e53a3f2f463e6c4d22bd2dd6bc6a0391a9789803aadc8ac40bd1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkingConfig do
  @moduledoc "Chunking configuration."

  defstruct max_characters: 1_000,
            overlap: 200,
            trim: true,
            chunker_type: :text,
            embedding: nil,
            preset: nil,
            sizing: :characters,
            prepend_heading_context: false,
            topic_threshold: nil
end
