# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5d5da1e5b625e8d60bdec1c4b134cca3ec94aa7a456bf7ff908ae9573be46053
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkingConfig do
  @moduledoc "Chunking configuration."

  defstruct max_characters: 1_000,
            overlap: 200,
            trim: true,
            chunker_type: :text,
            embedding: nil,
            preset: nil,
            sizing: :characters,
            prepend_heading_context: false,
            topic_threshold: nil
end
