# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:538e38e4b55dadef3338f46051c3b70b37cfec40e2cf0375e30b9439db5c2ace
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkMetadata do
  @moduledoc "Metadata about a chunk's position in the original document."

  defstruct byte_start: 0,
            byte_end: 0,
            token_count: nil,
            chunk_index: 0,
            total_chunks: 0,
            first_page: nil,
            last_page: nil,
            heading_context: nil
end
