# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:48c4f267a89cbbf7bc6ac83ab3a8d33a29f2cb3524ff314669aace15842a1b46
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Chunk do
  @moduledoc "A text chunk with optional embedding and metadata."

  defstruct content: "",
            chunk_type: :unknown,
            embedding: nil,
            metadata: nil
end
