# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:647415dc2472739a99f33e9b7be885b71cc30d2f97cd54964edb415e91bea617
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkTextParams do
  @moduledoc "Request parameters for text chunking."

  defstruct text: "",
            max_characters: nil,
            overlap: nil,
            chunker_type: nil,
            topic_threshold: nil
end
