# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:62423947466702226532119680be171895dcc25862f0b6299b907e6ef6566f14
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Chunk do
  @moduledoc "A text chunk with optional embedding and metadata."

  defstruct content: "",
            chunk_type: :unknown,
            embedding: nil,
            metadata: nil
end
