# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bccadd38d1c59cae3687e321b6cb68a615eeb3cc5b4ddf7f1648cd6a44f2d609
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkResponse do
  @moduledoc "Chunk response with chunks and metadata."

  defstruct chunks: [],
            chunk_count: 0,
            config: "",
            input_size_bytes: 0,
            chunker_type: ""
end
