# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1a1c861693e63f9a3f37e7396514ebeb9e409934cc4f7b8c6f2be746bd00b20c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkTextParams do
  @moduledoc "Request parameters for text chunking."

  defstruct text: "",
            max_characters: nil,
            overlap: nil,
            chunker_type: nil,
            topic_threshold: nil
end
