# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5e976b2da75e51515247409eb375d76712072f599c955e537c15369adbbfdaac
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Chunk do
  @moduledoc "A text chunk with optional embedding and metadata."

  defstruct content: "",
            chunk_type: :unknown,
            embedding: nil,
            metadata: nil
end
