# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:23dbe15b76464667811d927aa3ad368d00abba640e259206c619ef2636532a3b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkRequest do
  @moduledoc "Chunk request with text and configuration."

  defstruct text: "",
            config: nil,
            chunker_type: ""
end
