# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c96f6c35b8ce67010a21e16c1b27b1aa65a81ec66b1f0e6a7db621f44b103750
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CodeContentMode do
  @moduledoc "Content rendering mode for code extraction."

  @type t :: :chunks | :raw | :structure

  @chunks :chunks
  @raw :raw
  @structure :structure

  @spec chunks() :: t()
  def chunks, do: @chunks
  @spec raw() :: t()
  def raw, do: @raw
  @spec structure() :: t()
  def structure, do: @structure
end
