# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a6676ca3d83775a8bab2e552ad035e8c0f5eb0221717e2e65a79054af5731e0d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CodeContentMode do
  @moduledoc "Content rendering mode for code extraction."

  @type t :: :chunks | :raw | :structure

  @chunks :chunks
  @raw :raw
  @structure :structure

  @spec chunks() :: t()
  def chunks, do: @chunks
  @spec raw() :: t()
  def raw, do: @raw
  @spec structure() :: t()
  def structure, do: @structure
end
