# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:74356efcf693d44dd3cabeb36562dc1ede2d627272af01377888b3637ffbd592
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContentFilterConfig do
  @moduledoc "Cross-extractor content filtering configuration."

  defstruct include_headers: false,
            include_footers: false,
            strip_repeating_text: true,
            include_watermarks: false
end
