# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7de550249ad9aae15046417c27799a4bafbe90594ae51da48dcb72d8b31e22a8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContentFilterConfig do
  @moduledoc "Cross-extractor content filtering configuration."

  defstruct include_headers: false,
            include_footers: false,
            strip_repeating_text: true,
            include_watermarks: false
end
