# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1793608eae6faa35c9f1791e61c5fa3a6bd0830435e1cfe497e539a71ab9d86
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  defstruct name: "",
            role: nil
end
