# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8cc63df31eba4286cea0ad1bf5b95afc5b1046276a76078352811651f0cb0204
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  defstruct name: "",
            role: nil
end
