# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3d60ba377c16af3007931e3748fd07d2606f5946f1c651c64d915db96f375539
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CoreProperties do
  @moduledoc "Dublin Core metadata from docProps/core.xml"

  defstruct title: "",
            subject: "",
            creator: "",
            keywords: "",
            description: "",
            last_modified_by: "",
            revision: "",
            created: "",
            modified: "",
            category: "",
            content_status: "",
            language: "",
            identifier: "",
            version: "",
            last_printed: ""
end
