# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5a29e1670c3d4d4dae86c8fe95c2b30dd4ea9123e36b789acf79cbf14ae678a6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CoreProperties do
  @moduledoc "Dublin Core metadata from docProps/core.xml"

  defstruct title: "",
            subject: "",
            creator: "",
            keywords: "",
            description: "",
            last_modified_by: "",
            revision: "",
            created: "",
            modified: "",
            category: "",
            content_status: "",
            language: "",
            identifier: "",
            version: "",
            last_printed: ""
end
