# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:14c9479390da180f6456d2f18c223edbd2b19b34a08e4715032925ae6e1d3762
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CsvMetadata do
  @moduledoc "CSV/TSV file metadata."

  defstruct row_count: 0,
            column_count: 0,
            delimiter: "",
            has_header: false,
            column_types: []
end
