# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c5de8c5c062be0b5efc14465c08c88afffd14a2a8b6b36e8d0ca42513293e46
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CsvMetadata do
  @moduledoc "CSV/TSV file metadata."

  defstruct row_count: 0,
            column_count: 0,
            delimiter: "",
            has_header: false,
            column_types: []
end
