# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4762e683e3784efe4299cb354b030013383df3d289a3e52a36c1a53730c64f0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  defstruct name: "",
            field_type: ""
end
