# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:46b588a411e397beb8586f9e5120f35292d190fe9e1a05f2bdda8010e353c798
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  defstruct name: "",
            field_type: ""
end
