# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:895ce9cd35d84e3625194fdb44eb1e8705e1527610fabd605e81b91536d4fe67
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfMetadata do
  @moduledoc "dBASE (DBF) file metadata."

  defstruct record_count: 0,
            field_count: 0,
            fields: []
end
