# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:68532fab77717f7e85179ab09a522cf3afebc234dd9b530a482dbd81daad96b4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectMimeTypeParams do
  @moduledoc "Request parameters for MIME type detection."

  defstruct path: "",
            use_content: false
end
