# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:545db28aa320de31d3a5109166050f51e1b189190882853667ab0f94aff29d0d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectedBoundary do
  @moduledoc "A detected structural boundary in the text."

  defstruct byte_offset: 0,
            is_header: false
end
