# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:16506caeb3e702e97e52d32ccdbe268cc6a395f52f1cd11d1d5047fe2b2661f0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectedBoundary do
  @moduledoc "A detected structural boundary in the text."

  defstruct byte_offset: 0,
            is_header: false
end
