# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1c562f4cf9ff7fb76a3c5318f6310477f37c7cd8e9b11bd7ffcaa8f85c62f198
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectMimeTypeParams do
  @moduledoc "Request parameters for MIME type detection."

  defstruct path: "",
            use_content: false
end
