# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fa140f68b20259ebd1fd92cc00bab6431ebe7c6b613b05584e934bf19ac7ae65
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectResponse do
  @moduledoc "MIME type detection response."

  defstruct mime_type: "",
            filename: nil
end
