# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:196d1182e165a337d764f0840b3da80d35e38ae45c010687c013e17194e55f1b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotLink do
  @moduledoc "Link element in Djot."

  defstruct url: "",
            text: "",
            title: nil,
            attributes: nil
end
