# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7bd4dc9878fb949a7a7a3feabef80e3e89288c5c37ef5acd90fa70f7238d39b7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotContent do
  @moduledoc "Comprehensive Djot document structure with semantic preservation."

  defstruct plain_text: "",
            blocks: [],
            metadata: nil,
            tables: [],
            images: [],
            links: [],
            footnotes: [],
            attributes: []
end
