# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c8828cc4f7c00a4459635ba9b0f9683d8ccb29a6ad803ae95e13b7f4d6b01f9a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotContent do
  @moduledoc "Comprehensive Djot document structure with semantic preservation."

  defstruct plain_text: "",
            blocks: [],
            metadata: nil,
            tables: [],
            images: [],
            links: [],
            footnotes: [],
            attributes: []
end
