# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1e9413018e4f0842b84e1a1872ef7409d0139582cb9ad7a21567127adea20c51
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DoclingCompatResponse do
  @moduledoc "OpenWebUI \"Docling\" engine response format."

  defstruct document: "",
            status: ""
end
