# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4fa02d82d41250d83647dfd506fc4829b125ebb2d0ddd73d85705b684503d99f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentStructure do
  @moduledoc "Top-level structured document representation."

  defstruct nodes: [],
            source_format: "",
            relationships: [],
            node_types: []
end
