# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1cd491c7c0ac6e1a15684bfcac7e730636ceeef046e626ea98b2a5f8a2837f0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentRelationship do
  @moduledoc "A resolved relationship between two nodes in the document tree."

  defstruct source: 0,
            target: 0,
            kind: :footnote_reference
end
