# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:db32217ce2101a9a13cfde9c4b27ed98077d8051d04e1d4f9abfa25d16aa273d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentNode do
  @moduledoc "A single node in the document tree."

  defstruct id: "",
            content: :title,
            parent: nil,
            children: [],
            content_layer: :body,
            page: nil,
            page_end: nil,
            bbox: nil,
            annotations: [],
            attributes: nil
end
