# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9733497c31107d273769dde49dcc7c72fa6aded0fe0cbb8d3f2f5fc3ae1273a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentStructure do
  @moduledoc "Top-level structured document representation."

  defstruct nodes: [],
            source_format: "",
            relationships: [],
            node_types: []
end
