# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2631e5585bc50635ae17a093582dcdad026b4c57bdb58a96cdc4ba816e4dcab9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocxMetadata do
  @moduledoc "Word document metadata."

  defstruct core_properties: nil,
            app_properties: nil,
            custom_properties: %{}
end
