# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:83d2dabccdb8e239a93fd205c0558ce40f0bdac29a302c03e4d490424b825954
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocxMetadata do
  @moduledoc "Word document metadata."

  defstruct core_properties: nil,
            app_properties: nil,
            custom_properties: %{}
end
