# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:35d79939218d7b5a45d78f778be0fe7b4b86469125510416fa04a693c9e3575b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Drawing do
  @moduledoc "A drawing object extracted from `<w:drawing>`."

  defstruct drawing_type: "",
            extent: "",
            doc_properties: "",
            image_ref: ""
end
