# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4872cd5bc4f024238e78b9be457a3c87921d4636cea1d8086cbedb661246f5be
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Drawing do
  @moduledoc "A drawing object extracted from `<w:drawing>`."

  defstruct drawing_type: "",
            extent: "",
            doc_properties: "",
            image_ref: ""
end
