# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:18053264d0a1dd1c83a18a1c1b3a07df3276dc9bd7887d8b1ae39f47c9d272df
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Element do
  @moduledoc "Semantic element extracted from document."

  defstruct element_id: "",
            element_type: :title,
            text: "",
            metadata: nil
end
