# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5ccd616e674d11ea9044291acb3479fc6fdbb035954bcac6b35387d1b0cb4f0c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ElementMetadata do
  @moduledoc "Metadata for a semantic element."

  defstruct page_number: nil,
            filename: nil,
            coordinates: nil,
            element_index: nil,
            additional: %{}
end
