# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c013f04bd9c81ea98b4b80d16ad05b60feca25417a2024560c93cbe5d6a89052
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ElementMetadata do
  @moduledoc "Metadata for a semantic element."

  defstruct page_number: nil,
            filename: nil,
            coordinates: nil,
            element_index: nil,
            additional: %{}
end
