# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bc14226e3d21998eb0e3edc3f228a85feaf304d8c303a9f0309c7c1d0f044cee
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailAttachment do
  @moduledoc "Email attachment representation."

  defstruct name: nil,
            filename: nil,
            mime_type: nil,
            size: nil,
            is_image: false,
            data: nil
end
