# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:28684d824ea886b2cda08b7878ad52dab045c871bde89e5769c7cbb97293b995
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailAttachment do
  @moduledoc "Email attachment representation."

  defstruct name: nil,
            filename: nil,
            mime_type: nil,
            size: nil,
            is_image: false,
            data: nil
end
