# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:26ddcb081001208540d5c36e0b1a0249084d91785505d33d32e9192c210a0bf9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailMetadata do
  @moduledoc "Email metadata extracted from .eml and .msg files."

  defstruct from_email: "",
            from_name: "",
            to_emails: [],
            cc_emails: [],
            bcc_emails: [],
            message_id: "",
            attachments: []
end
