# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ce7af9ada8a45091479fbdedee610ddd4f1cfb98268b6c07994401a19c2ab425
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailMetadata do
  @moduledoc "Email metadata extracted from .eml and .msg files."

  defstruct from_email: "",
            from_name: "",
            to_emails: [],
            cc_emails: [],
            bcc_emails: [],
            message_id: "",
            attachments: []
end
