# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a6c32050840f3e03a4e6b71e0933a8c08c788aa2dcaeaf4718bfd8974e326849
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailAttachment do
  @moduledoc "Email attachment representation."

  defstruct name: nil,
            filename: nil,
            mime_type: nil,
            size: nil,
            is_image: false,
            data: nil
end
