# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:064e9047aeb9f9de03fd50ee4ef650dfa1db9fab10f8300d313863952d85ccd4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailConfig do
  @moduledoc "Configuration for email extraction."

  defstruct msg_fallback_codepage: 0
end
