# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e7156e464a404923050c1f989eced148313fca32e41a0481f2331c9e543d57d0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddingModelType do
  @moduledoc "Embedding model types supported by Kreuzberg."

  @type t :: term()

  @type preset :: %{type: :preset, name: term()}
  @type custom :: %{type: :custom, model_id: term(), dimensions: term()}
  @type llm :: %{type: :llm, llm: term()}
  @type plugin :: %{type: :plugin, name: term()}
end
