# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f8db2710ca21dd1d3328345b9234d167b3b6484ab9e5346e9350bb301a36871e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddingConfig do
  @moduledoc "Embedding configuration for text chunks."

  defstruct model: :preset,
            normalize: true,
            batch_size: 32,
            show_download_progress: false,
            cache_dir: nil,
            acceleration: nil,
            max_embed_duration_secs: 0
end
