# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:be9ec6d337f78416e4c60e107f33edee947f9599fcc64bddf72944ba1e70122d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedResponse do
  @moduledoc "Embedding response containing generated embeddings."

  defstruct embeddings: [],
            model: "",
            dimensions: 0,
            count: 0
end
