# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ee5aee502c1694e96237132a46699b05b2e65553d2e59117f21b9897b3d1a0f8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedResponse do
  @moduledoc "Embedding response containing generated embeddings."

  defstruct embeddings: [],
            model: "",
            dimensions: 0,
            count: 0
end
