# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:98506bc1a8e5b3462ab7a5dc943de55966bdaeb22580363fe227471290436133
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddingConfig do
  @moduledoc "Embedding configuration for text chunks."

  defstruct model: :preset,
            normalize: true,
            batch_size: 32,
            show_download_progress: false,
            cache_dir: nil,
            acceleration: nil,
            max_embed_duration_secs: 0
end
