# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:48cb27f4d8864aad5c2f067b2c77ce5ca5b580bf8e310d9377e843c389290000
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  defstruct name: "",
            data: "",
            mime_type: nil
end
