# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c10c73d8f3a5035ea594ac73ef19a053f31b95d86120710fc24da8e9920c11d0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  defstruct name: "",
            data: "",
            mime_type: nil
end
