# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d3cbbe7f00f33c66f532ff6aa60531fd502bfd677766c7da6dd3097521cb09b4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedRequest do
  @moduledoc "Embedding request for generating embeddings from text."

  defstruct texts: [],
            config: nil
end
