# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:64b783eb2b7eb5ad517be03550d7fe59b3f7c90a65b4ef60a1f82568c759757a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  defstruct name: "",
            data: "",
            mime_type: nil
end
