# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:98d9cc20721876ca48cb17fe3af912f0de79425005d92ed12640a963818fd72f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddingModelType do
  @moduledoc "Embedding model types supported by Kreuzberg."

  @type t :: term()

  @type preset :: %{type: :preset, name: term()}
  @type custom :: %{type: :custom, model_id: term(), dimensions: term()}
  @type llm :: %{type: :llm, llm: term()}
  @type plugin :: %{type: :plugin, name: term()}
end
