# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ea05ef0264676a2f2b462de5d941f9798af4f1bebd2ac7d25d14445c5a28b5d3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddingPreset do
  @moduledoc "Preset configurations for common RAG use cases."

  defstruct name: "",
            chunk_size: 0,
            overlap: 0,
            model_repo: "",
            pooling: "",
            model_file: "",
            dimensions: 0,
            description: ""
end
