# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4c33991c90743d6fdcf3bbe9d28ad1fc4d73bd686436e32aa324f71b99d3aa6d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EpubMetadata do
  @moduledoc "EPUB metadata (Dublin Core extensions)."

  defstruct coverage: "",
            dc_format: "",
            relation: "",
            source: "",
            dc_type: "",
            cover_image: ""
end
