# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:879234dc8b3b805988778423502175526a035a23334bf79538dd39c4b5e144ce
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EpubMetadata do
  @moduledoc "EPUB metadata (Dublin Core extensions)."

  defstruct coverage: "",
            dc_format: "",
            relation: "",
            source: "",
            dc_type: "",
            cover_image: ""
end
