# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:189087095b624ab200a14d72a3f98899caf5cc3ab0d7ffa26e62392121f1f04e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelWorkbook do
  @moduledoc "Excel workbook representation."

  defstruct sheets: [],
            metadata: %{}
end
