# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31c9f3bb5cf778f9d0fb4f697e2d1aed1bbb050c10c4e3d19049e0f479f6ca1a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelWorkbook do
  @moduledoc "Excel workbook representation."

  defstruct sheets: [],
            metadata: %{}
end
