# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d2a8159b39a3c1ec1f37da7cceaa2da33ab341e69f658a6b5429aa4424fccdc1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelSheet do
  @moduledoc "Single Excel worksheet."

  defstruct name: "",
            markdown: "",
            row_count: 0,
            col_count: 0,
            cell_count: 0,
            table_cells: nil
end
