# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1b5fc701887ac1609668ba39072a48393609457069ef6bbb83c58bf9b18b46f5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelWorkbook do
  @moduledoc "Excel workbook representation."

  defstruct sheets: [],
            metadata: %{}
end
