# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1dd537a89578c040444d98d5e1a14b72185192c76531ab7e0fec78854b20322e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractedImage do
  @moduledoc "Extracted image from a document."

  defstruct data: "",
            format: "",
            image_index: 0,
            page_number: nil,
            width: nil,
            height: nil,
            colorspace: nil,
            bits_per_component: nil,
            is_mask: false,
            description: nil,
            ocr_result: nil,
            bounding_box: nil,
            source_path: nil,
            image_kind: nil,
            kind_confidence: nil,
            cluster_id: nil
end
