# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:197829f3f1d913769ba666e70722dcb9b105baecd393ef17ce720ec192b9a9f3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractionMethod do
  @moduledoc "How the extracted text was produced."

  @type t :: :native | :ocr | :mixed

  @native :native
  @ocr :ocr
  @mixed :mixed

  @spec native() :: t()
  def native, do: @native
  @spec ocr() :: t()
  def ocr, do: @ocr
  @spec mixed() :: t()
  def mixed, do: @mixed
end
