# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a2973f499d137e6c308c49a29d0da4c701ec88755c39a23bf9ea672c23828f56
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractStructuredParams do
  @moduledoc "Request parameters for LLM-based structured extraction."

  defstruct path: "",
            schema: "",
            model: "",
            schema_name: "",
            schema_description: nil,
            prompt: nil,
            api_key: nil,
            strict: false
end
