# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:67251adc553120fafd8780298a50d0c01b908ea47da5986546782f8aa2c968e8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractionMethod do
  @moduledoc "How the extracted text was produced."

  @type t :: :native | :ocr | :mixed

  @native :native
  @ocr :ocr
  @mixed :mixed

  @spec native() :: t()
  def native, do: @native
  @spec ocr() :: t()
  def ocr, do: @ocr
  @spec mixed() :: t()
  def mixed, do: @mixed
end
