# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ca644e8928c27dff502c39e843a1acbb502b632dee19ef7dfd397a963440befd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractedInlineImage do
  @moduledoc "Extracted inline image with metadata."

  defstruct data: "",
            format: "",
            filename: nil,
            description: nil,
            dimensions: nil,
            attributes: []
end
