# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d87651ee03455172378a2a9186e55d725679afe40593049111ab8cd35999211d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FictionBookMetadata do
  @moduledoc "FictionBook (FB2) metadata."

  defstruct genres: [],
            sequences: [],
            annotation: ""
end
