# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7434f2629a5bbf76993c4158331dd6c4b864dc9c8341596951de0e316d4cb158
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FictionBookMetadata do
  @moduledoc "FictionBook (FB2) metadata."

  defstruct genres: [],
            sequences: [],
            annotation: ""
end
