# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a8ed655e65090246603e0dffab1f439d4b9fab98a0866fbb8e13d02d7b4a5fad
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FictionBookMetadata do
  @moduledoc "FictionBook (FB2) metadata."

  defstruct genres: [],
            sequences: [],
            annotation: ""
end
