# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e2f5c4969ebee6cbe328ab31c496a722e3d3d34f259823b4d1f56bb82e356214
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Footnote do
  @moduledoc "Footnote in Djot."

  defstruct label: "",
            content: []
end
