# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:81c9c147304f98d8c4ac12b9e8dff9b4917fe55bffff40b12a77dc9027ab9170
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Footnote do
  @moduledoc "Footnote in Djot."

  defstruct label: "",
            content: []
end
