# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c96acb6d53ca1712631af249c2f817a00456ab8ff0b962a0728ad67ba1fbff94
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Footnote do
  @moduledoc "Footnote in Djot."

  defstruct label: "",
            content: []
end
