# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aa95a3db97c57c7e7259054f004c8ef3b92609bff0e3a0eec592a3cfc5f78892
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FormattedBlock do
  @moduledoc "Block-level element in a Djot document."

  defstruct block_type: :paragraph,
            level: nil,
            inline_content: [],
            attributes: nil,
            language: nil,
            code: nil,
            children: []
end
