# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4299e808b82f30f404974e8b21c8d34153551fa976c005b9b2009267ef1c6c5e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FormattedBlock do
  @moduledoc "Block-level element in a Djot document."

  defstruct block_type: :paragraph,
            level: nil,
            inline_content: [],
            attributes: nil,
            language: nil,
            code: nil,
            children: []
end
