# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7f874dbb8d9f4997f0c0fd296ff7dea65e2ab457234df46136deabb827e2863d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.GridCell do
  @moduledoc "Individual grid cell with position and span metadata."

  defstruct content: "",
            row: 0,
            col: 0,
            row_span: 0,
            col_span: 0,
            is_header: false,
            bbox: nil
end
