# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1d9ff6c243524dcfb858aff03db355e1f19b6bf49f6ef55d07698eee177d20ac
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.GridCell do
  @moduledoc "Individual grid cell with position and span metadata."

  defstruct content: "",
            row: 0,
            col: 0,
            row_span: 0,
            col_span: 0,
            is_header: false,
            bbox: nil
end
