# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0ef32db8b8f1772f3d2f1721397df7a6ebf45f6a79df9a141405769f57d33226
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingLevel do
  @moduledoc "A single heading in the hierarchy."

  defstruct level: 0,
            text: ""
end
