# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2b7475b474370b8c5f29a78033f94a1640afdf23a9dcdeb75a33404764adafbe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingLevel do
  @moduledoc "A single heading in the hierarchy."

  defstruct level: 0,
            text: ""
end
