# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4180536d15adee8e841f0d8b34dad330b1292e038bf633e7ecf157fc8c3b0a5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeaderMetadata do
  @moduledoc "Header/heading element metadata."

  defstruct level: 0,
            text: "",
            id: nil,
            depth: 0,
            html_offset: 0
end
