# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1de5cf7787498a790b6faff0eb941fe3677231450397b454a0ffb2573e52fe68
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeaderMetadata do
  @moduledoc "Header/heading element metadata."

  defstruct level: 0,
            text: "",
            id: nil,
            depth: 0,
            html_offset: 0
end
