# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4e80451a6225d67e619940c81c12983259dab4bada4880fdf2cebc628b96ae25
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingContext do
  @moduledoc "Heading context for a chunk within a Markdown document."

  defstruct headings: []
end
