# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:49be68e6bc60cfd5602b1f207251c8b9c64d313b97b35fcccf08554f58bf66e8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingLevel do
  @moduledoc "A single heading in the hierarchy."

  defstruct level: 0,
            text: ""
end
