# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3bc2b553db1d3d9833847b6b3a762a3e6058c15e25cb962024543f725efe0f2b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HierarchyConfig do
  @moduledoc "Hierarchy extraction configuration for PDF text structure analysis."

  defstruct enabled: true,
            k_clusters: 3,
            include_bbox: true,
            ocr_coverage_threshold: nil
end
