# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:883262e9f7f9f4b41547e710f92f9770d017376c355ebcbd2ec51f130b7577a2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HierarchicalBlock do
  @moduledoc "A text block with hierarchy level assignment."

  defstruct text: "",
            font_size: 0.0,
            level: "",
            bbox: nil
end
