# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7edf870914e03990907e5fbcbf063d6d4c22fe4cfa491febebb1e3423fc404e6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HierarchicalBlock do
  @moduledoc "A text block with hierarchy level assignment."

  defstruct text: "",
            font_size: 0.0,
            level: "",
            bbox: nil
end
