# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5a56cda654f3aa6c704258473ed3ecf21623dd0fd8b4e6c3927d80c17be5c6d7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HierarchyConfig do
  @moduledoc "Hierarchy extraction configuration for PDF text structure analysis."

  defstruct enabled: true,
            k_clusters: 3,
            include_bbox: true,
            ocr_coverage_threshold: nil
end
