# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:452a64744921fb6cd20eb3f2578aadab887217ca60c0c0fee86a057243ae2319
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HtmlOutputConfig do
  @moduledoc "Configuration for styled HTML output."

  defstruct css: nil,
            css_file: nil,
            theme: :unstyled,
            class_prefix: "",
            embed_css: true
end
