# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f3dad9547cc75fe6a6931e21052549401e0c158faeebfae3baff313e25ffd559
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HtmlMetadata do
  @moduledoc "HTML metadata extracted from HTML documents."

  defstruct title: "",
            description: "",
            keywords: [],
            author: "",
            canonical_url: "",
            base_href: "",
            language: "",
            text_direction: :left_to_right,
            open_graph: %{},
            twitter_card: %{},
            meta_tags: %{},
            headers: [],
            links: [],
            images: [],
            structured_data: []
end
