# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b4e06724a17ca4209a0d83c070a86e3fe8f8f24fe72bb66474116525b1e34946
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HtmlTheme do
  @moduledoc "Built-in HTML theme selection."

  @type t :: :default | :git_hub | :dark | :light | :unstyled

  @default :default
  @git_hub :git_hub
  @dark :dark
  @light :light
  @unstyled :unstyled

  @spec default() :: t()
  def default, do: @default
  @spec git_hub() :: t()
  def git_hub, do: @git_hub
  @spec dark() :: t()
  def dark, do: @dark
  @spec light() :: t()
  def light, do: @light
  @spec unstyled() :: t()
  def unstyled, do: @unstyled
end
