# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7496d5f6429aa41b837e651bbcfa246d889642be449f8ab87b0435313d56ce0c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HtmlOutputConfig do
  @moduledoc "Configuration for styled HTML output."

  defstruct css: nil,
            css_file: nil,
            theme: :unstyled,
            class_prefix: "",
            embed_css: true
end
