# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6b841f83f236869e8a8edebaa7740ac2958c126e5c6d16eddcb99b77dfb76a95
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HtmlTheme do
  @moduledoc "Built-in HTML theme selection."

  @type t :: :default | :git_hub | :dark | :light | :unstyled

  @default :default
  @git_hub :git_hub
  @dark :dark
  @light :light
  @unstyled :unstyled

  @spec default() :: t()
  def default, do: @default
  @spec git_hub() :: t()
  def git_hub, do: @git_hub
  @spec dark() :: t()
  def dark, do: @dark
  @spec light() :: t()
  def light, do: @light
  @spec unstyled() :: t()
  def unstyled, do: @unstyled
end
