# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5921f49c9ca35a545d560658e99b5cdeb7b5ef21bcac0204523a12007bfa8b43
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HwpImage do
  @moduledoc false

  defstruct name: "",
            data: ""
end
