# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:938058a555635bc60174a62d79cb5e974618c0237be920a983a002a37efe9ae4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HwpImage do
  @moduledoc false

  defstruct name: "",
            data: ""
end
