# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:67a27cfad126f576d9513b8993ef23d67bdf0e136270c7cbcda0a5d591c24f9b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HwpImage do
  @moduledoc false

  defstruct name: "",
            data: ""
end
