# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5bf6999b4c3de56f8626f49b68de575e8783b6b55ce7d24d2ea6cc3861a2b923
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImageMetadataType do
  @moduledoc "Image element metadata."

  defstruct src: "",
            alt: nil,
            title: nil,
            dimensions: nil,
            image_type: :data_uri,
            attributes: []
end
