# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:75ad84531f059c5bc24fc1d0e8dac4114dabd91d418b91d3950105aba9fb571b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImagePreprocessingMetadata do
  @moduledoc "Image preprocessing metadata."

  defstruct original_dimensions: [],
            original_dpi: [],
            target_dpi: 0,
            scale_factor: 0.0,
            auto_adjusted: false,
            final_dpi: 0,
            new_dimensions: nil,
            resample_method: "",
            dimension_clamped: false,
            calculated_dpi: nil,
            skipped_resize: false,
            resize_error: nil
end
