# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fd480a4aa8a68bc4cbd18f2e87f5ac2a0969e23c21188104f9cfb1e763e4b9b0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImageType do
  @moduledoc "Image type classification."

  @type t :: :data_uri | :inline_svg | :external | :relative

  @data_uri :data_uri
  @inline_svg :inline_svg
  @external :external
  @relative :relative

  @spec data_uri() :: t()
  def data_uri, do: @data_uri
  @spec inline_svg() :: t()
  def inline_svg, do: @inline_svg
  @spec external() :: t()
  def external, do: @external
  @spec relative() :: t()
  def relative, do: @relative
end
