# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c35fdbb45e5f7e0be9d415d6fec245bbb7268b28876c161e6c54243c3448eefd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImagePreprocessingConfig do
  @moduledoc "Image preprocessing configuration for OCR."

  defstruct target_dpi: 300,
            auto_rotate: true,
            deskew: true,
            denoise: false,
            contrast_enhance: false,
            binarization_method: "otsu",
            invert_colors: false
end
