# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:87129fad4e9986a2d2a9d72f1775e3054f365ab38d745b2e0034d7b40088aa2d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImagePreprocessingMetadata do
  @moduledoc "Image preprocessing metadata."

  defstruct original_dimensions: [],
            original_dpi: [],
            target_dpi: 0,
            scale_factor: 0.0,
            auto_adjusted: false,
            final_dpi: 0,
            new_dimensions: nil,
            resample_method: "",
            dimension_clamped: false,
            calculated_dpi: nil,
            skipped_resize: false,
            resize_error: nil
end
