# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c4239923845bb6689f6e61f2fdae33e5c1334d4c8613333a802fe91d75ca650
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImagePreprocessingConfig do
  @moduledoc "Image preprocessing configuration for OCR."

  defstruct target_dpi: 300,
            auto_rotate: true,
            deskew: true,
            denoise: false,
            contrast_enhance: false,
            binarization_method: "otsu",
            invert_colors: false
end
