# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:aef8f9efbff688eec12b6b9373ddc294522cb9f8cf63c736ebf752079493c307
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImageMetadata do
  @moduledoc "Image metadata extracted from image files."

  defstruct width: 0,
            height: 0,
            format: "",
            exif: %{}
end
