# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9798a7153a167d0ce41e847e9cd151207f1cf788bb9bc7beb43c542f607f2d05
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImageMetadataType do
  @moduledoc "Image element metadata."

  defstruct src: "",
            alt: nil,
            title: nil,
            dimensions: nil,
            image_type: :data_uri,
            attributes: []
end
