# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e76f232fd7f9ff48f95554ec5a1103de020af02544da26d547938b969d16ab85
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.InfoResponse do
  @moduledoc "Server information response."

  defstruct version: "",
            rust_backend: false
end
