# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1e7b16ebab2a647d7e5e5704e79844b73bac778086e31c4ffa53aef286c0cf07
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.InlineElement do
  @moduledoc "Inline element within a block."

  defstruct element_type: :text,
            content: "",
            attributes: nil,
            metadata: nil
end
