# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0408a931b16645a2e249fa8973bfc7df1f72eac1145a477e14abd33849572c15
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.InlineElement do
  @moduledoc "Inline element within a block."

  defstruct element_type: :text,
            content: "",
            attributes: nil,
            metadata: nil
end
