# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:061f94d60ec4cdc2df49b172b3cfee90b81eb57de97e1b2423c6c7d846c26c94
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.JatsMetadata do
  @moduledoc "JATS (Journal Article Tag Suite) metadata."

  defstruct copyright: "",
            license: "",
            history_dates: %{},
            contributor_roles: []
end
