# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e0bd2522925482c69c0ab75b08b631b85c5c53cd5d936f44597a8211097f5db8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.JatsMetadata do
  @moduledoc "JATS (Journal Article Tag Suite) metadata."

  defstruct copyright: "",
            license: "",
            history_dates: %{},
            contributor_roles: []
end
