# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e540fcb4ece6fe9d99d64ca9dda1c82bd68b585670d8d11bc581e1b555c6b1bb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.JatsMetadata do
  @moduledoc "JATS (Journal Article Tag Suite) metadata."

  defstruct copyright: "",
            license: "",
            history_dates: %{},
            contributor_roles: []
end
