# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5369ce8898de21b9d3d7793b7320983e9fde8bbedeea216ba373e75567bb78fe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.KeywordAlgorithm do
  @moduledoc "Keyword algorithm selection."

  @type t :: :yake | :rake

  @yake :yake
  @rake :rake

  @spec yake() :: t()
  def yake, do: @yake
  @spec rake() :: t()
  def rake, do: @rake
end
