# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f407e3dd87941985e3ed59574abe971ae4ce86517cc04d1a9d6c8a92fc834013
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.KeywordConfig do
  @moduledoc "Keyword extraction configuration."

  defstruct algorithm: :yake,
            max_keywords: 10,
            min_score: 0,
            ngram_range: [],
            language: "",
            yake_params: nil,
            rake_params: nil
end
