# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c8be07b8cac4a183ce1ca55fb4422188227a7c8c346fa954524be09844031799
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  defstruct text: "",
            score: 0.0,
            algorithm: :yake,
            positions: nil
end
