# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ca386fa694563670f764f4757aa8a204be4f0113972f3df7bda9084c7b09b1b9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.KeywordAlgorithm do
  @moduledoc "Keyword algorithm selection."

  @type t :: :yake | :rake

  @yake :yake
  @rake :rake

  @spec yake() :: t()
  def yake, do: @yake
  @spec rake() :: t()
  def rake, do: @rake
end
