# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a8169142353cfce3760c0f49d260b5f99e3cc7ab86767ba45280e85b2e469177
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.KeywordAlgorithm do
  @moduledoc "Keyword algorithm selection."

  @type t :: :yake | :rake

  @yake :yake
  @rake :rake

  @spec yake() :: t()
  def yake, do: @yake
  @spec rake() :: t()
  def rake, do: @rake
end
