# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4ee1f43a27d2751644cc416db8654083b0c62df1f682d1f48b551ce0ddf8da0e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  defstruct text: "",
            score: 0.0,
            algorithm: :yake,
            positions: nil
end
