# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6bf53e3672c870d1f8d9ebe4db4d27ded6bb54765c30e1c865d59f8259529af2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LanguageDetectionConfig do
  @moduledoc "Language detection configuration."

  defstruct enabled: true,
            min_confidence: 0.8,
            detect_multiple: false
end
