# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b3cd41e503e5c920572efad6c1c5a935656c5f66a37f3ae09c16baad46301a61
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LanguageDetectionConfig do
  @moduledoc "Language detection configuration."

  defstruct enabled: true,
            min_confidence: 0.8,
            detect_multiple: false
end
