# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4be8ee3b4a7f163397dcf2ea05dcad9b6833e530d8dbb80760ca47ce31ce81f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutRegion do
  @moduledoc "A detected layout region on a page."

  defstruct class_name: "",
            confidence: 0.0,
            bounding_box: "",
            area_fraction: 0.0
end
