# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8dba308264acedcf54bae3f1fad9f7e9bb98cd0d2c70f03a65fa1bbaec393d7c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutDetectionConfig do
  @moduledoc "Layout detection configuration."

  defstruct confidence_threshold: nil,
            apply_heuristics: true,
            table_model: :tatr,
            acceleration: nil
end
