# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e3658ced801204f0e9ed2662882387a3d476b724ae1d24caa3178b8ec2954fa5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  defstruct class_name: :caption,
            confidence: 0.0,
            bbox: nil
end
