# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fc4110f9d389291a32819bfbfc2686eff2bb0e866cbc86419fbf0eec4f58b1d4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LinkMetadata do
  @moduledoc "Link element metadata."

  defstruct href: "",
            text: "",
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: []
end
