# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba2b1ad46c4c9aa4bbadc35ab2cda2d6425c3dd44c33b8cb8d80796836e4518b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LinkType do
  @moduledoc "Link type classification."

  @type t :: :anchor | :internal | :external | :email | :phone | :other

  @anchor :anchor
  @internal :internal
  @external :external
  @email :email
  @phone :phone
  @other :other

  @spec anchor() :: t()
  def anchor, do: @anchor
  @spec internal() :: t()
  def internal, do: @internal
  @spec external() :: t()
  def external, do: @external
  @spec email() :: t()
  def email, do: @email
  @spec phone() :: t()
  def phone, do: @phone
  @spec other() :: t()
  def other, do: @other
end
