# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a9dd11aec43ae2da9dc426fdc7ba321724eec267f8d5011353ba8c6ce41ad59e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LinkMetadata do
  @moduledoc "Link element metadata."

  defstruct href: "",
            text: "",
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: []
end
