# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1166e48e2b772ae06ea0f88c07b2c808a3a4d42813eaf4d6b3cf5210e836f2f0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LinkMetadata do
  @moduledoc "Link element metadata."

  defstruct href: "",
            text: "",
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: []
end
