# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:04cbf4adb4fd126c77969b993f132864f8c70014a93dbd5d00a54d7ea25af461
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LlmUsage do
  @moduledoc "Token usage and cost data for a single LLM call made during extraction."

  defstruct model: "",
            source: "",
            input_tokens: 0,
            output_tokens: 0,
            total_tokens: 0,
            estimated_cost: 0.0,
            finish_reason: ""
end
