# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ddd951d381730a33a15d078eb2ee1a6ba51077b3bead154797c0e82880e2da04
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LlmConfig do
  @moduledoc "Configuration for an LLM provider/model via liter-llm."

  defstruct model: "",
            api_key: "",
            base_url: "",
            timeout_secs: 0,
            max_retries: 0,
            temperature: 0.0,
            max_tokens: 0
end
