# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ee532cfe20901c66a43ccf5caff8a5eabff3a4f1a35b53705c3ea130bb2a1818
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ManifestEntryResponse do
  @moduledoc "Model manifest entry for cache management."

  defstruct relative_path: "",
            sha256: "",
            size_bytes: 0,
            source_url: ""
end
