# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f31b32c37eefdbe5ba349540aa17b1aa48771b8875841736da9aeabfb2628b06
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.MergedChunk do
  @moduledoc "A merged chunk produced by [`merge_segments`]."

  defstruct text: "",
            byte_start: 0,
            byte_end: 0
end
