# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:25b297ff017a66acba81608d39e07cdf5be564a968afd453fb29ac00a16d4b36
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.MergedChunk do
  @moduledoc "A merged chunk produced by [`merge_segments`]."

  defstruct text: "",
            byte_start: 0,
            byte_end: 0
end
