# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:64f9d7498f07d6fae79cd343fbeedee7d455991fb5732cb5ae5757653295ab4e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Metadata do
  @moduledoc "Extraction result metadata."

  defstruct title: "",
            subject: "",
            authors: [],
            keywords: [],
            language: "",
            created_at: "",
            modified_at: "",
            created_by: "",
            modified_by: "",
            pages: nil,
            format: :pdf,
            image_preprocessing: nil,
            json_schema: "",
            error: nil,
            extraction_duration_ms: 0,
            category: "",
            tags: [],
            document_version: "",
            abstract_text: "",
            output_format: "",
            sheet_count: 0,
            sheet_names: [],
            additional: %{}
end
