# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5868b23c4ea1c3c24c5b380368368b8d997ba7bf35e3f80c15e219cc98b48569
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Metadata do
  @moduledoc "Extraction result metadata."

  defstruct title: "",
            subject: "",
            authors: [],
            keywords: [],
            language: "",
            created_at: "",
            modified_at: "",
            created_by: "",
            modified_by: "",
            pages: nil,
            format: :pdf,
            image_preprocessing: nil,
            json_schema: "",
            error: nil,
            extraction_duration_ms: 0,
            category: "",
            tags: [],
            document_version: "",
            abstract_text: "",
            output_format: "",
            additional: %{}
end
