# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f7029895bd1b537ded51ec3c4d442b966185af0141f7df91e26cf1c705021ac2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ModelPaths do
  @moduledoc "Combined paths to all models needed for OCR (backward compatibility)."

  defstruct det_model: "",
            cls_model: "",
            rec_model: "",
            dict_file: ""
end
