# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a7e644c62c48a8eb5f110e1be097a93e55f313edc132bc99281150802d73054d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ModelPaths do
  @moduledoc "Combined paths to all models needed for OCR (backward compatibility)."

  defstruct det_model: "",
            cls_model: "",
            rec_model: "",
            dict_file: ""
end
