# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cb78d9751d3647c80bfd83a46b73a6a2cd5ae4887cae6e91839a974f1f92b37b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrTableBoundingBox do
  @moduledoc "Bounding box for an OCR-detected table in pixel coordinates."

  defstruct left: 0,
            top: 0,
            right: 0,
            bottom: 0
end
