# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:74b3c835d15234a958a2601eb0f8d77bc00cb8b4f52a824d9dbf9c247f5103b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElementLevel do
  @moduledoc "Hierarchical level of an OCR element."

  @type t :: :word | :line | :block | :page

  @word :word
  @line :line
  @block :block
  @page :page

  @spec word() :: t()
  def word, do: @word
  @spec line() :: t()
  def line, do: @line
  @spec block() :: t()
  def block, do: @block
  @spec page() :: t()
  def page, do: @page
end
