# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:91a77d28ef7e7f5c91e3f7e4bba8e212c0d34e8fc69d66ea304e2f8215c528b0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElementConfig do
  @moduledoc "Configuration for OCR element extraction."

  defstruct include_elements: false,
            min_level: :line,
            min_confidence: 0.0,
            build_hierarchy: false
end
