# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b932742b0d5ddabb0fc5e724ce1cfe383828ae6f9718f9b3e83bb137b3bec439
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElementConfig do
  @moduledoc "Configuration for OCR element extraction."

  defstruct include_elements: false,
            min_level: :line,
            min_confidence: 0.0,
            build_hierarchy: false
end
