# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1a4408eb7699a8db2b373d4d72280d3e2e7993ac617ff3d54ca6bee584bb4bb1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrBoundingGeometry do
  @moduledoc "Bounding geometry for an OCR element."

  @type t :: term()

  @type rectangle :: %{type: :rectangle, left: term(), top: term(), width: term(), height: term()}
  @type quadrilateral :: %{type: :quadrilateral, points: term()}
end
