# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:076f2ec7810099027dbfd0d6904632b5b7d782dfda9988cbf84122afd957e6c2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElementLevel do
  @moduledoc "Hierarchical level of an OCR element."

  @type t :: :word | :line | :block | :page

  @word :word
  @line :line
  @block :block
  @page :page

  @spec word() :: t()
  def word, do: @word
  @spec line() :: t()
  def line, do: @line
  @spec block() :: t()
  def block, do: @block
  @spec page() :: t()
  def page, do: @page
end
