# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b1e41595f713956dd8bf5ed20fbd4d4ba7ae239e941314b33d8f58bdfd0c02d3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrTableBoundingBox do
  @moduledoc "Bounding box for an OCR-detected table in pixel coordinates."

  defstruct left: 0,
            top: 0,
            right: 0,
            bottom: 0
end
