# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1372b5d15293a2ca0de919e59b6a15d8ac31d2a7c939e69e962314fb92638078
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrTable do
  @moduledoc "Table detected via OCR."

  defstruct cells: [],
            markdown: "",
            page_number: 0,
            bounding_box: nil
end
