# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0f1d6de7b5d20b3c78810333d54acea5ade9e7c29e92ad3969762be9ad0f8339
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrRotation do
  @moduledoc "Rotation information for an OCR element."

  defstruct angle_degrees: 0.0,
            confidence: nil
end
