# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8a49f8ca5fd95bc11b69cdb211cd39242bbb99eb4310f7c805dbd641f28c76ca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrMetadata do
  @moduledoc "OCR processing metadata."

  defstruct language: "",
            psm: 0,
            output_format: "",
            table_count: 0,
            table_rows: 0,
            table_cols: 0
end
