# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f91ef56af78093fe98bb47e921e83273969750793b24e465a89d75f23f047936
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrPipelineConfig do
  @moduledoc "Multi-backend OCR pipeline with quality-based fallback."

  defstruct stages: [],
            quality_thresholds: nil
end
