# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4ca174dc2e1c9c29736595c77c9dc27e29e116a389ab6ece50a17eca2bbffa31
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrConfidence do
  @moduledoc "Confidence scores for an OCR element."

  defstruct detection: 0.0,
            recognition: 0.0
end
