# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:143539dd3c860307f4e3c88a724c45b3dcbaf43d3ae8598db2a7bf4f0cd63eb2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElementConfig do
  @moduledoc "Configuration for OCR element extraction."

  defstruct include_elements: false,
            min_level: :line,
            min_confidence: 0.0,
            build_hierarchy: false
end
