# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3ede1bff8f93856b98028c1e26c8ddb0dd6cf0c9b461b90eff3f772dcb326a9c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrPipelineStage do
  @moduledoc "A single backend stage in the OCR pipeline."

  defstruct backend: "",
            priority: 0,
            language: nil,
            tesseract_config: nil,
            paddle_ocr_config: nil,
            vlm_config: nil
end
