# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cce5fcda00a28bb8e9e05f54f6d23f960ad4b447e4d19f95143b6ad7f9b7f347
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrPipelineConfig do
  @moduledoc "Multi-backend OCR pipeline with quality-based fallback."

  defstruct stages: [],
            quality_thresholds: nil
end
