# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cd0c43e83f9a155ffef6e9c5dcac4807c42ef4b6b901598db256e74c9ee73da8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrTable do
  @moduledoc "Table detected via OCR."

  defstruct cells: [],
            markdown: "",
            page_number: 0,
            bounding_box: nil
end
