# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:080f51698b9e520844e3b732baaa7c00d26a8dddf3b66bf1c0f921c84643f348
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrBoundingGeometry do
  @moduledoc "Bounding geometry for an OCR element."

  @type t :: term()

  @type rectangle :: %{type: :rectangle, left: term(), top: term(), width: term(), height: term()}
  @type quadrilateral :: %{type: :quadrilateral, points: term()}
end
