# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e05a1c74156f78135dc7945ddbfb54757b87c6cff0a9eb35561582359eeabfee
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElementLevel do
  @moduledoc "Hierarchical level of an OCR element."

  @type t :: :word | :line | :block | :page

  @word :word
  @line :line
  @block :block
  @page :page

  @spec word() :: t()
  def word, do: @word
  @spec line() :: t()
  def line, do: @line
  @spec block() :: t()
  def block, do: @block
  @spec page() :: t()
  def page, do: @page
end
