# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:297eac77a2a5d2091f9ef4e842404da67ab53c9a8f0f12c102912f9b1cb3d895
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrConfidence do
  @moduledoc "Confidence scores for an OCR element."

  defstruct detection: 0.0,
            recognition: 0.0
end
