# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bc3ffab6d71d211d8da77b410fe5ff4e4510923e8e06d51af37c0d708298c433
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrPipelineConfig do
  @moduledoc "Multi-backend OCR pipeline with quality-based fallback."

  defstruct stages: [],
            quality_thresholds: nil
end
