# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:352ec85f73f2429a8e4ab8b962686c5203362ac78bc8754ba34113de1ebc5b36
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElement do
  @moduledoc "A unified OCR element representing detected text with full metadata."

  defstruct text: "",
            geometry: :rectangle,
            confidence: nil,
            level: :line,
            rotation: nil,
            page_number: 0,
            parent_id: "",
            backend_metadata: %{}
end
