# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b26499d8504d56c60e2e224cfb25fffd96cc4757cc2a19e109143e02ae2633e7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrMetadata do
  @moduledoc "OCR processing metadata."

  defstruct language: "",
            psm: 0,
            output_format: "",
            table_count: 0,
            table_rows: 0,
            table_cols: 0
end
