# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a0965aa92e5b805b52d31f8dbb8a6ed99865a7b91614d409024f2703d2b66326
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrCacheStats do
  @moduledoc false

  defstruct total_files: 0,
            total_size_mb: 0.0
end
