# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d11573017ae3edd58cb5be69893d2ae10f2488ec629604c9f01c15522c063444
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OdtProperties do
  @moduledoc "OpenDocument metadata from meta.xml"

  defstruct title: "",
            subject: "",
            creator: "",
            initial_creator: "",
            keywords: "",
            description: "",
            date: "",
            creation_date: "",
            language: "",
            generator: "",
            editing_duration: "",
            editing_cycles: "",
            page_count: 0,
            word_count: 0,
            character_count: 0,
            paragraph_count: 0,
            table_count: 0,
            image_count: 0
end
