# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:768390d7069e5837499f18ff17185279b52f5a32e780a7b979f6d8bde3e1757d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageConfig do
  @moduledoc "Page extraction and tracking configuration."

  defstruct extract_pages: false,
            insert_page_markers: false,
            marker_format: "

<!-- PAGE {page_num} -->

"
end
