# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d80b2a4b7b6bb036efbb1541b74760d823c8dd1328bfcfc535c52688a426d8d3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageConfig do
  @moduledoc "Page extraction and tracking configuration."

  defstruct extract_pages: false,
            insert_page_markers: false,
            marker_format: "

<!-- PAGE {page_num} -->

"
end
