# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:554f27a78fcfad457d0ffaf5cfd4947bb43cfe05abcc1e3de766aef297857c73
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageBoundary do
  @moduledoc "Byte offset boundary for a page."

  defstruct byte_start: 0,
            byte_end: 0,
            page_number: 0
end
