# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b291a96d097c052cf6e7a32fffc47f8530f3a3692864d0b3cf7893fa7c71ae5d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageUnitType do
  @moduledoc "Type of paginated unit in a document."

  @type t :: :page | :slide | :sheet

  @page :page
  @slide :slide
  @sheet :sheet

  @spec page() :: t()
  def page, do: @page
  @spec slide() :: t()
  def slide, do: @slide
  @spec sheet() :: t()
  def sheet, do: @sheet
end
