# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:278bb84e28c2513b63108fe25ace022ab5e63a98549460ab3126c7d802932ab4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageStructure do
  @moduledoc "Unified page structure for documents."

  defstruct total_count: 0,
            unit_type: :page,
            boundaries: nil,
            pages: nil
end
