# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7506d5e5b0250fe778f74674463d3c19ed7ac92c95f1f388ecfe418ed54914a1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageContent do
  @moduledoc "Content for a single page/slide."

  defstruct page_number: 0,
            content: "",
            tables: [],
            images: [],
            hierarchy: nil,
            is_blank: nil,
            layout_regions: nil
end
