# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6d6f7912a0828f1af1e89f4d2f7831a5f3621f76e3fce0503600b3cda50b6989
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageStructure do
  @moduledoc "Unified page structure for documents."

  defstruct total_count: 0,
            unit_type: :page,
            boundaries: nil,
            pages: nil
end
