# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c20e2af3b6a01f79fbefb484a70e883917ec6e7b8d0585425ee44003279de9ba
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageContent do
  @moduledoc "Content for a single page/slide."

  defstruct page_number: 0,
            content: "",
            tables: [],
            images: [],
            hierarchy: nil,
            is_blank: nil,
            layout_regions: nil
end
