# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:45df84973d6f3a17ae2c3e1c59ea2c0f838e10610b7fb65c5fd0a009bd87a94b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageConfig do
  @moduledoc "Page extraction and tracking configuration."

  defstruct extract_pages: false,
            insert_page_markers: false,
            marker_format: "

<!-- PAGE {page_num} -->

"
end
