# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:664a53da769deb776c14b26c38e5c5463cd57f997879554bc7f50218e182aae8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageStructure do
  @moduledoc "Unified page structure for documents."

  defstruct total_count: 0,
            unit_type: :page,
            boundaries: nil,
            pages: nil
end
