# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6a7b0e82735757c4399d777849b576a71b557f3da4fd8857634aabedce6b208d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageMarginsPoints do
  @moduledoc "Page margins converted to points (1/72 inch)."

  defstruct top: 0.0,
            right: 0.0,
            bottom: 0.0,
            left: 0.0,
            header: 0.0,
            footer: 0.0,
            gutter: 0.0
end
