# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:536c734de38d70d8b0acae1bc4788f81049aa39c878c85a5c2490e07718e388d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageHierarchy do
  @moduledoc "Page hierarchy structure containing heading levels and block information."

  defstruct block_count: 0,
            blocks: []
end
