# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:42492f97ec46f4eead52107ae524e53a5e37fd867689adad315b197c20d2efeb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageInfo do
  @moduledoc "Metadata for individual page/slide/sheet."

  defstruct number: 0,
            title: nil,
            dimensions: nil,
            image_count: nil,
            table_count: nil,
            hidden: nil,
            is_blank: nil,
            has_vector_graphics: false
end
