# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d8f4622e719c597820f6bd5cdbbc7e3d3922bc67ed6371eb688a396ab4f3bd07
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfConfig do
  @moduledoc "PDF-specific configuration."

  defstruct extract_images: false,
            passwords: nil,
            extract_metadata: true,
            hierarchy: nil,
            extract_annotations: false,
            top_margin_fraction: nil,
            bottom_margin_fraction: nil,
            allow_single_column_tables: false
end
