# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bd621b50e347ec9a84175d062a4a5fbe9c3bc671f5c793b819751aec2fd478f8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfMetadata do
  @moduledoc "PDF-specific metadata."

  defstruct pdf_version: "",
            producer: "",
            is_encrypted: false,
            width: 0,
            height: 0,
            page_count: 0
end
