# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:afc0bf5e43967447182aa28cd400f1be2d9bfed6e83d8e7273117053e13b30a7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfAnnotation do
  @moduledoc "A PDF annotation extracted from a document page."

  defstruct annotation_type: :text,
            content: nil,
            page_number: 0,
            bounding_box: nil
end
