# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:97b727b102e00233dc5fc7648c44cafaed1145cbecc03ca94361f280042f3ca0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfConfig do
  @moduledoc "PDF-specific configuration."

  defstruct extract_images: false,
            passwords: nil,
            extract_metadata: true,
            hierarchy: nil,
            extract_annotations: false,
            top_margin_fraction: nil,
            bottom_margin_fraction: nil,
            allow_single_column_tables: false
end
