# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e8f548022efedf293f80706b8594735f4556cd08af79c1d5082ad16fdf713ba6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfMetadata do
  @moduledoc "PDF-specific metadata."

  defstruct pdf_version: "",
            producer: "",
            is_encrypted: false,
            width: 0,
            height: 0,
            page_count: 0
end
