# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cd1e3898ba8d9be0bc01b00cd7750fad27e1cf3714a7cb829081045ef16159ee
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PostProcessorConfig do
  @moduledoc "Post-processor configuration."

  defstruct enabled: true,
            enabled_processors: nil,
            disabled_processors: nil,
            enabled_set: nil,
            disabled_set: nil
end
