# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6c179e62f8fea296882fe6cf49c2f69598ebdf4eb35046dda0c482459d903ee8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PostProcessorConfig do
  @moduledoc "Post-processor configuration."

  defstruct enabled: true,
            enabled_processors: nil,
            disabled_processors: nil,
            enabled_set: nil,
            disabled_set: nil
end
