# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ede0c24c802a4039c8d413c55951a514d1450f7f32b4b0fdd4639e33a9bc9637
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PptxMetadata do
  @moduledoc "PowerPoint presentation metadata."

  defstruct slide_count: 0,
            slide_names: [],
            image_count: 0,
            table_count: 0
end
