# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6e40192f357a25778a4aeaa7b5f62c1242cd4d0eda6229e641933af185c7182b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PptxMetadata do
  @moduledoc "PowerPoint presentation metadata."

  defstruct slide_count: 0,
            slide_names: [],
            image_count: 0,
            table_count: 0
end
