# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6c0ae51355e58f96dd1dd72785863caec4ad08a2dab879b3162eabd3405428e4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ProcessingStage do
  @moduledoc "Processing stages for post-processors."

  @type t :: :early | :middle | :late

  @early :early
  @middle :middle
  @late :late

  @spec early() :: t()
  def early, do: @early
  @spec middle() :: t()
  def middle, do: @middle
  @spec late() :: t()
  def late, do: @late
end
