# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:327442e2a3d76c0625ade08dd986f9f8589ed2ee3f9ee3560a9f19e3a2e1f540
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ProcessingWarning do
  @moduledoc "A non-fatal warning from a processing pipeline stage."

  defstruct source: "",
            message: ""
end
