# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:93f93de88af8f97388cbbee8a14e817cd7f3e433cfdf18ff6dab5def728de4e9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ProcessingWarning do
  @moduledoc "A non-fatal warning from a processing pipeline stage."

  defstruct source: "",
            message: ""
end
