# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:60793ad58dc213ae1dabed2a5d3ad18a93e5679a9a2c508207c4f54005666079
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ProcessingWarning do
  @moduledoc "A non-fatal warning from a processing pipeline stage."

  defstruct source: "",
            message: ""
end
