# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:13cfa8db594d2bca111af42edc586238cf641e5d899439db4b6a0c16065b375d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PstMetadata do
  @moduledoc "Outlook PST archive metadata."

  defstruct message_count: 0
end
