# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a7bcd6cfd2bcbbed9760f23e8bd03e08745933503413f356ab50eb713a692079
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PstMetadata do
  @moduledoc "Outlook PST archive metadata."

  defstruct message_count: 0
end
