# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:94239972bf85a34d17e48912643069d202468114b923254ab89efc8eb392a25b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RakeParams do
  @moduledoc "RAKE-specific parameters."

  defstruct min_word_length: 1,
            max_words_per_phrase: 3
end
