# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e1bacc2125af55ecd460fba9917e6e0d528c88c6f2c65c6fbc2ff23adece820f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RakeParams do
  @moduledoc "RAKE-specific parameters."

  defstruct min_word_length: 1,
            max_words_per_phrase: 3
end
