# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7b7d9407957b007dcf785ce597465a133f224a520738261caadfdd77d3955ffa
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RecognizedTable do
  @moduledoc "Pre-computed table markdown for a table detection region."

  defstruct detection_bbox: nil,
            cells: [],
            markdown: ""
end
