# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2577c336d041d60dd806b1dd128f42d96327514fcbb508aab3754f4c9692cb2b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RecognizedTable do
  @moduledoc "Pre-computed table markdown for a table detection region."

  defstruct detection_bbox: nil,
            cells: [],
            markdown: ""
end
