# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c4151070b5ce70bbd8341978c041edc256ea9a142d46fa5ef12b81601940ff44
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RecognizedTable do
  @moduledoc "Pre-computed table markdown for a table detection region."

  defstruct detection_bbox: nil,
            cells: [],
            markdown: ""
end
