# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c8dce54f7f72417b7ad1863d12f00ee6c1193d7fd94ba35e98e219ca4d5ba50d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ReductionLevel do
  @moduledoc false

  @type t :: :off | :light | :moderate | :aggressive | :maximum

  @off :off
  @light :light
  @moderate :moderate
  @aggressive :aggressive
  @maximum :maximum

  @spec off() :: t()
  def off, do: @off
  @spec light() :: t()
  def light, do: @light
  @spec moderate() :: t()
  def moderate, do: @moderate
  @spec aggressive() :: t()
  def aggressive, do: @aggressive
  @spec maximum() :: t()
  def maximum, do: @maximum
end
