# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0c564f1c4c9cc8ad43b880a8f7e2a7fd1dc09970df0a6816b8af66a70e52e678
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ReductionLevel do
  @moduledoc false

  @type t :: :off | :light | :moderate | :aggressive | :maximum

  @off :off
  @light :light
  @moderate :moderate
  @aggressive :aggressive
  @maximum :maximum

  @spec off() :: t()
  def off, do: @off
  @spec light() :: t()
  def light, do: @light
  @spec moderate() :: t()
  def moderate, do: @moderate
  @spec aggressive() :: t()
  def aggressive, do: @aggressive
  @spec maximum() :: t()
  def maximum, do: @maximum
end
