# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:84e250b6bacb95b496672f1c65158afeb84ca51b61b72b2928ec643265df3a42
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ResolvedStyle do
  @moduledoc "Fully resolved (flattened) style after walking the inheritance chain."

  defstruct paragraph_properties: "",
            run_properties: ""
end
