# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:89deb8cf7e57452fc545d8898278293a67ef0e11a8780cc95f07f66c5a54fa02
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ResolvedStyle do
  @moduledoc "Fully resolved (flattened) style after walking the inheritance chain."

  defstruct paragraph_properties: "",
            run_properties: ""
end
