# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a4c22a1ff3b3d6204baffa6ef3f4de6a5792a1648a64b538c49c89abb850ed8c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.SecurityLimits do
  @moduledoc "Configuration for security limits across extractors."

  defstruct max_archive_size: 524_288_000,
            max_compression_ratio: 100,
            max_files_in_archive: 10_000,
            max_nesting_depth: 1_024,
            max_entity_length: 1_048_576,
            max_content_size: 104_857_600,
            max_iterations: 10_000_000,
            max_xml_depth: 1_024,
            max_table_cells: 100_000
end
