# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3fe19b12bc970701e749d476aea214f59a7abd88975f218b4a5b6aa5534b58e7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ServerConfig do
  @moduledoc "API server configuration."

  defstruct host: "",
            port: 0,
            cors_origins: [],
            max_request_body_bytes: 0,
            max_multipart_field_bytes: 0
end
