# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:20c57a0cfb4a4f3db2ae0e3108c9230ab48cec857960e78900cb103ab612ca1c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredData do
  @moduledoc "Structured data (Schema.org, microdata, RDFa) block."

  defstruct data_type: :json_ld,
            raw_json: "",
            schema_type: nil
end
