# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7133798cc67729c552e168d57dd7928d4902057102d7ae8002028a314f6672e1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredExtractionResponse do
  @moduledoc "Response from structured extraction endpoint."

  defstruct structured_output: "",
            content: "",
            mime_type: ""
end
