# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:da9fb6f1366af99e1a440ea79fc954b4052233480c77b8dd71c4cedc528d7e1e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredExtractionConfig do
  @moduledoc "Configuration for LLM-based structured data extraction."

  defstruct schema: "",
            schema_name: "",
            schema_description: nil,
            strict: false,
            prompt: nil,
            llm: nil
end
