# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:db2d930b3effe6b3bfdf05efe364c44b2e2fc3f22ebf8edb1d16201692c92abc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredData do
  @moduledoc "Structured data (Schema.org, microdata, RDFa) block."

  defstruct data_type: :json_ld,
            raw_json: "",
            schema_type: nil
end
