# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4e019baa33906af229f90996b7dfdd065445e668c5e853491ab13d08352982d8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredExtractionConfig do
  @moduledoc "Configuration for LLM-based structured data extraction."

  defstruct schema: "",
            schema_name: "",
            schema_description: nil,
            strict: false,
            prompt: nil,
            llm: nil
end
