# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c97489c1fca8ea31cda631d423840fa02f64ed569e605160df7d570710c49b97
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.SupportedFormat do
  @moduledoc "A supported document format entry."

  defstruct extension: "",
            mime_type: ""
end
