# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9f02af508a2ff111e962401e2ddbf4f16f428c78cb2f9e26348f7cd1b2c3e387
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.SupportedFormat do
  @moduledoc "A supported document format entry."

  defstruct extension: "",
            mime_type: ""
end
