# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:291525e3ee77061496eae7c573476fe7e334d49ed14612d99476c3ec927b5f0a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.SupportedFormat do
  @moduledoc "A supported document format entry."

  defstruct extension: "",
            mime_type: ""
end
