# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:649370d2f8d16bd2a206ec2d75ab6c23e80b6fd20100021246abca13212db364
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableGrid do
  @moduledoc "Structured table grid with cell-level metadata."

  defstruct rows: 0,
            cols: 0,
            cells: []
end
