# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3d91cf257b88794ddf3a212cb2aa17c102691fe44e7a7bd61b167191f0bb3fe4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableGrid do
  @moduledoc "Structured table grid with cell-level metadata."

  defstruct rows: 0,
            cols: 0,
            cells: []
end
