# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8193a81f52c78c24ae2c0d474ec6ba93867407fb3d043dd4d981bcb772a1e511
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableProperties do
  @moduledoc "Table-level properties from `<w:tblPr>`."

  defstruct style_id: "",
            width: "",
            alignment: "",
            layout: "",
            look: "",
            borders: "",
            cell_margins: "",
            indent: "",
            caption: ""
end
