# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0d50ae75d82d756d7786db8315b3ff00e89d80c1f0ca161efdb684f4bfac8ed8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Table do
  @moduledoc "Extracted table structure."

  defstruct cells: [],
            markdown: "",
            page_number: 0,
            bounding_box: ""
end
