# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c7978c7e372b5a6042ee940e5f2138ef2733c225a6ea64a96714987bbfd7c766
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableModel do
  @moduledoc "Which table structure recognition model to use."

  @type t :: :tatr | :slanet_wired | :slanet_wireless | :slanet_plus | :slanet_auto | :disabled

  @tatr :tatr
  @slanet_wired :slanet_wired
  @slanet_wireless :slanet_wireless
  @slanet_plus :slanet_plus
  @slanet_auto :slanet_auto
  @disabled :disabled

  @spec tatr() :: t()
  def tatr, do: @tatr
  @spec slanet_wired() :: t()
  def slanet_wired, do: @slanet_wired
  @spec slanet_wireless() :: t()
  def slanet_wireless, do: @slanet_wireless
  @spec slanet_plus() :: t()
  def slanet_plus, do: @slanet_plus
  @spec slanet_auto() :: t()
  def slanet_auto, do: @slanet_auto
  @spec disabled() :: t()
  def disabled, do: @disabled
end
