# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5906bddc468272ddfd6c10bff793ac6bcb2590d2f4c0b475ae4de7583d7ff483
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Table do
  @moduledoc "Extracted table structure."

  defstruct cells: [],
            markdown: "",
            page_number: 0,
            bounding_box: ""
end
