# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d5aa244cc66d4b78292eefc636f73a885548fc83ecfdf04351dc90055b8972a2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableCell do
  @moduledoc "Individual table cell with content and optional styling."

  defstruct content: "",
            row_span: 0,
            col_span: 0,
            is_header: false
end
