# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ad7c4d05fc0e2b6eb8784261ae346e4d74726d0e26e72fa313477b2a2fbe3549
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextAnnotation do
  @moduledoc "Inline text annotation — byte-range based formatting and links."

  defstruct start: 0,
            end: 0,
            kind: :bold
end
