# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:80afdb2159e332a994aeae66ebc8fa1a172a9177267c46398cea75b7713c27d0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextMetadata do
  @moduledoc "Text/Markdown metadata."

  defstruct line_count: 0,
            word_count: 0,
            character_count: 0,
            headers: [],
            links: [],
            code_blocks: []
end
