# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a88fbfc9776d700608e534cb2b21228a91dd12820fde8e07b76fa7be15dbee02
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TokenReductionOptions do
  @moduledoc "Token reduction configuration."

  defstruct mode: "",
            preserve_important_words: true
end
