# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d3ce330f1f0185d502d6cb87f58acafce72f0b390b1567c9c9a460db8229aab1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TokenReductionOptions do
  @moduledoc "Token reduction configuration."

  defstruct mode: "",
            preserve_important_words: true
end
