# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cadd69099e60771718863166a8641a7d440615980b541ad34f2f53c04193f0e1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TokenReductionOptions do
  @moduledoc "Token reduction configuration."

  defstruct mode: "",
            preserve_important_words: true
end
