# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0a40f57907984c485dd62501b44b2942e1702f82f0a771c85140e63dcd1f5823
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TreeSitterProcessConfig do
  @moduledoc "Processing options for tree-sitter code analysis."

  defstruct structure: true,
            imports: true,
            exports: true,
            comments: false,
            docstrings: false,
            symbols: false,
            diagnostics: false,
            chunk_max_size: nil,
            content_mode: :chunks
end
