# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a623d7b09e1116c569aa6e065b9b8933017ce25b60285ea0636053e1cb3e09bb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TreeSitterConfig do
  @moduledoc "Configuration for tree-sitter language pack integration."

  defstruct enabled: true,
            cache_dir: nil,
            languages: nil,
            groups: nil,
            process: nil
end
