# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e1d3930a509483d7fd1c0af14938353fa283c5b042b54b26ffa2179a15ba7a10
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TreeSitterProcessConfig do
  @moduledoc "Processing options for tree-sitter code analysis."

  defstruct structure: true,
            imports: true,
            exports: true,
            comments: false,
            docstrings: false,
            symbols: false,
            diagnostics: false,
            chunk_max_size: nil,
            content_mode: :chunks
end
