# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1a10accf25b42b6dac2c7c2d62ca7b10534f7cc1c3d38980e2b6e0de6ca081f9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TreeSitterConfig do
  @moduledoc "Configuration for tree-sitter language pack integration."

  defstruct enabled: true,
            cache_dir: nil,
            languages: nil,
            groups: nil,
            process: nil
end
