# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:07feccca16ed07b8a1a224c31420069f83de5fb1ec97e813074024120381ece9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Uri do
  @moduledoc "A URI extracted from a document."

  defstruct url: "",
            label: nil,
            page: nil,
            kind: :hyperlink
end
