# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:39f318ab5656916f52c1083a36fc4e125c0d72f462a7ff53f13615ff6098798f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Uri do
  @moduledoc "A URI extracted from a document."

  defstruct url: "",
            label: nil,
            page: nil,
            kind: :hyperlink
end
