# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:17a7e36cfb8dc72caa5b22c6578fb5ed412a1c99678c25b650f8bc3253ed537e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.WarmResponse do
  @moduledoc "Cache warm response."

  defstruct cache_dir: "",
            downloaded: [],
            already_cached: []
end
