# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b785dbf881f67ef750b9d8e7ab0d2e933e1941c30caec04b41631b6763af1a6a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.XlsxAppProperties do
  @moduledoc "Application properties from docProps/app.xml for XLSX"

  defstruct application: "",
            app_version: "",
            doc_security: 0,
            scale_crop: false,
            links_up_to_date: false,
            shared_doc: false,
            hyperlinks_changed: false,
            company: "",
            worksheet_names: []
end
