# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9fc80ede1b25e489fed0a7da2506930679e304f7bf7ecffaa4b3f2734c077ca9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.XmlMetadata do
  @moduledoc "XML metadata extracted during XML parsing."

  defstruct element_count: 0,
            unique_elements: []
end
