# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a7096e9a0c9743768c6c3bf5a46f457ae3fcbb5ee3e67c00cc92d7b559f496e2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.XmlMetadata do
  @moduledoc "XML metadata extracted during XML parsing."

  defstruct element_count: 0,
            unique_elements: []
end
