# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:263657004f205984f4a498f48fa3a8fa36e72017fd3631457f02c1a10e77d910
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.YakeParams do
  @moduledoc "YAKE-specific parameters."

  defstruct window_size: 2
end
