# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1bb6e6e849e59e1297b6a5851bc5b03ae9c675c95740ea02bca8b663b616443
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  defstruct min: nil,
            max: nil,
            years: []
end
