# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:784390a95eb70de9bf0f8f97ae2d074e521e1f11ca76471409c2f6a607a5e6ac
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  defstruct min: nil,
            max: nil,
            years: []
end
