# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4150a78481a90468e7c9e0bdb15966aec0c2b89fee1032a61191b63f399e9079
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  defstruct min: nil,
            max: nil,
            years: []
end
