// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8ddf60dcbc4251d26f5081b935bcf67db51ccacdffc0fdfffbe73524bd9ecfd2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import gleeunit
import gleeunit/should
import kreuzberg
import e2e_gleam

import gleam/option

// extract_bytes empty MIME async
pub fn async_extract_bytes_empty_mime_test() {
  let assert Ok(data_bytes__) = e2e_gleam.read_file_bytes("../../test_documents/text/plain.txt")
  kreuzberg.extract_bytes(data_bytes__, "", kreuzberg.config_from_json_string("{}")) |> should.be_error()
}

// extract_bytes unsupported MIME async
pub fn async_extract_bytes_invalid_mime_test() {
  let assert Ok(data_bytes__) = e2e_gleam.read_file_bytes("../../test_documents/text/plain.txt")
  kreuzberg.extract_bytes(data_bytes__, "application/x-nonexistent", kreuzberg.config_from_json_string("{}")) |> should.be_error()
}
