// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3772f1400b1e3ac08324022ee990fc66706e87db0100763ff8d4c60e5bd06e53
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import gleeunit
import gleeunit/should
import kreuzberg
import e2e_gleam

import gleam/option

// Detect HTML MIME from bytes
pub fn detect_mime_bytes_html_test() {
  let assert Ok(data_bytes__) = e2e_gleam.read_file_bytes("../../test_documents/html/html.html")
  let result = kreuzberg.detect_mime_type_from_bytes(data_bytes__)
  result |> should.be_ok()
  let assert Ok(r) = result
}

// Detect PDF MIME type from bytes
pub fn detect_mime_bytes_pdf_test() {
  let assert Ok(data_bytes__) = e2e_gleam.read_file_bytes("../../test_documents/pdf/fake_memo.pdf")
  let result = kreuzberg.detect_mime_type_from_bytes(data_bytes__)
  result |> should.be_ok()
  let assert Ok(r) = result
}

// Detect PNG MIME type from bytes
pub fn detect_mime_bytes_png_test() {
  let assert Ok(data_bytes__) = e2e_gleam.read_file_bytes("../../test_documents/images/test_hello_world.png")
  let result = kreuzberg.detect_mime_type_from_bytes(data_bytes__)
  result |> should.be_ok()
  let assert Ok(r) = result
}

// get_extensions unknown MIME
pub fn get_extensions_unknown_mime_test() {
  kreuzberg.get_extensions_for_mime("application/x-totally-unknown") |> should.be_error()
}
