// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:536d1a7efbe1438e1ccf7c96df71f5267ddb8b4310dde9290ca7f6e740e5221a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import gleeunit
import gleeunit/should
import kreuzberg
import e2e_gleam

import gleam/list
import gleam/string

// Get file extensions for DOCX MIME type
pub fn extensions_docx_test() {
  let result = kreuzberg.get_extensions_for_mime("application/vnd.openxmlformats-officedocument.wordprocessingml.document")
  result |> should.be_ok()
  let assert Ok(r) = result
}

// Get file extensions for HTML MIME type
pub fn extensions_html_test() {
  let result = kreuzberg.get_extensions_for_mime("text/html")
  result |> should.be_ok()
  let assert Ok(r) = result
}

// Get file extensions for PDF MIME type
pub fn extensions_pdf_test() {
  let result = kreuzberg.get_extensions_for_mime("application/pdf")
  result |> should.be_ok()
  let assert Ok(r) = result
  r |> list.any(fn(item__) { string.contains(item__, "pdf") }) |> should.equal(True)
}
