# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:841e2489f4e680f558e000364f4ba7f758ddbe0802cc76d3042699aa84130e5e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

#' @useDynLib kreuzberg, .registration = TRUE
NULL
