// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3449a020c47419d996897382ffc7218b4b382784daae55aa8bb623b2237bb55a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from "vitest";
import { extractFile, renderPdfPageToPng } from "kreuzberg";

describe("error", () => {
  it("error_file_not_found_async: Error when file does not exist (async)", async () => {
    await expect(async () => {
      await extractFile("nonexistent/file.pdf");
    }).rejects.toThrow();
  });

  it("error_render_corrupt_pdf: Error when rendering page from corrupt PDF", async () => {
    await expect(async () => {
      await renderPdfPageToPng("pdf/corrupt_truncated.pdf", 0);
    }).rejects.toThrow();
  });

  it("error_render_invalid_page: Error when rendering page number exceeds document page count", async () => {
    await expect(async () => {
      await renderPdfPageToPng("pdf/fake_memo.pdf", 0);
    }).rejects.toThrow();
  });
});
