// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:509198a2f2287db008d9fcef0de31c2f88749bf74a5911f995e0303b489ff2ea
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from "vitest";
import { extractFile } from "kreuzberg";

describe("extraction", () => {
  it("extract_doc_basic: Extract text from a DOC file containing unit test lists", async () => {
    const result = await extractFile(null);
    expect(result.content.length).toBeGreaterThanOrEqual(10);
  });

  it("extract_email_basic: Extract content from an email file in EML format", async () => {
    await extractFile(null);
  });

  it("extract_pdf_basic: Extract text from a basic PDF document containing memo content", async () => {
    const result = await extractFile(null);
    expect(result.content.length).toBeGreaterThanOrEqual(50);
  });

  it("extract_pdf_code: Extract text from PDF containing code snippets and formulas", async () => {
    const result = await extractFile(null);
    expect(result.content.length).toBeGreaterThanOrEqual(20);
  });

  it("extract_pptx_basic: Extract text from a PowerPoint presentation file", async () => {
    await extractFile(null);
  });
});
