// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:15d4c5d8e242e36343e2310a5eaae935611706c3cda248bd454701900cad058a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from "vitest";
import {
  extractFile,
  listDocumentExtractors,
  listOcrBackends,
  listPostProcessors,
  listValidators,
} from "kreuzberg";

describe("registry", () => {
  it("list_document_extractors: List document extractors", () => {
    listDocumentExtractors({});
  });

  it("list_ocr_backends: List OCR backends", () => {
    listOcrBackends({});
  });

  it("list_post_processors: List post-processors", () => {
    listPostProcessors({});
  });

  it("list_validators: List validators", () => {
    listValidators({});
  });
});
