// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0a0b07fb99eb8d8a99401b81f44999e2bcd163a7d6575b22ef7c66fe0e3ce6a6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

import { describe, expect, it } from "vitest";
import {
  extractFile,
  listDocumentExtractors,
  listEmbeddingBackends,
  listOcrBackends,
  listPostProcessors,
  listRenderers,
  listValidators,
  WasmLayoutDetectionConfig,
  WasmLanguageDetectionConfig,
  WasmAccelerationConfig,
  WasmEmailConfig,
  WasmLlmConfig,
  WasmRakeParams,
  WasmImagePreprocessingConfig,
  WasmStructuredExtractionConfig,
  WasmTokenReductionOptions,
  WasmHierarchyConfig,
  WasmOcrPipelineConfig,
  WasmPostProcessorConfig,
  WasmPageConfig,
  WasmOcrElementConfig,
  WasmImageExtractionConfig,
  WasmContentFilterConfig,
  WasmChunkingConfig,
  WasmYakeParams,
  WasmPdfConfig,
  WasmOcrQualityThresholds,
  WasmTesseractConfig,
  WasmEmbeddingConfig,
  WasmOcrConfig,
  WasmKeywordConfig,
  WasmHtmlOutputConfig,
  WasmSecurityLimits,
  WasmTreeSitterConfig,
  WasmOcrPipelineStage,
  WasmTreeSitterProcessConfig,
} from "kreuzberg";
function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

describe("registry", () => {
  it("list_document_extractors: List document extractors", () => {
    listDocumentExtractors();
  });
  it("list_embedding_backends: List embedding backends", () => {
    listEmbeddingBackends();
  });
  it("list_ocr_backends: List OCR backends", () => {
    listOcrBackends();
  });
  it("list_post_processors: List post-processors", () => {
    listPostProcessors();
  });
  it("list_renderers: List renderers", () => {
    listRenderers();
  });
  it("list_validators: List validators", () => {
    listValidators();
  });
});
