// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ff1760d3965209a785b9840a5dc3d05fdaeb14acae82e9a1ce32fe166f598578
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from "vitest";
import { extractFile } from "kreuzberg";

describe("validate", () => {
  it("validate_binarization_invalid: Invalid binarization", async () => {
    await expect(async () => {
      await extractFile(null);
    }).rejects.toThrow();
  });

  it("validate_binarization_valid: Valid binarization", async () => {
    await extractFile(null);
  });

  it("validate_chunking_params_invalid: Chunking overlap >= max", async () => {
    await expect(async () => {
      await { max_characters: 50, overlap: 60 };
    }).rejects.toThrow();
  });

  it("validate_chunking_params_valid: Valid chunking params", () => {
    ({ max_characters: 500, overlap: 50 });
  });

  it("validate_confidence_boundary: Confidence at 1.0", async () => {
    await extractFile(null);
  });

  it("validate_confidence_negative: Negative confidence", async () => {
    await expect(async () => {
      await extractFile(null);
    }).rejects.toThrow();
  });

  it("validate_confidence_over: Confidence > 1", async () => {
    await expect(async () => {
      await extractFile(null);
    }).rejects.toThrow();
  });

  it("validate_confidence_zero: Confidence at 0.0", async () => {
    await extractFile(null);
  });

  it("validate_host_empty: Empty host rejected", async () => {
    await expect(async () => {
      await extractFile(null);
    }).rejects.toThrow();
  });

  it("validate_ocr_backend_invalid: Invalid OCR backend", async () => {
    await expect(async () => {
      await extractFile(null);
    }).rejects.toThrow();
  });

  it("validate_ocr_backend_valid: Valid OCR backend", async () => {
    await extractFile(null);
  });

  it("validate_port_max: Port 65535 accepted", async () => {
    await extractFile(null);
  });

  it("validate_port_over: Port over 65535", async () => {
    await expect(async () => {
      await extractFile(null);
    }).rejects.toThrow();
  });

  it("validate_port_zero: Port 0 rejected", async () => {
    await expect(async () => {
      await extractFile(null);
    }).rejects.toThrow();
  });

  it("validate_reduction_level_invalid: Invalid reduction level", async () => {
    await expect(async () => {
      await extractFile(null);
    }).rejects.toThrow();
  });

  it("validate_reduction_level_valid: Valid reduction level", async () => {
    await extractFile(null);
  });
});
