// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:33c0f664689a5ab808fac3cbaaccf7ac4c118fe656666031b6cabc87ff3ea3f9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from "vitest";
import { extractFile } from "kreuzberg";

describe("xml", () => {
  it("xml_plant_catalog: XML plant catalog to validate streaming XML extraction.", async () => {
    const result = await extractFile("xml/plant_catalog.xml");
    expect(result.mimeType.trim()).toBe("application/xml");
    expect(result.content.length).toBeGreaterThanOrEqual(100);
  });
});
