# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5133e7d9d57ca28d1ad4e09454d299661c0c6dec81148cd6966540c3cceb387a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require_relative 'spec_helper'

RSpec.describe 'table' do
  it 'table_csv_extraction: CSV file extraction produces content' do
    result = Kreuzberg.extract_file_sync('csv/stanley_cups.csv')
    expect(result.content.length).to be >= 10
  end

  it 'table_html_extraction: HTML table extraction produces markdown format' do
    result = Kreuzberg.extract_file_sync('html/simple_table.html', nil, Kreuzberg::ExtractionConfig.new(output_format: 'markdown'))
    expect(['|'].any? { |v| result.content.to_s.include?(v) }).to be(true)
  end

  it 'table_xlsx_markdown: XLSX extraction produces markdown table format' do
    result = Kreuzberg.extract_file_sync('xlsx/stanley_cups.xlsx', nil, Kreuzberg::ExtractionConfig.new(output_format: 'markdown'))
    expect(['|', '---'].any? { |v| result.content.to_s.include?(v) }).to be(true)
  end
end
