// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4b0f947f4fb5037f1ed6468adf274c146cacae6e55a2a25522d817236b2617d2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'dart:io';

// E2e tests for category: async
void main() {
  test('extract_bytes empty MIME async', () async {
    final result = await extractBytes();
  });

  test('extract_bytes unsupported MIME async', () async {
    final result = await extractBytes();
  });

}
