// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b2b5b9986fb9e79c1fd6eb0663d57e6f6868194a841c7e5610c307a708a4e535
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'dart:io';

// E2e tests for category: format_specific
void main() {
  test('Standalone DOCX extraction using extract_bytes_sync', () {
    final result = extractBytesSync();
  });

  test('Standalone PDF text extraction using extract_bytes_sync', () {
    final result = extractBytesSync();
  });

  test('PPTX presentation extraction using extract_file_sync', () {
    final result = extractFileSync();
  });

  test('XLSX spreadsheet extraction using extract_file_sync', () {
    final result = extractFileSync();
  });

}
