// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4f57698a1998ff2765e6120ce59a636640d9100891c3fcb86103a0b96c00dc7e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'dart:io';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: registry
void main() {
  setUpAll(() async {
    await RustLib.init();
    final _testDocs = Platform.environment['FIXTURES_DIR'] ?? '../../test_documents';
    final _dir = Directory(_testDocs);
    if (_dir.existsSync()) Directory.current = _dir;
  });

  test('List document extractors', () async {
    final result = await KreuzbergBridge.listDocumentExtractors();
  });

  test('List embedding backends', () async {
    final result = await KreuzbergBridge.extractBytes('application/octet-stream');
  });

  test('List OCR backends', () async {
    final result = await KreuzbergBridge.listOcrBackends();
  });

  test('List post-processors', () async {
    final result = await KreuzbergBridge.listPostProcessors();
  });

  test('List renderers', () async {
    final result = await KreuzbergBridge.extractBytes('application/octet-stream');
  });

  test('List validators', () async {
    final result = await KreuzbergBridge.listValidators();
  });

}
