// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:03ed82db8498c93380825adda80fd92e4ad2890437973133b6a6bed8f2a4a539
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'dart:io';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: registry_operations
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('Get file extensions for DOCX MIME type', () async {
    final result = await KreuzbergBridge.getExtensionsForMime('application/vnd.openxmlformats-officedocument.wordprocessingml.document');
  });

  test('Get file extensions for HTML MIME type', () async {
    final result = await KreuzbergBridge.getExtensionsForMime('text/html');
  });

  test('Get file extensions for PDF MIME type', () async {
    final result = await KreuzbergBridge.getExtensionsForMime('application/pdf');
  });

}
