// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1ec848341f62df7d9037e82279d25ab8771c2958b65a3b8ea2ceb36172ef37f9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'dart:io';

// E2e tests for category: smoke
void main() {
  test('OCR: PNG image extraction with OCR enabled. In WASM this exercises the Uint8Array bridge parameter and Promise await in the generated OcrBackend bridge.', () async {
    final result = await extractBytes();
  });

  test('Smoke test: DOCX with formatted text', () async {
    final result = await extractFile();
  });

  test('Smoke test: HTML table extraction', () async {
    final result = await extractFile();
  });

  test('Smoke test: JSON file extraction', () async {
    final result = await extractFile();
  });

  test('Smoke test: PDF with simple text extraction', () async {
    final result = await extractFile();
  });

  test('Smoke test: Plain text file', () async {
    final result = await extractFile();
  });

  test('Smoke test: XLSX with basic spreadsheet data including tables', () async {
    final result = await extractFile();
  });

}
