// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f6c0e662a29de5818daf279e2dea561198908a01b1b7132b01119695d1e8991d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: cache_ops
package e2e_test

import (
	"testing"

	"github.com/stretchr/testify/assert"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_GenerateCacheKeyComplex(t *testing.T) {
	// Complex cache key
	result, err := kreuzberg.ExtractFile(nil, nil, kreuzberg.ExtractionConfig{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.GreaterOrEqual(t, len(result.Result), 5, "expected length >= 5")
}

func Test_ValidateCacheKeyInvalid(t *testing.T) {
	// Invalid cache key returns false
	result, err := kreuzberg.ExtractFile(nil, nil, kreuzberg.ExtractionConfig{})
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	assert.False(t, result.Result, "expected false")
}
