// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:07e78422ed1cc61cdee2d7ea97f4bc4129fa8e653743358387af1a1d7ad9bd9b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: language
package e2e_test

import (
	"encoding/json"
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v4"
)

func Test_LangDetectConfig(t *testing.T) {
	// Language detection with specific language config
	var config kreuzberg.ExtractionConfig
	if err := json.Unmarshal([]byte(`{"language_detection":{"enabled":true,"languages":["en","de","fr"]}}`), &config); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	_, err := kreuzberg.ExtractFileSync(`semantic/mixed_topics.txt`, nil, config)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_LangDetectEnglish(t *testing.T) {
	// Language detection works on English text
	var config kreuzberg.ExtractionConfig
	if err := json.Unmarshal([]byte(`{"language_detection":{"enabled":true}}`), &config); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	_, err := kreuzberg.ExtractFileSync(`semantic/mixed_topics.txt`, nil, config)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
