// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5aebb7980aa2c0915564d451f6980098f31d92b9c376b3d1a4b181bb89b1c76c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: serialization
package e2e_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func Test_SerializeJsonBasic(t *testing.T) {
	// Serialize extraction result to JSON
	t.Skip("non-HTTP fixture: Go binding does not expose a callable for the configured `[e2e.call]` function")
}

func Test_SerializeJsonPdf(t *testing.T) {
	// Serialize PDF extraction to JSON
	t.Skip("non-HTTP fixture: Go binding does not expose a callable for the configured `[e2e.call]` function")
}

func Test_SerializeToonBasic(t *testing.T) {
	// Serialize extraction result to TOON format
	t.Skip("non-HTTP fixture: Go binding does not expose a callable for the configured `[e2e.call]` function")
}

func Test_SerializeToonPdf(t *testing.T) {
	// Serialize PDF extraction to TOON
	t.Skip("non-HTTP fixture: Go binding does not expose a callable for the configured `[e2e.call]` function")
}
